using System;
using System.Collections.Generic;
using System.Data.Common;

namespace App.BL.AIAgent.GenericAgent
{
    /// <summary>
    /// DB-backed blackboard for multi-agent workflows.
    /// Each workflow instance is scoped by a WorkflowId (GUID) so multiple concurrent
    /// workflows don't interfere. The WorkflowId is generated by GenericAgentEngine on the
    /// first (orchestrator) run and propagated to all child agents via AgentCallPlugin.
    /// </summary>
    public static class AppAgentSharedContextBL
    {
        /// <summary>
        /// Returns the stored JSON string for the given scope + key, or null if not found.
        /// </summary>
        public static string ReadContext(string scopeId, string key, int dataSourceId)
        {
            if (string.IsNullOrWhiteSpace(scopeId) || string.IsNullOrWhiteSpace(key)) return null;
            try
            {
                var fixture = GetFixture(dataSourceId);
                if (fixture == null) return null;

                var dt = fixture.RetriveDataTable(
                    "SELECT DataJson FROM dbo.AppAgentSharedContext WHERE ScopeId=@S AND ContextKey=@K",
                    new List<DbParameter>
                    {
                        P(fixture, "@S", scopeId),
                        P(fixture, "@K", key)
                    });

                if (dt == null || dt.Rows.Count == 0) return null;
                return dt.Rows[0]["DataJson"]?.ToString();
            }
            catch (Exception ex)
            {
                NLog.LogManager.GetCurrentClassLogger().Error(ex, nameof(ReadContext));
                return null;
            }
        }

        /// <summary>
        /// Upserts the JSON string for the given scope + key.
        /// </summary>
        public static void WriteContext(string scopeId, string key, string dataJson, int dataSourceId)
        {
            if (string.IsNullOrWhiteSpace(scopeId) || string.IsNullOrWhiteSpace(key) || dataJson == null) return;
            try
            {
                var fixture = GetFixture(dataSourceId);
                if (fixture == null) return;

                const string sql = @"
IF EXISTS (SELECT 1 FROM dbo.AppAgentSharedContext WHERE ScopeId=@S AND ContextKey=@K)
    UPDATE dbo.AppAgentSharedContext SET DataJson=@J, UpdatedAt=GETUTCDATE() WHERE ScopeId=@S AND ContextKey=@K
ELSE
    INSERT INTO dbo.AppAgentSharedContext (ScopeId, ContextKey, DataJson, UpdatedAt)
    VALUES (@S, @K, @J, GETUTCDATE())";

                fixture.ExecuteNonQueryResult(sql, new List<DbParameter>
                {
                    P(fixture, "@S", scopeId),
                    P(fixture, "@K", key),
                    P(fixture, "@J", dataJson)
                });
            }
            catch (Exception ex)
            {
                NLog.LogManager.GetCurrentClassLogger().Error(ex, nameof(WriteContext));
            }
        }

        private static DatabaseSchemaMrg.DatabaseFixture GetFixture(int dataSourceId)
        {
            if (dataSourceId > 0)
                return AppCacheManagerBL.GetOneDatabaseFixture(dataSourceId);
            var id = AppDataSourceRegisterBL.GetDefaultDataSourceRegId();
            if (!id.HasValue) return null;
            return AppCacheManagerBL.GetOneDatabaseFixture(id.Value);
        }

        private static DbParameter P(DatabaseSchemaMrg.DatabaseFixture f, string name, object value)
        {
            var p = f.CreateParameter(name);
            p.Value = value ?? DBNull.Value;
            return p;
        }
    }
}
