//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:16 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppApplicationAssetsItem'.<br/><br/></summary>
	[Serializable]
	public partial class AppApplicationAssetsItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private AppDesktopEntity _appDesktop;
		private AppFormEntity _appForm;
		private AppListMenuEntity _appListMenu;
		private AppProjectOrWorkFlowEntity _appProjectOrWorkFlow;
		private AppReportEntity _appReport;
		private AppSearchEntity _appSearch;
		private AppTransactionEntity _appTransaction;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppApplicationAssetsItemEntityStaticMetaData _staticMetaData = new AppApplicationAssetsItemEntityStaticMetaData();
		private static AppApplicationAssetsItemRelations _relationsFactory = new AppApplicationAssetsItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppDesktop</summary>
			public static readonly string AppDesktop = "AppDesktop";
			/// <summary>Member name AppForm</summary>
			public static readonly string AppForm = "AppForm";
			/// <summary>Member name AppListMenu</summary>
			public static readonly string AppListMenu = "AppListMenu";
			/// <summary>Member name AppProjectOrWorkFlow</summary>
			public static readonly string AppProjectOrWorkFlow = "AppProjectOrWorkFlow";
			/// <summary>Member name AppReport</summary>
			public static readonly string AppReport = "AppReport";
			/// <summary>Member name AppSearch</summary>
			public static readonly string AppSearch = "AppSearch";
			/// <summary>Member name AppTransaction</summary>
			public static readonly string AppTransaction = "AppTransaction";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppApplicationAssetsItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppApplicationAssetsItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppApplicationAssetsItemEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppApplicationAssetsItemEntity, typeof(AppApplicationAssetsItemEntity), typeof(AppApplicationAssetsItemEntityFactory), false);
				AddNavigatorMetaData<AppApplicationAssetsItemEntity, AppDesktopEntity>("AppDesktop", "AppApplicationAssetsItem", (a, b) => a._appDesktop = b, a => a._appDesktop, (a, b) => a.AppDesktop = b, APP.LBL.RelationClasses.StaticAppApplicationAssetsItemRelations.AppDesktopEntityUsingDesktopIdStatic, ()=>new AppApplicationAssetsItemRelations().AppDesktopEntityUsingDesktopId, null, new int[] { (int)AppApplicationAssetsItemFieldIndex.DesktopId }, null, true, (int)APP.LBL.EntityType.AppDesktopEntity);
				AddNavigatorMetaData<AppApplicationAssetsItemEntity, AppFormEntity>("AppForm", "AppApplicationAssetsItem", (a, b) => a._appForm = b, a => a._appForm, (a, b) => a.AppForm = b, APP.LBL.RelationClasses.StaticAppApplicationAssetsItemRelations.AppFormEntityUsingFormIdStatic, ()=>new AppApplicationAssetsItemRelations().AppFormEntityUsingFormId, null, new int[] { (int)AppApplicationAssetsItemFieldIndex.FormId }, null, true, (int)APP.LBL.EntityType.AppFormEntity);
				AddNavigatorMetaData<AppApplicationAssetsItemEntity, AppListMenuEntity>("AppListMenu", "AppApplicationAssetsItem", (a, b) => a._appListMenu = b, a => a._appListMenu, (a, b) => a.AppListMenu = b, APP.LBL.RelationClasses.StaticAppApplicationAssetsItemRelations.AppListMenuEntityUsingApplicationIdStatic, ()=>new AppApplicationAssetsItemRelations().AppListMenuEntityUsingApplicationId, null, new int[] { (int)AppApplicationAssetsItemFieldIndex.ApplicationId }, null, true, (int)APP.LBL.EntityType.AppListMenuEntity);
				AddNavigatorMetaData<AppApplicationAssetsItemEntity, AppProjectOrWorkFlowEntity>("AppProjectOrWorkFlow", "AppApplicationAssetsItem", (a, b) => a._appProjectOrWorkFlow = b, a => a._appProjectOrWorkFlow, (a, b) => a.AppProjectOrWorkFlow = b, APP.LBL.RelationClasses.StaticAppApplicationAssetsItemRelations.AppProjectOrWorkFlowEntityUsingProjectWorkflowIdStatic, ()=>new AppApplicationAssetsItemRelations().AppProjectOrWorkFlowEntityUsingProjectWorkflowId, null, new int[] { (int)AppApplicationAssetsItemFieldIndex.ProjectWorkflowId }, null, true, (int)APP.LBL.EntityType.AppProjectOrWorkFlowEntity);
				AddNavigatorMetaData<AppApplicationAssetsItemEntity, AppReportEntity>("AppReport", "AppApplicationAssetsItem", (a, b) => a._appReport = b, a => a._appReport, (a, b) => a.AppReport = b, APP.LBL.RelationClasses.StaticAppApplicationAssetsItemRelations.AppReportEntityUsingReportIdStatic, ()=>new AppApplicationAssetsItemRelations().AppReportEntityUsingReportId, null, new int[] { (int)AppApplicationAssetsItemFieldIndex.ReportId }, null, true, (int)APP.LBL.EntityType.AppReportEntity);
				AddNavigatorMetaData<AppApplicationAssetsItemEntity, AppSearchEntity>("AppSearch", "AppApplicationAssetsItem", (a, b) => a._appSearch = b, a => a._appSearch, (a, b) => a.AppSearch = b, APP.LBL.RelationClasses.StaticAppApplicationAssetsItemRelations.AppSearchEntityUsingSearchIdStatic, ()=>new AppApplicationAssetsItemRelations().AppSearchEntityUsingSearchId, null, new int[] { (int)AppApplicationAssetsItemFieldIndex.SearchId }, null, true, (int)APP.LBL.EntityType.AppSearchEntity);
				AddNavigatorMetaData<AppApplicationAssetsItemEntity, AppTransactionEntity>("AppTransaction", "AppApplicationAssetsItem", (a, b) => a._appTransaction = b, a => a._appTransaction, (a, b) => a.AppTransaction = b, APP.LBL.RelationClasses.StaticAppApplicationAssetsItemRelations.AppTransactionEntityUsingTransactionIdStatic, ()=>new AppApplicationAssetsItemRelations().AppTransactionEntityUsingTransactionId, null, new int[] { (int)AppApplicationAssetsItemFieldIndex.TransactionId }, null, true, (int)APP.LBL.EntityType.AppTransactionEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppApplicationAssetsItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppApplicationAssetsItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppApplicationAssetsItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppApplicationAssetsItemEntity</param>
		public AppApplicationAssetsItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="assetsItemId">PK value for AppApplicationAssetsItem which data should be fetched into this AppApplicationAssetsItem object</param>
		public AppApplicationAssetsItemEntity(System.Int32 assetsItemId) : this(assetsItemId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="assetsItemId">PK value for AppApplicationAssetsItem which data should be fetched into this AppApplicationAssetsItem object</param>
		/// <param name="validator">The custom validator object for this AppApplicationAssetsItemEntity</param>
		public AppApplicationAssetsItemEntity(System.Int32 assetsItemId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.AssetsItemId = assetsItemId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppApplicationAssetsItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppDesktop' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppDesktop() { return CreateRelationInfoForNavigator("AppDesktop"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppForm' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppForm() { return CreateRelationInfoForNavigator("AppForm"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppListMenu' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppListMenu() { return CreateRelationInfoForNavigator("AppListMenu"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppProjectOrWorkFlow' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppProjectOrWorkFlow() { return CreateRelationInfoForNavigator("AppProjectOrWorkFlow"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppReport' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppReport() { return CreateRelationInfoForNavigator("AppReport"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppSearch' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSearch() { return CreateRelationInfoForNavigator("AppSearch"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppTransaction' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppTransaction() { return CreateRelationInfoForNavigator("AppTransaction"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppApplicationAssetsItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppApplicationAssetsItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppDesktop' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppDesktop { get { return _staticMetaData.GetPrefetchPathElement("AppDesktop", CommonEntityBase.CreateEntityCollection<AppDesktopEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppForm' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppForm { get { return _staticMetaData.GetPrefetchPathElement("AppForm", CommonEntityBase.CreateEntityCollection<AppFormEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppListMenu' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppListMenu { get { return _staticMetaData.GetPrefetchPathElement("AppListMenu", CommonEntityBase.CreateEntityCollection<AppListMenuEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppProjectOrWorkFlow' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppProjectOrWorkFlow { get { return _staticMetaData.GetPrefetchPathElement("AppProjectOrWorkFlow", CommonEntityBase.CreateEntityCollection<AppProjectOrWorkFlowEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppReport' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppReport { get { return _staticMetaData.GetPrefetchPathElement("AppReport", CommonEntityBase.CreateEntityCollection<AppReportEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSearch' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSearch { get { return _staticMetaData.GetPrefetchPathElement("AppSearch", CommonEntityBase.CreateEntityCollection<AppSearchEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppTransaction' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppTransaction { get { return _staticMetaData.GetPrefetchPathElement("AppTransaction", CommonEntityBase.CreateEntityCollection<AppTransactionEntity>()); } }

		/// <summary>The AssetsItemId property of the Entity AppApplicationAssetsItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppApplicationAssetsItem"."AssetsItemID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 AssetsItemId
		{
			get { return (System.Int32)GetValue((int)AppApplicationAssetsItemFieldIndex.AssetsItemId, true); }
			set { SetValue((int)AppApplicationAssetsItemFieldIndex.AssetsItemId, value); }
		}

		/// <summary>The ApplicationId property of the Entity AppApplicationAssetsItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppApplicationAssetsItem"."ApplicationID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> ApplicationId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppApplicationAssetsItemFieldIndex.ApplicationId, false); }
			set { SetValue((int)AppApplicationAssetsItemFieldIndex.ApplicationId, value); }
		}

		/// <summary>The Name property of the Entity AppApplicationAssetsItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppApplicationAssetsItem"."Name".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)AppApplicationAssetsItemFieldIndex.Name, true); }
			set { SetValue((int)AppApplicationAssetsItemFieldIndex.Name, value); }
		}

		/// <summary>The Description property of the Entity AppApplicationAssetsItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppApplicationAssetsItem"."Description".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)AppApplicationAssetsItemFieldIndex.Description, true); }
			set { SetValue((int)AppApplicationAssetsItemFieldIndex.Description, value); }
		}

		/// <summary>The FormId property of the Entity AppApplicationAssetsItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppApplicationAssetsItem"."FormID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> FormId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppApplicationAssetsItemFieldIndex.FormId, false); }
			set { SetValue((int)AppApplicationAssetsItemFieldIndex.FormId, value); }
		}

		/// <summary>The TransactionId property of the Entity AppApplicationAssetsItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppApplicationAssetsItem"."TransactionID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> TransactionId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppApplicationAssetsItemFieldIndex.TransactionId, false); }
			set { SetValue((int)AppApplicationAssetsItemFieldIndex.TransactionId, value); }
		}

		/// <summary>The ProjectWorkflowId property of the Entity AppApplicationAssetsItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppApplicationAssetsItem"."ProjectWorkflowID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> ProjectWorkflowId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppApplicationAssetsItemFieldIndex.ProjectWorkflowId, false); }
			set { SetValue((int)AppApplicationAssetsItemFieldIndex.ProjectWorkflowId, value); }
		}

		/// <summary>The SearchId property of the Entity AppApplicationAssetsItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppApplicationAssetsItem"."SearchID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> SearchId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppApplicationAssetsItemFieldIndex.SearchId, false); }
			set { SetValue((int)AppApplicationAssetsItemFieldIndex.SearchId, value); }
		}

		/// <summary>The ReportId property of the Entity AppApplicationAssetsItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppApplicationAssetsItem"."ReportID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> ReportId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppApplicationAssetsItemFieldIndex.ReportId, false); }
			set { SetValue((int)AppApplicationAssetsItemFieldIndex.ReportId, value); }
		}

		/// <summary>The DesktopId property of the Entity AppApplicationAssetsItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppApplicationAssetsItem"."DesktopID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> DesktopId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppApplicationAssetsItemFieldIndex.DesktopId, false); }
			set { SetValue((int)AppApplicationAssetsItemFieldIndex.DesktopId, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppApplicationAssetsItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppApplicationAssetsItem"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppApplicationAssetsItemFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppApplicationAssetsItemFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppApplicationAssetsItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppApplicationAssetsItem"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppApplicationAssetsItemFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppApplicationAssetsItemFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppApplicationAssetsItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppApplicationAssetsItem"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppApplicationAssetsItemFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppApplicationAssetsItemFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppApplicationAssetsItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppApplicationAssetsItem"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppApplicationAssetsItemFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppApplicationAssetsItemFieldIndex.AppModifiedById, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppApplicationAssetsItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppApplicationAssetsItem"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppApplicationAssetsItemFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppApplicationAssetsItemFieldIndex.AppCreatedByCompanyId, value); }
		}

		/// <summary>Gets / sets related entity of type 'AppDesktopEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppDesktopEntity AppDesktop
		{
			get { return _appDesktop; }
			set { SetSingleRelatedEntityNavigator(value, "AppDesktop"); }
		}

		/// <summary>Gets / sets related entity of type 'AppFormEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppFormEntity AppForm
		{
			get { return _appForm; }
			set { SetSingleRelatedEntityNavigator(value, "AppForm"); }
		}

		/// <summary>Gets / sets related entity of type 'AppListMenuEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppListMenuEntity AppListMenu
		{
			get { return _appListMenu; }
			set { SetSingleRelatedEntityNavigator(value, "AppListMenu"); }
		}

		/// <summary>Gets / sets related entity of type 'AppProjectOrWorkFlowEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppProjectOrWorkFlowEntity AppProjectOrWorkFlow
		{
			get { return _appProjectOrWorkFlow; }
			set { SetSingleRelatedEntityNavigator(value, "AppProjectOrWorkFlow"); }
		}

		/// <summary>Gets / sets related entity of type 'AppReportEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppReportEntity AppReport
		{
			get { return _appReport; }
			set { SetSingleRelatedEntityNavigator(value, "AppReport"); }
		}

		/// <summary>Gets / sets related entity of type 'AppSearchEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppSearchEntity AppSearch
		{
			get { return _appSearch; }
			set { SetSingleRelatedEntityNavigator(value, "AppSearch"); }
		}

		/// <summary>Gets / sets related entity of type 'AppTransactionEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppTransactionEntity AppTransaction
		{
			get { return _appTransaction; }
			set { SetSingleRelatedEntityNavigator(value, "AppTransaction"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppApplicationAssetsItemFieldIndex
	{
		///<summary>AssetsItemId. </summary>
		AssetsItemId,
		///<summary>ApplicationId. </summary>
		ApplicationId,
		///<summary>Name. </summary>
		Name,
		///<summary>Description. </summary>
		Description,
		///<summary>FormId. </summary>
		FormId,
		///<summary>TransactionId. </summary>
		TransactionId,
		///<summary>ProjectWorkflowId. </summary>
		ProjectWorkflowId,
		///<summary>SearchId. </summary>
		SearchId,
		///<summary>ReportId. </summary>
		ReportId,
		///<summary>DesktopId. </summary>
		DesktopId,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppApplicationAssetsItem. </summary>
	public partial class AppApplicationAssetsItemRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between AppApplicationAssetsItemEntity and AppDesktopEntity over the m:1 relation they have, using the relation between the fields: AppApplicationAssetsItem.DesktopId - AppDesktop.DesktopId</summary>
		public virtual IEntityRelation AppDesktopEntityUsingDesktopId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppDesktop", false, new[] { AppDesktopFields.DesktopId, AppApplicationAssetsItemFields.DesktopId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppApplicationAssetsItemEntity and AppFormEntity over the m:1 relation they have, using the relation between the fields: AppApplicationAssetsItem.FormId - AppForm.FormId</summary>
		public virtual IEntityRelation AppFormEntityUsingFormId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppForm", false, new[] { AppFormFields.FormId, AppApplicationAssetsItemFields.FormId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppApplicationAssetsItemEntity and AppListMenuEntity over the m:1 relation they have, using the relation between the fields: AppApplicationAssetsItem.ApplicationId - AppListMenu.MenuId</summary>
		public virtual IEntityRelation AppListMenuEntityUsingApplicationId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppListMenu", false, new[] { AppListMenuFields.MenuId, AppApplicationAssetsItemFields.ApplicationId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppApplicationAssetsItemEntity and AppProjectOrWorkFlowEntity over the m:1 relation they have, using the relation between the fields: AppApplicationAssetsItem.ProjectWorkflowId - AppProjectOrWorkFlow.ProjectId</summary>
		public virtual IEntityRelation AppProjectOrWorkFlowEntityUsingProjectWorkflowId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppProjectOrWorkFlow", false, new[] { AppProjectOrWorkFlowFields.ProjectId, AppApplicationAssetsItemFields.ProjectWorkflowId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppApplicationAssetsItemEntity and AppReportEntity over the m:1 relation they have, using the relation between the fields: AppApplicationAssetsItem.ReportId - AppReport.ReportId</summary>
		public virtual IEntityRelation AppReportEntityUsingReportId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppReport", false, new[] { AppReportFields.ReportId, AppApplicationAssetsItemFields.ReportId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppApplicationAssetsItemEntity and AppSearchEntity over the m:1 relation they have, using the relation between the fields: AppApplicationAssetsItem.SearchId - AppSearch.SearchId</summary>
		public virtual IEntityRelation AppSearchEntityUsingSearchId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppSearch", false, new[] { AppSearchFields.SearchId, AppApplicationAssetsItemFields.SearchId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppApplicationAssetsItemEntity and AppTransactionEntity over the m:1 relation they have, using the relation between the fields: AppApplicationAssetsItem.TransactionId - AppTransaction.TransactionId</summary>
		public virtual IEntityRelation AppTransactionEntityUsingTransactionId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppTransaction", false, new[] { AppTransactionFields.TransactionId, AppApplicationAssetsItemFields.TransactionId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppApplicationAssetsItemRelations
	{
		internal static readonly IEntityRelation AppDesktopEntityUsingDesktopIdStatic = new AppApplicationAssetsItemRelations().AppDesktopEntityUsingDesktopId;
		internal static readonly IEntityRelation AppFormEntityUsingFormIdStatic = new AppApplicationAssetsItemRelations().AppFormEntityUsingFormId;
		internal static readonly IEntityRelation AppListMenuEntityUsingApplicationIdStatic = new AppApplicationAssetsItemRelations().AppListMenuEntityUsingApplicationId;
		internal static readonly IEntityRelation AppProjectOrWorkFlowEntityUsingProjectWorkflowIdStatic = new AppApplicationAssetsItemRelations().AppProjectOrWorkFlowEntityUsingProjectWorkflowId;
		internal static readonly IEntityRelation AppReportEntityUsingReportIdStatic = new AppApplicationAssetsItemRelations().AppReportEntityUsingReportId;
		internal static readonly IEntityRelation AppSearchEntityUsingSearchIdStatic = new AppApplicationAssetsItemRelations().AppSearchEntityUsingSearchId;
		internal static readonly IEntityRelation AppTransactionEntityUsingTransactionIdStatic = new AppApplicationAssetsItemRelations().AppTransactionEntityUsingTransactionId;

		/// <summary>CTor</summary>
		static StaticAppApplicationAssetsItemRelations() { }
	}
}
