//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:16 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppDatabaseDiagram'.<br/><br/></summary>
	[Serializable]
	public partial class AppDatabaseDiagramEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<AppDatabaseDiagramItemEntity> _appDatabaseDiagramItem;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppDatabaseDiagramEntityStaticMetaData _staticMetaData = new AppDatabaseDiagramEntityStaticMetaData();
		private static AppDatabaseDiagramRelations _relationsFactory = new AppDatabaseDiagramRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppDatabaseDiagramItem</summary>
			public static readonly string AppDatabaseDiagramItem = "AppDatabaseDiagramItem";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppDatabaseDiagramEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppDatabaseDiagramEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppDatabaseDiagramEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppDatabaseDiagramEntity, typeof(AppDatabaseDiagramEntity), typeof(AppDatabaseDiagramEntityFactory), false);
				AddNavigatorMetaData<AppDatabaseDiagramEntity, EntityCollection<AppDatabaseDiagramItemEntity>>("AppDatabaseDiagramItem", a => a._appDatabaseDiagramItem, (a, b) => a._appDatabaseDiagramItem = b, a => a.AppDatabaseDiagramItem, () => new AppDatabaseDiagramRelations().AppDatabaseDiagramItemEntityUsingDiagramId, typeof(AppDatabaseDiagramItemEntity), (int)APP.LBL.EntityType.AppDatabaseDiagramItemEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppDatabaseDiagramEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppDatabaseDiagramEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppDatabaseDiagramEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppDatabaseDiagramEntity</param>
		public AppDatabaseDiagramEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="diagramId">PK value for AppDatabaseDiagram which data should be fetched into this AppDatabaseDiagram object</param>
		public AppDatabaseDiagramEntity(System.Int32 diagramId) : this(diagramId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="diagramId">PK value for AppDatabaseDiagram which data should be fetched into this AppDatabaseDiagram object</param>
		/// <param name="validator">The custom validator object for this AppDatabaseDiagramEntity</param>
		public AppDatabaseDiagramEntity(System.Int32 diagramId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.DiagramId = diagramId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppDatabaseDiagramEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppDatabaseDiagramItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppDatabaseDiagramItem() { return CreateRelationInfoForNavigator("AppDatabaseDiagramItem"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppDatabaseDiagramEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppDatabaseDiagramRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppDatabaseDiagramItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppDatabaseDiagramItem { get { return _staticMetaData.GetPrefetchPathElement("AppDatabaseDiagramItem", CommonEntityBase.CreateEntityCollection<AppDatabaseDiagramItemEntity>()); } }

		/// <summary>The DiagramId property of the Entity AppDatabaseDiagram<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDatabaseDiagram"."DiagramID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 DiagramId
		{
			get { return (System.Int32)GetValue((int)AppDatabaseDiagramFieldIndex.DiagramId, true); }
			set { SetValue((int)AppDatabaseDiagramFieldIndex.DiagramId, value); }
		}

		/// <summary>The DiagramName property of the Entity AppDatabaseDiagram<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDatabaseDiagram"."DiagramName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String DiagramName
		{
			get { return (System.String)GetValue((int)AppDatabaseDiagramFieldIndex.DiagramName, true); }
			set { SetValue((int)AppDatabaseDiagramFieldIndex.DiagramName, value); }
		}

		/// <summary>The Description property of the Entity AppDatabaseDiagram<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDatabaseDiagram"."Description".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)AppDatabaseDiagramFieldIndex.Description, true); }
			set { SetValue((int)AppDatabaseDiagramFieldIndex.Description, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppDatabaseDiagram<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDatabaseDiagram"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppDatabaseDiagramFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppDatabaseDiagramFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppDatabaseDiagram<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDatabaseDiagram"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppDatabaseDiagramFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppDatabaseDiagramFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppDatabaseDiagram<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDatabaseDiagram"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppDatabaseDiagramFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppDatabaseDiagramFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppDatabaseDiagram<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDatabaseDiagram"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppDatabaseDiagramFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppDatabaseDiagramFieldIndex.AppModifiedById, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppDatabaseDiagram<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDatabaseDiagram"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppDatabaseDiagramFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppDatabaseDiagramFieldIndex.AppCreatedByCompanyId, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'AppDatabaseDiagramItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppDatabaseDiagramItemEntity))]
		public virtual EntityCollection<AppDatabaseDiagramItemEntity> AppDatabaseDiagramItem { get { return GetOrCreateEntityCollection<AppDatabaseDiagramItemEntity, AppDatabaseDiagramItemEntityFactory>("AppDatabaseDiagram", true, false, ref _appDatabaseDiagramItem); } }

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppDatabaseDiagramFieldIndex
	{
		///<summary>DiagramId. </summary>
		DiagramId,
		///<summary>DiagramName. </summary>
		DiagramName,
		///<summary>Description. </summary>
		Description,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppDatabaseDiagram. </summary>
	public partial class AppDatabaseDiagramRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between AppDatabaseDiagramEntity and AppDatabaseDiagramItemEntity over the 1:n relation they have, using the relation between the fields: AppDatabaseDiagram.DiagramId - AppDatabaseDiagramItem.DiagramId</summary>
		public virtual IEntityRelation AppDatabaseDiagramItemEntityUsingDiagramId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppDatabaseDiagramItem", true, new[] { AppDatabaseDiagramFields.DiagramId, AppDatabaseDiagramItemFields.DiagramId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppDatabaseDiagramRelations
	{
		internal static readonly IEntityRelation AppDatabaseDiagramItemEntityUsingDiagramIdStatic = new AppDatabaseDiagramRelations().AppDatabaseDiagramItemEntityUsingDiagramId;

		/// <summary>CTor</summary>
		static StaticAppDatabaseDiagramRelations() { }
	}
}
