//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:16 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppDesktopItem'.<br/><br/></summary>
	[Serializable]
	public partial class AppDesktopItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private AppDesktopEntity _appDesktop;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppDesktopItemEntityStaticMetaData _staticMetaData = new AppDesktopItemEntityStaticMetaData();
		private static AppDesktopItemRelations _relationsFactory = new AppDesktopItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppDesktop</summary>
			public static readonly string AppDesktop = "AppDesktop";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppDesktopItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppDesktopItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppDesktopItemEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppDesktopItemEntity, typeof(AppDesktopItemEntity), typeof(AppDesktopItemEntityFactory), false);
				AddNavigatorMetaData<AppDesktopItemEntity, AppDesktopEntity>("AppDesktop", "AppDesktopItem", (a, b) => a._appDesktop = b, a => a._appDesktop, (a, b) => a.AppDesktop = b, APP.LBL.RelationClasses.StaticAppDesktopItemRelations.AppDesktopEntityUsingDesktopIdStatic, ()=>new AppDesktopItemRelations().AppDesktopEntityUsingDesktopId, null, new int[] { (int)AppDesktopItemFieldIndex.DesktopId }, null, true, (int)APP.LBL.EntityType.AppDesktopEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppDesktopItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppDesktopItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppDesktopItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppDesktopItemEntity</param>
		public AppDesktopItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="desktopItemId">PK value for AppDesktopItem which data should be fetched into this AppDesktopItem object</param>
		public AppDesktopItemEntity(System.Int32 desktopItemId) : this(desktopItemId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="desktopItemId">PK value for AppDesktopItem which data should be fetched into this AppDesktopItem object</param>
		/// <param name="validator">The custom validator object for this AppDesktopItemEntity</param>
		public AppDesktopItemEntity(System.Int32 desktopItemId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.DesktopItemId = desktopItemId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppDesktopItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppDesktop' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppDesktop() { return CreateRelationInfoForNavigator("AppDesktop"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppDesktopItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppDesktopItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppDesktop' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppDesktop { get { return _staticMetaData.GetPrefetchPathElement("AppDesktop", CommonEntityBase.CreateEntityCollection<AppDesktopEntity>()); } }

		/// <summary>The DesktopItemId property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."DesktopItemID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 DesktopItemId
		{
			get { return (System.Int32)GetValue((int)AppDesktopItemFieldIndex.DesktopItemId, true); }
			set { SetValue((int)AppDesktopItemFieldIndex.DesktopItemId, value); }
		}

		/// <summary>The DesktopId property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."DesktopID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> DesktopId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppDesktopItemFieldIndex.DesktopId, false); }
			set { SetValue((int)AppDesktopItemFieldIndex.DesktopId, value); }
		}

		/// <summary>The WidgetItemType property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."WidgetItemType".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> WidgetItemType
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppDesktopItemFieldIndex.WidgetItemType, false); }
			set { SetValue((int)AppDesktopItemFieldIndex.WidgetItemType, value); }
		}

		/// <summary>The FlowOrGridLayoutSortOrder property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."FlowOrGridLayoutSortOrder".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> FlowOrGridLayoutSortOrder
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppDesktopItemFieldIndex.FlowOrGridLayoutSortOrder, false); }
			set { SetValue((int)AppDesktopItemFieldIndex.FlowOrGridLayoutSortOrder, value); }
		}

		/// <summary>The StyleLayoutInfo property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."StyleLayoutInfo".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String StyleLayoutInfo
		{
			get { return (System.String)GetValue((int)AppDesktopItemFieldIndex.StyleLayoutInfo, true); }
			set { SetValue((int)AppDesktopItemFieldIndex.StyleLayoutInfo, value); }
		}

		/// <summary>The DomElementTag property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."DomElementTag".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String DomElementTag
		{
			get { return (System.String)GetValue((int)AppDesktopItemFieldIndex.DomElementTag, true); }
			set { SetValue((int)AppDesktopItemFieldIndex.DomElementTag, value); }
		}

		/// <summary>The ParameterKeyValue property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."ParameterKeyValue".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ParameterKeyValue
		{
			get { return (System.String)GetValue((int)AppDesktopItemFieldIndex.ParameterKeyValue, true); }
			set { SetValue((int)AppDesktopItemFieldIndex.ParameterKeyValue, value); }
		}

		/// <summary>The DisplayTitle property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."DisplayTitle".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String DisplayTitle
		{
			get { return (System.String)GetValue((int)AppDesktopItemFieldIndex.DisplayTitle, true); }
			set { SetValue((int)AppDesktopItemFieldIndex.DisplayTitle, value); }
		}

		/// <summary>The RowIndex property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."RowIndex".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> RowIndex
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppDesktopItemFieldIndex.RowIndex, false); }
			set { SetValue((int)AppDesktopItemFieldIndex.RowIndex, value); }
		}

		/// <summary>The ColumnIndex property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."ColumnIndex".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> ColumnIndex
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppDesktopItemFieldIndex.ColumnIndex, false); }
			set { SetValue((int)AppDesktopItemFieldIndex.ColumnIndex, value); }
		}

		/// <summary>The RowSpan property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."RowSpan".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> RowSpan
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppDesktopItemFieldIndex.RowSpan, false); }
			set { SetValue((int)AppDesktopItemFieldIndex.RowSpan, value); }
		}

		/// <summary>The ColumnSpan property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."ColumnSpan".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> ColumnSpan
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppDesktopItemFieldIndex.ColumnSpan, false); }
			set { SetValue((int)AppDesktopItemFieldIndex.ColumnSpan, value); }
		}

		/// <summary>The GridLayoutParentId property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."GridLayoutParentID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> GridLayoutParentId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppDesktopItemFieldIndex.GridLayoutParentId, false); }
			set { SetValue((int)AppDesktopItemFieldIndex.GridLayoutParentId, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppDesktopItemFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppDesktopItemFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppDesktopItemFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppDesktopItemFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppDesktopItemFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppDesktopItemFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppDesktopItemFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppDesktopItemFieldIndex.AppModifiedById, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppDesktopItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppDesktopItem"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppDesktopItemFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppDesktopItemFieldIndex.AppCreatedByCompanyId, value); }
		}

		/// <summary>Gets / sets related entity of type 'AppDesktopEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppDesktopEntity AppDesktop
		{
			get { return _appDesktop; }
			set { SetSingleRelatedEntityNavigator(value, "AppDesktop"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppDesktopItemFieldIndex
	{
		///<summary>DesktopItemId. </summary>
		DesktopItemId,
		///<summary>DesktopId. </summary>
		DesktopId,
		///<summary>WidgetItemType. </summary>
		WidgetItemType,
		///<summary>FlowOrGridLayoutSortOrder. </summary>
		FlowOrGridLayoutSortOrder,
		///<summary>StyleLayoutInfo. </summary>
		StyleLayoutInfo,
		///<summary>DomElementTag. </summary>
		DomElementTag,
		///<summary>ParameterKeyValue. </summary>
		ParameterKeyValue,
		///<summary>DisplayTitle. </summary>
		DisplayTitle,
		///<summary>RowIndex. </summary>
		RowIndex,
		///<summary>ColumnIndex. </summary>
		ColumnIndex,
		///<summary>RowSpan. </summary>
		RowSpan,
		///<summary>ColumnSpan. </summary>
		ColumnSpan,
		///<summary>GridLayoutParentId. </summary>
		GridLayoutParentId,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppDesktopItem. </summary>
	public partial class AppDesktopItemRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between AppDesktopItemEntity and AppDesktopEntity over the m:1 relation they have, using the relation between the fields: AppDesktopItem.DesktopId - AppDesktop.DesktopId</summary>
		public virtual IEntityRelation AppDesktopEntityUsingDesktopId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppDesktop", false, new[] { AppDesktopFields.DesktopId, AppDesktopItemFields.DesktopId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppDesktopItemRelations
	{
		internal static readonly IEntityRelation AppDesktopEntityUsingDesktopIdStatic = new AppDesktopItemRelations().AppDesktopEntityUsingDesktopId;

		/// <summary>CTor</summary>
		static StaticAppDesktopItemRelations() { }
	}
}
