//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:16 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppEsiteCatalogue'.<br/><br/></summary>
	[Serializable]
	public partial class AppEsiteCatalogueEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private AppEsiteEntity _appEsite;
		private AppSearchViewEntity _appSearchView;
		private AppSearchViewEntity _appSearchView_;
		private AppSearchViewEntity _appSearchView__;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppEsiteCatalogueEntityStaticMetaData _staticMetaData = new AppEsiteCatalogueEntityStaticMetaData();
		private static AppEsiteCatalogueRelations _relationsFactory = new AppEsiteCatalogueRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppEsite</summary>
			public static readonly string AppEsite = "AppEsite";
			/// <summary>Member name AppSearchView</summary>
			public static readonly string AppSearchView = "AppSearchView";
			/// <summary>Member name AppSearchView_</summary>
			public static readonly string AppSearchView_ = "AppSearchView_";
			/// <summary>Member name AppSearchView__</summary>
			public static readonly string AppSearchView__ = "AppSearchView__";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppEsiteCatalogueEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppEsiteCatalogueEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppEsiteCatalogueEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppEsiteCatalogueEntity, typeof(AppEsiteCatalogueEntity), typeof(AppEsiteCatalogueEntityFactory), false);
				AddNavigatorMetaData<AppEsiteCatalogueEntity, AppEsiteEntity>("AppEsite", "AppEsiteCatalogue", (a, b) => a._appEsite = b, a => a._appEsite, (a, b) => a.AppEsite = b, APP.LBL.RelationClasses.StaticAppEsiteCatalogueRelations.AppEsiteEntityUsingEsiteIdStatic, ()=>new AppEsiteCatalogueRelations().AppEsiteEntityUsingEsiteId, null, new int[] { (int)AppEsiteCatalogueFieldIndex.EsiteId }, null, true, (int)APP.LBL.EntityType.AppEsiteEntity);
				AddNavigatorMetaData<AppEsiteCatalogueEntity, AppSearchViewEntity>("AppSearchView", "AppEsiteCatalogue", (a, b) => a._appSearchView = b, a => a._appSearchView, (a, b) => a.AppSearchView = b, APP.LBL.RelationClasses.StaticAppEsiteCatalogueRelations.AppSearchViewEntityUsingTreeNavigationViewIdStatic, ()=>new AppEsiteCatalogueRelations().AppSearchViewEntityUsingTreeNavigationViewId, null, new int[] { (int)AppEsiteCatalogueFieldIndex.TreeNavigationViewId }, null, true, (int)APP.LBL.EntityType.AppSearchViewEntity);
				AddNavigatorMetaData<AppEsiteCatalogueEntity, AppSearchViewEntity>("AppSearchView_", "AppEsiteCatalogue_", (a, b) => a._appSearchView_ = b, a => a._appSearchView_, (a, b) => a.AppSearchView_ = b, APP.LBL.RelationClasses.StaticAppEsiteCatalogueRelations.AppSearchViewEntityUsingCatalogCardViewIdStatic, ()=>new AppEsiteCatalogueRelations().AppSearchViewEntityUsingCatalogCardViewId, null, new int[] { (int)AppEsiteCatalogueFieldIndex.CatalogCardViewId }, null, true, (int)APP.LBL.EntityType.AppSearchViewEntity);
				AddNavigatorMetaData<AppEsiteCatalogueEntity, AppSearchViewEntity>("AppSearchView__", "AppEsiteCatalogue__", (a, b) => a._appSearchView__ = b, a => a._appSearchView__, (a, b) => a.AppSearchView__ = b, APP.LBL.RelationClasses.StaticAppEsiteCatalogueRelations.AppSearchViewEntityUsingCatalogCardDetailIdStatic, ()=>new AppEsiteCatalogueRelations().AppSearchViewEntityUsingCatalogCardDetailId, null, new int[] { (int)AppEsiteCatalogueFieldIndex.CatalogCardDetailId }, null, true, (int)APP.LBL.EntityType.AppSearchViewEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppEsiteCatalogueEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppEsiteCatalogueEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppEsiteCatalogueEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppEsiteCatalogueEntity</param>
		public AppEsiteCatalogueEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="esiteCatalogueId">PK value for AppEsiteCatalogue which data should be fetched into this AppEsiteCatalogue object</param>
		public AppEsiteCatalogueEntity(System.Int32 esiteCatalogueId) : this(esiteCatalogueId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="esiteCatalogueId">PK value for AppEsiteCatalogue which data should be fetched into this AppEsiteCatalogue object</param>
		/// <param name="validator">The custom validator object for this AppEsiteCatalogueEntity</param>
		public AppEsiteCatalogueEntity(System.Int32 esiteCatalogueId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.EsiteCatalogueId = esiteCatalogueId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppEsiteCatalogueEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppEsite' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppEsite() { return CreateRelationInfoForNavigator("AppEsite"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppSearchView' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSearchView() { return CreateRelationInfoForNavigator("AppSearchView"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppSearchView' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSearchView_() { return CreateRelationInfoForNavigator("AppSearchView_"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppSearchView' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSearchView__() { return CreateRelationInfoForNavigator("AppSearchView__"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppEsiteCatalogueEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppEsiteCatalogueRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppEsite' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppEsite { get { return _staticMetaData.GetPrefetchPathElement("AppEsite", CommonEntityBase.CreateEntityCollection<AppEsiteEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSearchView' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSearchView { get { return _staticMetaData.GetPrefetchPathElement("AppSearchView", CommonEntityBase.CreateEntityCollection<AppSearchViewEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSearchView' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSearchView_ { get { return _staticMetaData.GetPrefetchPathElement("AppSearchView_", CommonEntityBase.CreateEntityCollection<AppSearchViewEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSearchView' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSearchView__ { get { return _staticMetaData.GetPrefetchPathElement("AppSearchView__", CommonEntityBase.CreateEntityCollection<AppSearchViewEntity>()); } }

		/// <summary>The EsiteCatalogueId property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."EsiteCatalogueID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 EsiteCatalogueId
		{
			get { return (System.Int32)GetValue((int)AppEsiteCatalogueFieldIndex.EsiteCatalogueId, true); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.EsiteCatalogueId, value); }
		}

		/// <summary>The EsiteId property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."EsiteID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> EsiteId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteCatalogueFieldIndex.EsiteId, false); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.EsiteId, value); }
		}

		/// <summary>The Sort property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."Sort".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Sort
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteCatalogueFieldIndex.Sort, false); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.Sort, value); }
		}

		/// <summary>The Name property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."Name".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)AppEsiteCatalogueFieldIndex.Name, true); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.Name, value); }
		}

		/// <summary>The Description property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."Description".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 1000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)AppEsiteCatalogueFieldIndex.Description, true); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.Description, value); }
		}

		/// <summary>The EmAppEstoreLayout property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."EmAppEStoreLayout".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> EmAppEstoreLayout
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteCatalogueFieldIndex.EmAppEstoreLayout, false); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.EmAppEstoreLayout, value); }
		}

		/// <summary>The EmAppEstoreTheme property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."EmAppEStoreTheme".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> EmAppEstoreTheme
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteCatalogueFieldIndex.EmAppEstoreTheme, false); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.EmAppEstoreTheme, value); }
		}

		/// <summary>The TreeNavigationViewId property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."TreeNavigationViewID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> TreeNavigationViewId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteCatalogueFieldIndex.TreeNavigationViewId, false); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.TreeNavigationViewId, value); }
		}

		/// <summary>The CatalogCardViewId property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."CatalogCardViewID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CatalogCardViewId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteCatalogueFieldIndex.CatalogCardViewId, false); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.CatalogCardViewId, value); }
		}

		/// <summary>The CatalogCardDetailId property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."CatalogCardDetailID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CatalogCardDetailId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteCatalogueFieldIndex.CatalogCardDetailId, false); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.CatalogCardDetailId, value); }
		}

		/// <summary>The SaasApplicationId property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."SaasApplicationID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> SaasApplicationId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteCatalogueFieldIndex.SaasApplicationId, false); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.SaasApplicationId, value); }
		}

		/// <summary>The IsActive property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."IsActive".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IsActive
		{
			get { return (Nullable<System.Boolean>)GetValue((int)AppEsiteCatalogueFieldIndex.IsActive, false); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.IsActive, value); }
		}

		/// <summary>The IsDefault property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."IsDefault".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IsDefault
		{
			get { return (Nullable<System.Boolean>)GetValue((int)AppEsiteCatalogueFieldIndex.IsDefault, false); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.IsDefault, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteCatalogueFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.AppCreatedByCompanyId, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteCatalogueFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppEsiteCatalogueFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppEsiteCatalogueFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppEsiteCatalogue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsiteCatalogue"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteCatalogueFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppEsiteCatalogueFieldIndex.AppModifiedById, value); }
		}

		/// <summary>Gets / sets related entity of type 'AppEsiteEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppEsiteEntity AppEsite
		{
			get { return _appEsite; }
			set { SetSingleRelatedEntityNavigator(value, "AppEsite"); }
		}

		/// <summary>Gets / sets related entity of type 'AppSearchViewEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppSearchViewEntity AppSearchView
		{
			get { return _appSearchView; }
			set { SetSingleRelatedEntityNavigator(value, "AppSearchView"); }
		}

		/// <summary>Gets / sets related entity of type 'AppSearchViewEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppSearchViewEntity AppSearchView_
		{
			get { return _appSearchView_; }
			set { SetSingleRelatedEntityNavigator(value, "AppSearchView_"); }
		}

		/// <summary>Gets / sets related entity of type 'AppSearchViewEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppSearchViewEntity AppSearchView__
		{
			get { return _appSearchView__; }
			set { SetSingleRelatedEntityNavigator(value, "AppSearchView__"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppEsiteCatalogueFieldIndex
	{
		///<summary>EsiteCatalogueId. </summary>
		EsiteCatalogueId,
		///<summary>EsiteId. </summary>
		EsiteId,
		///<summary>Sort. </summary>
		Sort,
		///<summary>Name. </summary>
		Name,
		///<summary>Description. </summary>
		Description,
		///<summary>EmAppEstoreLayout. </summary>
		EmAppEstoreLayout,
		///<summary>EmAppEstoreTheme. </summary>
		EmAppEstoreTheme,
		///<summary>TreeNavigationViewId. </summary>
		TreeNavigationViewId,
		///<summary>CatalogCardViewId. </summary>
		CatalogCardViewId,
		///<summary>CatalogCardDetailId. </summary>
		CatalogCardDetailId,
		///<summary>SaasApplicationId. </summary>
		SaasApplicationId,
		///<summary>IsActive. </summary>
		IsActive,
		///<summary>IsDefault. </summary>
		IsDefault,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppEsiteCatalogue. </summary>
	public partial class AppEsiteCatalogueRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between AppEsiteCatalogueEntity and AppEsiteEntity over the m:1 relation they have, using the relation between the fields: AppEsiteCatalogue.EsiteId - AppEsite.EsiteId</summary>
		public virtual IEntityRelation AppEsiteEntityUsingEsiteId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppEsite", false, new[] { AppEsiteFields.EsiteId, AppEsiteCatalogueFields.EsiteId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppEsiteCatalogueEntity and AppSearchViewEntity over the m:1 relation they have, using the relation between the fields: AppEsiteCatalogue.TreeNavigationViewId - AppSearchView.SearchViewId</summary>
		public virtual IEntityRelation AppSearchViewEntityUsingTreeNavigationViewId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppSearchView", false, new[] { AppSearchViewFields.SearchViewId, AppEsiteCatalogueFields.TreeNavigationViewId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppEsiteCatalogueEntity and AppSearchViewEntity over the m:1 relation they have, using the relation between the fields: AppEsiteCatalogue.CatalogCardViewId - AppSearchView.SearchViewId</summary>
		public virtual IEntityRelation AppSearchViewEntityUsingCatalogCardViewId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppSearchView_", false, new[] { AppSearchViewFields.SearchViewId, AppEsiteCatalogueFields.CatalogCardViewId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppEsiteCatalogueEntity and AppSearchViewEntity over the m:1 relation they have, using the relation between the fields: AppEsiteCatalogue.CatalogCardDetailId - AppSearchView.SearchViewId</summary>
		public virtual IEntityRelation AppSearchViewEntityUsingCatalogCardDetailId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppSearchView__", false, new[] { AppSearchViewFields.SearchViewId, AppEsiteCatalogueFields.CatalogCardDetailId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppEsiteCatalogueRelations
	{
		internal static readonly IEntityRelation AppEsiteEntityUsingEsiteIdStatic = new AppEsiteCatalogueRelations().AppEsiteEntityUsingEsiteId;
		internal static readonly IEntityRelation AppSearchViewEntityUsingTreeNavigationViewIdStatic = new AppEsiteCatalogueRelations().AppSearchViewEntityUsingTreeNavigationViewId;
		internal static readonly IEntityRelation AppSearchViewEntityUsingCatalogCardViewIdStatic = new AppEsiteCatalogueRelations().AppSearchViewEntityUsingCatalogCardViewId;
		internal static readonly IEntityRelation AppSearchViewEntityUsingCatalogCardDetailIdStatic = new AppEsiteCatalogueRelations().AppSearchViewEntityUsingCatalogCardDetailId;

		/// <summary>CTor</summary>
		static StaticAppEsiteCatalogueRelations() { }
	}
}
