//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:16 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppEsite'.<br/><br/></summary>
	[Serializable]
	public partial class AppEsiteEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<AppEsiteCatalogueEntity> _appEsiteCatalogue;
		private EntityCollection<AppEsitePagesEntity> _appEsitePages;
		private AppListMenuEntity _appListMenu;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppEsiteEntityStaticMetaData _staticMetaData = new AppEsiteEntityStaticMetaData();
		private static AppEsiteRelations _relationsFactory = new AppEsiteRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppListMenu</summary>
			public static readonly string AppListMenu = "AppListMenu";
			/// <summary>Member name AppEsiteCatalogue</summary>
			public static readonly string AppEsiteCatalogue = "AppEsiteCatalogue";
			/// <summary>Member name AppEsitePages</summary>
			public static readonly string AppEsitePages = "AppEsitePages";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppEsiteEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppEsiteEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppEsiteEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppEsiteEntity, typeof(AppEsiteEntity), typeof(AppEsiteEntityFactory), false);
				AddNavigatorMetaData<AppEsiteEntity, EntityCollection<AppEsiteCatalogueEntity>>("AppEsiteCatalogue", a => a._appEsiteCatalogue, (a, b) => a._appEsiteCatalogue = b, a => a.AppEsiteCatalogue, () => new AppEsiteRelations().AppEsiteCatalogueEntityUsingEsiteId, typeof(AppEsiteCatalogueEntity), (int)APP.LBL.EntityType.AppEsiteCatalogueEntity);
				AddNavigatorMetaData<AppEsiteEntity, EntityCollection<AppEsitePagesEntity>>("AppEsitePages", a => a._appEsitePages, (a, b) => a._appEsitePages = b, a => a.AppEsitePages, () => new AppEsiteRelations().AppEsitePagesEntityUsingEsiteId, typeof(AppEsitePagesEntity), (int)APP.LBL.EntityType.AppEsitePagesEntity);
				AddNavigatorMetaData<AppEsiteEntity, AppListMenuEntity>("AppListMenu", "AppEsite", (a, b) => a._appListMenu = b, a => a._appListMenu, (a, b) => a.AppListMenu = b, APP.LBL.RelationClasses.StaticAppEsiteRelations.AppListMenuEntityUsingSaasApplicationIdStatic, ()=>new AppEsiteRelations().AppListMenuEntityUsingSaasApplicationId, null, new int[] { (int)AppEsiteFieldIndex.SaasApplicationId }, null, true, (int)APP.LBL.EntityType.AppListMenuEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppEsiteEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppEsiteEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppEsiteEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppEsiteEntity</param>
		public AppEsiteEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="esiteId">PK value for AppEsite which data should be fetched into this AppEsite object</param>
		public AppEsiteEntity(System.Int32 esiteId) : this(esiteId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="esiteId">PK value for AppEsite which data should be fetched into this AppEsite object</param>
		/// <param name="validator">The custom validator object for this AppEsiteEntity</param>
		public AppEsiteEntity(System.Int32 esiteId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.EsiteId = esiteId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppEsiteEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppEsiteCatalogue' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppEsiteCatalogue() { return CreateRelationInfoForNavigator("AppEsiteCatalogue"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppEsitePages' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppEsitePages() { return CreateRelationInfoForNavigator("AppEsitePages"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppListMenu' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppListMenu() { return CreateRelationInfoForNavigator("AppListMenu"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppEsiteEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppEsiteRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppEsiteCatalogue' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppEsiteCatalogue { get { return _staticMetaData.GetPrefetchPathElement("AppEsiteCatalogue", CommonEntityBase.CreateEntityCollection<AppEsiteCatalogueEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppEsitePages' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppEsitePages { get { return _staticMetaData.GetPrefetchPathElement("AppEsitePages", CommonEntityBase.CreateEntityCollection<AppEsitePagesEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppListMenu' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppListMenu { get { return _staticMetaData.GetPrefetchPathElement("AppListMenu", CommonEntityBase.CreateEntityCollection<AppListMenuEntity>()); } }

		/// <summary>The EsiteId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."EsiteID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 EsiteId
		{
			get { return (System.Int32)GetValue((int)AppEsiteFieldIndex.EsiteId, true); }
			set { SetValue((int)AppEsiteFieldIndex.EsiteId, value); }
		}

		/// <summary>The Sort property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."Sort".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Sort
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.Sort, false); }
			set { SetValue((int)AppEsiteFieldIndex.Sort, value); }
		}

		/// <summary>The Name property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."Name".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.Name, true); }
			set { SetValue((int)AppEsiteFieldIndex.Name, value); }
		}

		/// <summary>The Description property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."Description".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.Description, true); }
			set { SetValue((int)AppEsiteFieldIndex.Description, value); }
		}

		/// <summary>The EmAppEsiteTheme property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."EmAppEsiteTheme".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> EmAppEsiteTheme
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.EmAppEsiteTheme, false); }
			set { SetValue((int)AppEsiteFieldIndex.EmAppEsiteTheme, value); }
		}

		/// <summary>The LogoImageId1 property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."LogoImageID1".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> LogoImageId1
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.LogoImageId1, false); }
			set { SetValue((int)AppEsiteFieldIndex.LogoImageId1, value); }
		}

		/// <summary>The LogoImageId2 property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."LogoImageID2".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> LogoImageId2
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.LogoImageId2, false); }
			set { SetValue((int)AppEsiteFieldIndex.LogoImageId2, value); }
		}

		/// <summary>The IsAllowGuestCheckout property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."IsAllowGuestCheckout".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IsAllowGuestCheckout
		{
			get { return (Nullable<System.Boolean>)GetValue((int)AppEsiteFieldIndex.IsAllowGuestCheckout, false); }
			set { SetValue((int)AppEsiteFieldIndex.IsAllowGuestCheckout, value); }
		}

		/// <summary>The MyOrderListSearchId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."MyOrderListSearchID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> MyOrderListSearchId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.MyOrderListSearchId, false); }
			set { SetValue((int)AppEsiteFieldIndex.MyOrderListSearchId, value); }
		}

		/// <summary>The CustomerInfoDataModelId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."CustomerInfoDataModelID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CustomerInfoDataModelId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.CustomerInfoDataModelId, false); }
			set { SetValue((int)AppEsiteFieldIndex.CustomerInfoDataModelId, value); }
		}

		/// <summary>The CustomerInfoDbtableName property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."CustomerInfoDBTableName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String CustomerInfoDbtableName
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.CustomerInfoDbtableName, true); }
			set { SetValue((int)AppEsiteFieldIndex.CustomerInfoDbtableName, value); }
		}

		/// <summary>The CustomerInfoCustomerIdDbfieldName property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."CustomerInfoCustomerIdDBFieldName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String CustomerInfoCustomerIdDbfieldName
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.CustomerInfoCustomerIdDbfieldName, true); }
			set { SetValue((int)AppEsiteFieldIndex.CustomerInfoCustomerIdDbfieldName, value); }
		}

		/// <summary>The CustomerInfoEmailDbfieldName property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."CustomerInfoEmailDBFieldName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String CustomerInfoEmailDbfieldName
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.CustomerInfoEmailDbfieldName, true); }
			set { SetValue((int)AppEsiteFieldIndex.CustomerInfoEmailDbfieldName, value); }
		}

		/// <summary>The CustomerInfoDataTransferId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."CustomerInfoDataTransferID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CustomerInfoDataTransferId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.CustomerInfoDataTransferId, false); }
			set { SetValue((int)AppEsiteFieldIndex.CustomerInfoDataTransferId, value); }
		}

		/// <summary>The SaveCustomerInfoPostActionId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."SaveCustomerInfoPostActionID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> SaveCustomerInfoPostActionId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.SaveCustomerInfoPostActionId, false); }
			set { SetValue((int)AppEsiteFieldIndex.SaveCustomerInfoPostActionId, value); }
		}

		/// <summary>The CustomerShippingAddressSearchId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."CustomerShippingAddressSearchID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CustomerShippingAddressSearchId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.CustomerShippingAddressSearchId, false); }
			set { SetValue((int)AppEsiteFieldIndex.CustomerShippingAddressSearchId, value); }
		}

		/// <summary>The CustomerShippingAddressDataModelId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."CustomerShippingAddressDataModelID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CustomerShippingAddressDataModelId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.CustomerShippingAddressDataModelId, false); }
			set { SetValue((int)AppEsiteFieldIndex.CustomerShippingAddressDataModelId, value); }
		}

		/// <summary>The CustomerShippingAddressDataTransferId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."CustomerShippingAddressDataTransferID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CustomerShippingAddressDataTransferId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.CustomerShippingAddressDataTransferId, false); }
			set { SetValue((int)AppEsiteFieldIndex.CustomerShippingAddressDataTransferId, value); }
		}

		/// <summary>The SaveCustomerShippingAddressPostActionId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."SaveCustomerShippingAddressPostActionID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> SaveCustomerShippingAddressPostActionId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.SaveCustomerShippingAddressPostActionId, false); }
			set { SetValue((int)AppEsiteFieldIndex.SaveCustomerShippingAddressPostActionId, value); }
		}

		/// <summary>The CustomerOrderListSearchId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."CustomerOrderListSearchID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CustomerOrderListSearchId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.CustomerOrderListSearchId, false); }
			set { SetValue((int)AppEsiteFieldIndex.CustomerOrderListSearchId, value); }
		}

		/// <summary>The OrderDataModelId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."OrderDataModelID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> OrderDataModelId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.OrderDataModelId, false); }
			set { SetValue((int)AppEsiteFieldIndex.OrderDataModelId, value); }
		}

		/// <summary>The InvoiceDataModelId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."InvoiceDataModelId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> InvoiceDataModelId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.InvoiceDataModelId, false); }
			set { SetValue((int)AppEsiteFieldIndex.InvoiceDataModelId, value); }
		}

		/// <summary>The InvoiceReportId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."InvoiceReportId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> InvoiceReportId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.InvoiceReportId, false); }
			set { SetValue((int)AppEsiteFieldIndex.InvoiceReportId, value); }
		}

		/// <summary>The OrderDataTransferId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."OrderDataTransferID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> OrderDataTransferId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.OrderDataTransferId, false); }
			set { SetValue((int)AppEsiteFieldIndex.OrderDataTransferId, value); }
		}

		/// <summary>The SaveOrderPostActionId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."SaveOrderPostActionID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> SaveOrderPostActionId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.SaveOrderPostActionId, false); }
			set { SetValue((int)AppEsiteFieldIndex.SaveOrderPostActionId, value); }
		}

		/// <summary>The CustomerPaymentHistorySearchId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."CustomerPaymentHistorySearchID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CustomerPaymentHistorySearchId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.CustomerPaymentHistorySearchId, false); }
			set { SetValue((int)AppEsiteFieldIndex.CustomerPaymentHistorySearchId, value); }
		}

		/// <summary>The CustomerPaymentHistoryDataModelId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."CustomerPaymentHistoryDataModelID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CustomerPaymentHistoryDataModelId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.CustomerPaymentHistoryDataModelId, false); }
			set { SetValue((int)AppEsiteFieldIndex.CustomerPaymentHistoryDataModelId, value); }
		}

		/// <summary>The CustomerPaymentHistoryDataTransferId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."CustomerPaymentHistoryDataTransferID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CustomerPaymentHistoryDataTransferId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.CustomerPaymentHistoryDataTransferId, false); }
			set { SetValue((int)AppEsiteFieldIndex.CustomerPaymentHistoryDataTransferId, value); }
		}

		/// <summary>The PaymentSuccessfulPostActionActionId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."PaymentSuccessfulPostActionActionID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> PaymentSuccessfulPostActionActionId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.PaymentSuccessfulPostActionActionId, false); }
			set { SetValue((int)AppEsiteFieldIndex.PaymentSuccessfulPostActionActionId, value); }
		}

		/// <summary>The PaymentFailedPostActionActionId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."PaymentFailedPostActionActionID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> PaymentFailedPostActionActionId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.PaymentFailedPostActionActionId, false); }
			set { SetValue((int)AppEsiteFieldIndex.PaymentFailedPostActionActionId, value); }
		}

		/// <summary>The EnablePaypalPayment property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."EnablePaypalPayment".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> EnablePaypalPayment
		{
			get { return (Nullable<System.Boolean>)GetValue((int)AppEsiteFieldIndex.EnablePaypalPayment, false); }
			set { SetValue((int)AppEsiteFieldIndex.EnablePaypalPayment, value); }
		}

		/// <summary>The PaypalPaymentApiBaseUrl property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."PaypalPayment_ApiBaseURL".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String PaypalPaymentApiBaseUrl
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.PaypalPaymentApiBaseUrl, true); }
			set { SetValue((int)AppEsiteFieldIndex.PaypalPaymentApiBaseUrl, value); }
		}

		/// <summary>The PaypalPaymentSbClientId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."PaypalPayment_SB_CLIENT_ID".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String PaypalPaymentSbClientId
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.PaypalPaymentSbClientId, true); }
			set { SetValue((int)AppEsiteFieldIndex.PaypalPaymentSbClientId, value); }
		}

		/// <summary>The PaypalPaymentDefaultCurrencyCode property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."PaypalPayment_DefaultCurrencyCode".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String PaypalPaymentDefaultCurrencyCode
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.PaypalPaymentDefaultCurrencyCode, true); }
			set { SetValue((int)AppEsiteFieldIndex.PaypalPaymentDefaultCurrencyCode, value); }
		}

		/// <summary>The EnableVisaPayment property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."EnableVisaPayment".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> EnableVisaPayment
		{
			get { return (Nullable<System.Boolean>)GetValue((int)AppEsiteFieldIndex.EnableVisaPayment, false); }
			set { SetValue((int)AppEsiteFieldIndex.EnableVisaPayment, value); }
		}

		/// <summary>The VisaPaymentApiBaseUrl property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."VisaPayment_ApiBaseURL".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String VisaPaymentApiBaseUrl
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.VisaPaymentApiBaseUrl, true); }
			set { SetValue((int)AppEsiteFieldIndex.VisaPaymentApiBaseUrl, value); }
		}

		/// <summary>The VisaPaymentApiParam1 property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."VisaPayment_ApiParam1".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String VisaPaymentApiParam1
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.VisaPaymentApiParam1, true); }
			set { SetValue((int)AppEsiteFieldIndex.VisaPaymentApiParam1, value); }
		}

		/// <summary>The VisaPaymentApiParam2 property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."VisaPayment_ApiParam2".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String VisaPaymentApiParam2
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.VisaPaymentApiParam2, true); }
			set { SetValue((int)AppEsiteFieldIndex.VisaPaymentApiParam2, value); }
		}

		/// <summary>The VisaPaymentApiParam3 property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."VisaPayment_ApiParam3".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String VisaPaymentApiParam3
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.VisaPaymentApiParam3, true); }
			set { SetValue((int)AppEsiteFieldIndex.VisaPaymentApiParam3, value); }
		}

		/// <summary>The VisaPaymentApiParam4 property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."VisaPayment_ApiParam4".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String VisaPaymentApiParam4
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.VisaPaymentApiParam4, true); }
			set { SetValue((int)AppEsiteFieldIndex.VisaPaymentApiParam4, value); }
		}

		/// <summary>The VisaPaymentApiParam5 property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."VisaPayment_ApiParam5".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String VisaPaymentApiParam5
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.VisaPaymentApiParam5, true); }
			set { SetValue((int)AppEsiteFieldIndex.VisaPaymentApiParam5, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppEsiteFieldIndex.AppCreatedByCompanyId, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppEsiteFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppEsiteFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppEsiteFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppEsiteFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppEsiteFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppEsiteFieldIndex.AppModifiedById, value); }
		}

		/// <summary>The MasteSiteHostLayoutHtmlContent property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."MasteSiteHostLayoutHtmlContent".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String MasteSiteHostLayoutHtmlContent
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.MasteSiteHostLayoutHtmlContent, true); }
			set { SetValue((int)AppEsiteFieldIndex.MasteSiteHostLayoutHtmlContent, value); }
		}

		/// <summary>The MasteSiteCustNavigationJavaScripControl property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."MasteSiteCustNavigationJavaScripControl".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String MasteSiteCustNavigationJavaScripControl
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.MasteSiteCustNavigationJavaScripControl, true); }
			set { SetValue((int)AppEsiteFieldIndex.MasteSiteCustNavigationJavaScripControl, value); }
		}

		/// <summary>The EmApplicationType property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."EmApplicationType".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> EmApplicationType
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.EmApplicationType, false); }
			set { SetValue((int)AppEsiteFieldIndex.EmApplicationType, value); }
		}

		/// <summary>The SaasApplicationId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."SaasApplicationID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> SaasApplicationId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.SaasApplicationId, false); }
			set { SetValue((int)AppEsiteFieldIndex.SaasApplicationId, value); }
		}

		/// <summary>The SupplierInfoDataModelId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."SupplierInfoDataModelID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> SupplierInfoDataModelId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppEsiteFieldIndex.SupplierInfoDataModelId, false); }
			set { SetValue((int)AppEsiteFieldIndex.SupplierInfoDataModelId, value); }
		}

		/// <summary>The SupplierInfoDbtableName property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."SupplierInfoDBTableName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String SupplierInfoDbtableName
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.SupplierInfoDbtableName, true); }
			set { SetValue((int)AppEsiteFieldIndex.SupplierInfoDbtableName, value); }
		}

		/// <summary>The SupplierInfoIdDbfieldName property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."SupplierInfoIdDBFieldName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String SupplierInfoIdDbfieldName
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.SupplierInfoIdDbfieldName, true); }
			set { SetValue((int)AppEsiteFieldIndex.SupplierInfoIdDbfieldName, value); }
		}

		/// <summary>The SupplierInfoEmailDbfieldName property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."SupplierInfoEmailDBFieldName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String SupplierInfoEmailDbfieldName
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.SupplierInfoEmailDbfieldName, true); }
			set { SetValue((int)AppEsiteFieldIndex.SupplierInfoEmailDbfieldName, value); }
		}

		/// <summary>The SupplierInfoDataTransferId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."SupplierInfoDataTransferID".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String SupplierInfoDataTransferId
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.SupplierInfoDataTransferId, true); }
			set { SetValue((int)AppEsiteFieldIndex.SupplierInfoDataTransferId, value); }
		}

		/// <summary>The SaveSupplierInfoPostActionId property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."SaveSupplierInfoPostActionID".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String SaveSupplierInfoPostActionId
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.SaveSupplierInfoPostActionId, true); }
			set { SetValue((int)AppEsiteFieldIndex.SaveSupplierInfoPostActionId, value); }
		}

		/// <summary>The SitePublishedBaseUrl property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."SitePublishedBaseUrl".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String SitePublishedBaseUrl
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.SitePublishedBaseUrl, true); }
			set { SetValue((int)AppEsiteFieldIndex.SitePublishedBaseUrl, value); }
		}

		/// <summary>The SitePublishedLoginUrl property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."SitePublishedLoginUrl".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String SitePublishedLoginUrl
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.SitePublishedLoginUrl, true); }
			set { SetValue((int)AppEsiteFieldIndex.SitePublishedLoginUrl, value); }
		}

		/// <summary>The StartPage property of the Entity AppEsite<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppEsite"."StartPage".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String StartPage
		{
			get { return (System.String)GetValue((int)AppEsiteFieldIndex.StartPage, true); }
			set { SetValue((int)AppEsiteFieldIndex.StartPage, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'AppEsiteCatalogueEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppEsiteCatalogueEntity))]
		public virtual EntityCollection<AppEsiteCatalogueEntity> AppEsiteCatalogue { get { return GetOrCreateEntityCollection<AppEsiteCatalogueEntity, AppEsiteCatalogueEntityFactory>("AppEsite", true, false, ref _appEsiteCatalogue); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppEsitePagesEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppEsitePagesEntity))]
		public virtual EntityCollection<AppEsitePagesEntity> AppEsitePages { get { return GetOrCreateEntityCollection<AppEsitePagesEntity, AppEsitePagesEntityFactory>("AppEsite_", true, false, ref _appEsitePages); } }

		/// <summary>Gets / sets related entity of type 'AppListMenuEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppListMenuEntity AppListMenu
		{
			get { return _appListMenu; }
			set { SetSingleRelatedEntityNavigator(value, "AppListMenu"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppEsiteFieldIndex
	{
		///<summary>EsiteId. </summary>
		EsiteId,
		///<summary>Sort. </summary>
		Sort,
		///<summary>Name. </summary>
		Name,
		///<summary>Description. </summary>
		Description,
		///<summary>EmAppEsiteTheme. </summary>
		EmAppEsiteTheme,
		///<summary>LogoImageId1. </summary>
		LogoImageId1,
		///<summary>LogoImageId2. </summary>
		LogoImageId2,
		///<summary>IsAllowGuestCheckout. </summary>
		IsAllowGuestCheckout,
		///<summary>MyOrderListSearchId. </summary>
		MyOrderListSearchId,
		///<summary>CustomerInfoDataModelId. </summary>
		CustomerInfoDataModelId,
		///<summary>CustomerInfoDbtableName. </summary>
		CustomerInfoDbtableName,
		///<summary>CustomerInfoCustomerIdDbfieldName. </summary>
		CustomerInfoCustomerIdDbfieldName,
		///<summary>CustomerInfoEmailDbfieldName. </summary>
		CustomerInfoEmailDbfieldName,
		///<summary>CustomerInfoDataTransferId. </summary>
		CustomerInfoDataTransferId,
		///<summary>SaveCustomerInfoPostActionId. </summary>
		SaveCustomerInfoPostActionId,
		///<summary>CustomerShippingAddressSearchId. </summary>
		CustomerShippingAddressSearchId,
		///<summary>CustomerShippingAddressDataModelId. </summary>
		CustomerShippingAddressDataModelId,
		///<summary>CustomerShippingAddressDataTransferId. </summary>
		CustomerShippingAddressDataTransferId,
		///<summary>SaveCustomerShippingAddressPostActionId. </summary>
		SaveCustomerShippingAddressPostActionId,
		///<summary>CustomerOrderListSearchId. </summary>
		CustomerOrderListSearchId,
		///<summary>OrderDataModelId. </summary>
		OrderDataModelId,
		///<summary>InvoiceDataModelId. </summary>
		InvoiceDataModelId,
		///<summary>InvoiceReportId. </summary>
		InvoiceReportId,
		///<summary>OrderDataTransferId. </summary>
		OrderDataTransferId,
		///<summary>SaveOrderPostActionId. </summary>
		SaveOrderPostActionId,
		///<summary>CustomerPaymentHistorySearchId. </summary>
		CustomerPaymentHistorySearchId,
		///<summary>CustomerPaymentHistoryDataModelId. </summary>
		CustomerPaymentHistoryDataModelId,
		///<summary>CustomerPaymentHistoryDataTransferId. </summary>
		CustomerPaymentHistoryDataTransferId,
		///<summary>PaymentSuccessfulPostActionActionId. </summary>
		PaymentSuccessfulPostActionActionId,
		///<summary>PaymentFailedPostActionActionId. </summary>
		PaymentFailedPostActionActionId,
		///<summary>EnablePaypalPayment. </summary>
		EnablePaypalPayment,
		///<summary>PaypalPaymentApiBaseUrl. </summary>
		PaypalPaymentApiBaseUrl,
		///<summary>PaypalPaymentSbClientId. </summary>
		PaypalPaymentSbClientId,
		///<summary>PaypalPaymentDefaultCurrencyCode. </summary>
		PaypalPaymentDefaultCurrencyCode,
		///<summary>EnableVisaPayment. </summary>
		EnableVisaPayment,
		///<summary>VisaPaymentApiBaseUrl. </summary>
		VisaPaymentApiBaseUrl,
		///<summary>VisaPaymentApiParam1. </summary>
		VisaPaymentApiParam1,
		///<summary>VisaPaymentApiParam2. </summary>
		VisaPaymentApiParam2,
		///<summary>VisaPaymentApiParam3. </summary>
		VisaPaymentApiParam3,
		///<summary>VisaPaymentApiParam4. </summary>
		VisaPaymentApiParam4,
		///<summary>VisaPaymentApiParam5. </summary>
		VisaPaymentApiParam5,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		///<summary>MasteSiteHostLayoutHtmlContent. </summary>
		MasteSiteHostLayoutHtmlContent,
		///<summary>MasteSiteCustNavigationJavaScripControl. </summary>
		MasteSiteCustNavigationJavaScripControl,
		///<summary>EmApplicationType. </summary>
		EmApplicationType,
		///<summary>SaasApplicationId. </summary>
		SaasApplicationId,
		///<summary>SupplierInfoDataModelId. </summary>
		SupplierInfoDataModelId,
		///<summary>SupplierInfoDbtableName. </summary>
		SupplierInfoDbtableName,
		///<summary>SupplierInfoIdDbfieldName. </summary>
		SupplierInfoIdDbfieldName,
		///<summary>SupplierInfoEmailDbfieldName. </summary>
		SupplierInfoEmailDbfieldName,
		///<summary>SupplierInfoDataTransferId. </summary>
		SupplierInfoDataTransferId,
		///<summary>SaveSupplierInfoPostActionId. </summary>
		SaveSupplierInfoPostActionId,
		///<summary>SitePublishedBaseUrl. </summary>
		SitePublishedBaseUrl,
		///<summary>SitePublishedLoginUrl. </summary>
		SitePublishedLoginUrl,
		///<summary>StartPage. </summary>
		StartPage,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppEsite. </summary>
	public partial class AppEsiteRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between AppEsiteEntity and AppEsiteCatalogueEntity over the 1:n relation they have, using the relation between the fields: AppEsite.EsiteId - AppEsiteCatalogue.EsiteId</summary>
		public virtual IEntityRelation AppEsiteCatalogueEntityUsingEsiteId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppEsiteCatalogue", true, new[] { AppEsiteFields.EsiteId, AppEsiteCatalogueFields.EsiteId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppEsiteEntity and AppEsitePagesEntity over the 1:n relation they have, using the relation between the fields: AppEsite.EsiteId - AppEsitePages.EsiteId</summary>
		public virtual IEntityRelation AppEsitePagesEntityUsingEsiteId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppEsitePages", true, new[] { AppEsiteFields.EsiteId, AppEsitePagesFields.EsiteId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppEsiteEntity and AppListMenuEntity over the m:1 relation they have, using the relation between the fields: AppEsite.SaasApplicationId - AppListMenu.MenuId</summary>
		public virtual IEntityRelation AppListMenuEntityUsingSaasApplicationId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppListMenu", false, new[] { AppListMenuFields.MenuId, AppEsiteFields.SaasApplicationId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppEsiteRelations
	{
		internal static readonly IEntityRelation AppEsiteCatalogueEntityUsingEsiteIdStatic = new AppEsiteRelations().AppEsiteCatalogueEntityUsingEsiteId;
		internal static readonly IEntityRelation AppEsitePagesEntityUsingEsiteIdStatic = new AppEsiteRelations().AppEsitePagesEntityUsingEsiteId;
		internal static readonly IEntityRelation AppListMenuEntityUsingSaasApplicationIdStatic = new AppEsiteRelations().AppListMenuEntityUsingSaasApplicationId;

		/// <summary>CTor</summary>
		static StaticAppEsiteRelations() { }
	}
}
