//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:17 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppListMenu'.<br/><br/></summary>
	[Serializable]
	public partial class AppListMenuEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<AppApplicationAssetsItemEntity> _appApplicationAssetsItem;
		private EntityCollection<AppDataSetEntity> _appDataSet;
		private EntityCollection<AppDesktopEntity> _appDesktop;
		private EntityCollection<AppEntityInfoEntity> _appEntityInfo;
		private EntityCollection<AppEsiteEntity> _appEsite;
		private EntityCollection<AppFormEntity> _appForm;
		private EntityCollection<AppListMenuEntity> _appListMenu_;
		private EntityCollection<AppProjectOrWorkFlowEntity> _appProjectOrWorkFlow;
		private EntityCollection<AppReportEntity> _appReport;
		private EntityCollection<AppSearchEntity> _appSearch;
		private EntityCollection<AppSecurityRegDomainListMenuEntity> _appSecurityRegDomainListMenu;
		private EntityCollection<AppSecurityUserListMenuEntity> _appSecurityUserListMenu;
		private EntityCollection<AppSysLabelLanguageEntity> _appSysLabelLanguage;
		private EntityCollection<AppTransactionEntity> _appTransaction;
		private EntityCollection<AppVersionEditionModuleEntity> _appVersionEditionModule;
		private AppCompanyEntity _appCompany;
		private AppListMenuEntity _appListMenu;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppListMenuEntityStaticMetaData _staticMetaData = new AppListMenuEntityStaticMetaData();
		private static AppListMenuRelations _relationsFactory = new AppListMenuRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppCompany</summary>
			public static readonly string AppCompany = "AppCompany";
			/// <summary>Member name AppListMenu</summary>
			public static readonly string AppListMenu = "AppListMenu";
			/// <summary>Member name AppApplicationAssetsItem</summary>
			public static readonly string AppApplicationAssetsItem = "AppApplicationAssetsItem";
			/// <summary>Member name AppDataSet</summary>
			public static readonly string AppDataSet = "AppDataSet";
			/// <summary>Member name AppDesktop</summary>
			public static readonly string AppDesktop = "AppDesktop";
			/// <summary>Member name AppEntityInfo</summary>
			public static readonly string AppEntityInfo = "AppEntityInfo";
			/// <summary>Member name AppEsite</summary>
			public static readonly string AppEsite = "AppEsite";
			/// <summary>Member name AppForm</summary>
			public static readonly string AppForm = "AppForm";
			/// <summary>Member name AppListMenu_</summary>
			public static readonly string AppListMenu_ = "AppListMenu_";
			/// <summary>Member name AppProjectOrWorkFlow</summary>
			public static readonly string AppProjectOrWorkFlow = "AppProjectOrWorkFlow";
			/// <summary>Member name AppReport</summary>
			public static readonly string AppReport = "AppReport";
			/// <summary>Member name AppSearch</summary>
			public static readonly string AppSearch = "AppSearch";
			/// <summary>Member name AppSecurityRegDomainListMenu</summary>
			public static readonly string AppSecurityRegDomainListMenu = "AppSecurityRegDomainListMenu";
			/// <summary>Member name AppSecurityUserListMenu</summary>
			public static readonly string AppSecurityUserListMenu = "AppSecurityUserListMenu";
			/// <summary>Member name AppSysLabelLanguage</summary>
			public static readonly string AppSysLabelLanguage = "AppSysLabelLanguage";
			/// <summary>Member name AppTransaction</summary>
			public static readonly string AppTransaction = "AppTransaction";
			/// <summary>Member name AppVersionEditionModule</summary>
			public static readonly string AppVersionEditionModule = "AppVersionEditionModule";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppListMenuEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppListMenuEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppListMenuEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppListMenuEntity, typeof(AppListMenuEntity), typeof(AppListMenuEntityFactory), false);
				AddNavigatorMetaData<AppListMenuEntity, EntityCollection<AppApplicationAssetsItemEntity>>("AppApplicationAssetsItem", a => a._appApplicationAssetsItem, (a, b) => a._appApplicationAssetsItem = b, a => a.AppApplicationAssetsItem, () => new AppListMenuRelations().AppApplicationAssetsItemEntityUsingApplicationId, typeof(AppApplicationAssetsItemEntity), (int)APP.LBL.EntityType.AppApplicationAssetsItemEntity);
				AddNavigatorMetaData<AppListMenuEntity, EntityCollection<AppDataSetEntity>>("AppDataSet", a => a._appDataSet, (a, b) => a._appDataSet = b, a => a.AppDataSet, () => new AppListMenuRelations().AppDataSetEntityUsingSaasApplicationId, typeof(AppDataSetEntity), (int)APP.LBL.EntityType.AppDataSetEntity);
				AddNavigatorMetaData<AppListMenuEntity, EntityCollection<AppDesktopEntity>>("AppDesktop", a => a._appDesktop, (a, b) => a._appDesktop = b, a => a.AppDesktop, () => new AppListMenuRelations().AppDesktopEntityUsingSaasApplicationId, typeof(AppDesktopEntity), (int)APP.LBL.EntityType.AppDesktopEntity);
				AddNavigatorMetaData<AppListMenuEntity, EntityCollection<AppEntityInfoEntity>>("AppEntityInfo", a => a._appEntityInfo, (a, b) => a._appEntityInfo = b, a => a.AppEntityInfo, () => new AppListMenuRelations().AppEntityInfoEntityUsingSaasApplicationId, typeof(AppEntityInfoEntity), (int)APP.LBL.EntityType.AppEntityInfoEntity);
				AddNavigatorMetaData<AppListMenuEntity, EntityCollection<AppEsiteEntity>>("AppEsite", a => a._appEsite, (a, b) => a._appEsite = b, a => a.AppEsite, () => new AppListMenuRelations().AppEsiteEntityUsingSaasApplicationId, typeof(AppEsiteEntity), (int)APP.LBL.EntityType.AppEsiteEntity);
				AddNavigatorMetaData<AppListMenuEntity, EntityCollection<AppFormEntity>>("AppForm", a => a._appForm, (a, b) => a._appForm = b, a => a.AppForm, () => new AppListMenuRelations().AppFormEntityUsingSaasApplicationId, typeof(AppFormEntity), (int)APP.LBL.EntityType.AppFormEntity);
				AddNavigatorMetaData<AppListMenuEntity, EntityCollection<AppListMenuEntity>>("AppListMenu_", a => a._appListMenu_, (a, b) => a._appListMenu_ = b, a => a.AppListMenu_, () => new AppListMenuRelations().AppListMenuEntityUsingParentId, typeof(AppListMenuEntity), (int)APP.LBL.EntityType.AppListMenuEntity);
				AddNavigatorMetaData<AppListMenuEntity, EntityCollection<AppProjectOrWorkFlowEntity>>("AppProjectOrWorkFlow", a => a._appProjectOrWorkFlow, (a, b) => a._appProjectOrWorkFlow = b, a => a.AppProjectOrWorkFlow, () => new AppListMenuRelations().AppProjectOrWorkFlowEntityUsingSaasApplicationId, typeof(AppProjectOrWorkFlowEntity), (int)APP.LBL.EntityType.AppProjectOrWorkFlowEntity);
				AddNavigatorMetaData<AppListMenuEntity, EntityCollection<AppReportEntity>>("AppReport", a => a._appReport, (a, b) => a._appReport = b, a => a.AppReport, () => new AppListMenuRelations().AppReportEntityUsingSaasApplicationId, typeof(AppReportEntity), (int)APP.LBL.EntityType.AppReportEntity);
				AddNavigatorMetaData<AppListMenuEntity, EntityCollection<AppSearchEntity>>("AppSearch", a => a._appSearch, (a, b) => a._appSearch = b, a => a.AppSearch, () => new AppListMenuRelations().AppSearchEntityUsingSaasApplicationId, typeof(AppSearchEntity), (int)APP.LBL.EntityType.AppSearchEntity);
				AddNavigatorMetaData<AppListMenuEntity, EntityCollection<AppSecurityRegDomainListMenuEntity>>("AppSecurityRegDomainListMenu", a => a._appSecurityRegDomainListMenu, (a, b) => a._appSecurityRegDomainListMenu = b, a => a.AppSecurityRegDomainListMenu, () => new AppListMenuRelations().AppSecurityRegDomainListMenuEntityUsingMenuId, typeof(AppSecurityRegDomainListMenuEntity), (int)APP.LBL.EntityType.AppSecurityRegDomainListMenuEntity);
				AddNavigatorMetaData<AppListMenuEntity, EntityCollection<AppSecurityUserListMenuEntity>>("AppSecurityUserListMenu", a => a._appSecurityUserListMenu, (a, b) => a._appSecurityUserListMenu = b, a => a.AppSecurityUserListMenu, () => new AppListMenuRelations().AppSecurityUserListMenuEntityUsingMenuId, typeof(AppSecurityUserListMenuEntity), (int)APP.LBL.EntityType.AppSecurityUserListMenuEntity);
				AddNavigatorMetaData<AppListMenuEntity, EntityCollection<AppSysLabelLanguageEntity>>("AppSysLabelLanguage", a => a._appSysLabelLanguage, (a, b) => a._appSysLabelLanguage = b, a => a.AppSysLabelLanguage, () => new AppListMenuRelations().AppSysLabelLanguageEntityUsingMenuId, typeof(AppSysLabelLanguageEntity), (int)APP.LBL.EntityType.AppSysLabelLanguageEntity);
				AddNavigatorMetaData<AppListMenuEntity, EntityCollection<AppTransactionEntity>>("AppTransaction", a => a._appTransaction, (a, b) => a._appTransaction = b, a => a.AppTransaction, () => new AppListMenuRelations().AppTransactionEntityUsingSaasApplicationId, typeof(AppTransactionEntity), (int)APP.LBL.EntityType.AppTransactionEntity);
				AddNavigatorMetaData<AppListMenuEntity, EntityCollection<AppVersionEditionModuleEntity>>("AppVersionEditionModule", a => a._appVersionEditionModule, (a, b) => a._appVersionEditionModule = b, a => a.AppVersionEditionModule, () => new AppListMenuRelations().AppVersionEditionModuleEntityUsingMenuId, typeof(AppVersionEditionModuleEntity), (int)APP.LBL.EntityType.AppVersionEditionModuleEntity);
				AddNavigatorMetaData<AppListMenuEntity, AppCompanyEntity>("AppCompany", "AppListMenu", (a, b) => a._appCompany = b, a => a._appCompany, (a, b) => a.AppCompany = b, APP.LBL.RelationClasses.StaticAppListMenuRelations.AppCompanyEntityUsingAppCreatedByCompanyIdStatic, ()=>new AppListMenuRelations().AppCompanyEntityUsingAppCreatedByCompanyId, null, new int[] { (int)AppListMenuFieldIndex.AppCreatedByCompanyId }, null, true, (int)APP.LBL.EntityType.AppCompanyEntity);
				AddNavigatorMetaData<AppListMenuEntity, AppListMenuEntity>("AppListMenu", "AppListMenu_", (a, b) => a._appListMenu = b, a => a._appListMenu, (a, b) => a.AppListMenu = b, APP.LBL.RelationClasses.StaticAppListMenuRelations.AppListMenuEntityUsingMenuIdParentIdStatic, ()=>new AppListMenuRelations().AppListMenuEntityUsingMenuIdParentId, null, new int[] { (int)AppListMenuFieldIndex.ParentId }, null, true, (int)APP.LBL.EntityType.AppListMenuEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppListMenuEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppListMenuEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppListMenuEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppListMenuEntity</param>
		public AppListMenuEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="menuId">PK value for AppListMenu which data should be fetched into this AppListMenu object</param>
		public AppListMenuEntity(System.Int32 menuId) : this(menuId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="menuId">PK value for AppListMenu which data should be fetched into this AppListMenu object</param>
		/// <param name="validator">The custom validator object for this AppListMenuEntity</param>
		public AppListMenuEntity(System.Int32 menuId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.MenuId = menuId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppListMenuEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppApplicationAssetsItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppApplicationAssetsItem() { return CreateRelationInfoForNavigator("AppApplicationAssetsItem"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppDataSet' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppDataSet() { return CreateRelationInfoForNavigator("AppDataSet"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppDesktop' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppDesktop() { return CreateRelationInfoForNavigator("AppDesktop"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppEntityInfo' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppEntityInfo() { return CreateRelationInfoForNavigator("AppEntityInfo"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppEsite' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppEsite() { return CreateRelationInfoForNavigator("AppEsite"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppForm' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppForm() { return CreateRelationInfoForNavigator("AppForm"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppListMenu' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppListMenu_() { return CreateRelationInfoForNavigator("AppListMenu_"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppProjectOrWorkFlow' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppProjectOrWorkFlow() { return CreateRelationInfoForNavigator("AppProjectOrWorkFlow"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppReport' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppReport() { return CreateRelationInfoForNavigator("AppReport"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppSearch' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSearch() { return CreateRelationInfoForNavigator("AppSearch"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppSecurityRegDomainListMenu' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSecurityRegDomainListMenu() { return CreateRelationInfoForNavigator("AppSecurityRegDomainListMenu"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppSecurityUserListMenu' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSecurityUserListMenu() { return CreateRelationInfoForNavigator("AppSecurityUserListMenu"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppSysLabelLanguage' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSysLabelLanguage() { return CreateRelationInfoForNavigator("AppSysLabelLanguage"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppTransaction' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppTransaction() { return CreateRelationInfoForNavigator("AppTransaction"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppVersionEditionModule' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppVersionEditionModule() { return CreateRelationInfoForNavigator("AppVersionEditionModule"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppCompany' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppCompany() { return CreateRelationInfoForNavigator("AppCompany"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppListMenu' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppListMenu() { return CreateRelationInfoForNavigator("AppListMenu"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppListMenuEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppListMenuRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppApplicationAssetsItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppApplicationAssetsItem { get { return _staticMetaData.GetPrefetchPathElement("AppApplicationAssetsItem", CommonEntityBase.CreateEntityCollection<AppApplicationAssetsItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppDataSet' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppDataSet { get { return _staticMetaData.GetPrefetchPathElement("AppDataSet", CommonEntityBase.CreateEntityCollection<AppDataSetEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppDesktop' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppDesktop { get { return _staticMetaData.GetPrefetchPathElement("AppDesktop", CommonEntityBase.CreateEntityCollection<AppDesktopEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppEntityInfo' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppEntityInfo { get { return _staticMetaData.GetPrefetchPathElement("AppEntityInfo", CommonEntityBase.CreateEntityCollection<AppEntityInfoEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppEsite' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppEsite { get { return _staticMetaData.GetPrefetchPathElement("AppEsite", CommonEntityBase.CreateEntityCollection<AppEsiteEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppForm' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppForm { get { return _staticMetaData.GetPrefetchPathElement("AppForm", CommonEntityBase.CreateEntityCollection<AppFormEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppListMenu' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppListMenu_ { get { return _staticMetaData.GetPrefetchPathElement("AppListMenu_", CommonEntityBase.CreateEntityCollection<AppListMenuEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppProjectOrWorkFlow' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppProjectOrWorkFlow { get { return _staticMetaData.GetPrefetchPathElement("AppProjectOrWorkFlow", CommonEntityBase.CreateEntityCollection<AppProjectOrWorkFlowEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppReport' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppReport { get { return _staticMetaData.GetPrefetchPathElement("AppReport", CommonEntityBase.CreateEntityCollection<AppReportEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSearch' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSearch { get { return _staticMetaData.GetPrefetchPathElement("AppSearch", CommonEntityBase.CreateEntityCollection<AppSearchEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSecurityRegDomainListMenu' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSecurityRegDomainListMenu { get { return _staticMetaData.GetPrefetchPathElement("AppSecurityRegDomainListMenu", CommonEntityBase.CreateEntityCollection<AppSecurityRegDomainListMenuEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSecurityUserListMenu' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSecurityUserListMenu { get { return _staticMetaData.GetPrefetchPathElement("AppSecurityUserListMenu", CommonEntityBase.CreateEntityCollection<AppSecurityUserListMenuEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSysLabelLanguage' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSysLabelLanguage { get { return _staticMetaData.GetPrefetchPathElement("AppSysLabelLanguage", CommonEntityBase.CreateEntityCollection<AppSysLabelLanguageEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppTransaction' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppTransaction { get { return _staticMetaData.GetPrefetchPathElement("AppTransaction", CommonEntityBase.CreateEntityCollection<AppTransactionEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppVersionEditionModule' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppVersionEditionModule { get { return _staticMetaData.GetPrefetchPathElement("AppVersionEditionModule", CommonEntityBase.CreateEntityCollection<AppVersionEditionModuleEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppCompany' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppCompany { get { return _staticMetaData.GetPrefetchPathElement("AppCompany", CommonEntityBase.CreateEntityCollection<AppCompanyEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppListMenu' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppListMenu { get { return _staticMetaData.GetPrefetchPathElement("AppListMenu", CommonEntityBase.CreateEntityCollection<AppListMenuEntity>()); } }

		/// <summary>The MenuId property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."MenuID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 MenuId
		{
			get { return (System.Int32)GetValue((int)AppListMenuFieldIndex.MenuId, true); }
			set { SetValue((int)AppListMenuFieldIndex.MenuId, value); }
		}

		/// <summary>The ParentId property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."ParentID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> ParentId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppListMenuFieldIndex.ParentId, false); }
			set { SetValue((int)AppListMenuFieldIndex.ParentId, value); }
		}

		/// <summary>The Name property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."Name".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)AppListMenuFieldIndex.Name, true); }
			set { SetValue((int)AppListMenuFieldIndex.Name, value); }
		}

		/// <summary>The Description property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."Description".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)AppListMenuFieldIndex.Description, true); }
			set { SetValue((int)AppListMenuFieldIndex.Description, value); }
		}

		/// <summary>The IconName property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."IconName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String IconName
		{
			get { return (System.String)GetValue((int)AppListMenuFieldIndex.IconName, true); }
			set { SetValue((int)AppListMenuFieldIndex.IconName, value); }
		}

		/// <summary>The RouteCode property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."RouteCode".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String RouteCode
		{
			get { return (System.String)GetValue((int)AppListMenuFieldIndex.RouteCode, true); }
			set { SetValue((int)AppListMenuFieldIndex.RouteCode, value); }
		}

		/// <summary>The Link property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."Link".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Link
		{
			get { return (System.String)GetValue((int)AppListMenuFieldIndex.Link, true); }
			set { SetValue((int)AppListMenuFieldIndex.Link, value); }
		}

		/// <summary>The Sort property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."Sort".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Sort
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppListMenuFieldIndex.Sort, false); }
			set { SetValue((int)AppListMenuFieldIndex.Sort, value); }
		}

		/// <summary>The LinkType property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."LinkType".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 LinkType
		{
			get { return (System.Int32)GetValue((int)AppListMenuFieldIndex.LinkType, true); }
			set { SetValue((int)AppListMenuFieldIndex.LinkType, value); }
		}

		/// <summary>The IsSharedbyMutipleCompany property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."IsSharedbyMutipleCompany".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IsSharedbyMutipleCompany
		{
			get { return (Nullable<System.Boolean>)GetValue((int)AppListMenuFieldIndex.IsSharedbyMutipleCompany, false); }
			set { SetValue((int)AppListMenuFieldIndex.IsSharedbyMutipleCompany, value); }
		}

		/// <summary>The EmDeviceMenuShowMode property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."EmDeviceMenuShowMode".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> EmDeviceMenuShowMode
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppListMenuFieldIndex.EmDeviceMenuShowMode, false); }
			set { SetValue((int)AppListMenuFieldIndex.EmDeviceMenuShowMode, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppListMenuFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppListMenuFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppListMenuFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppListMenuFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppListMenuFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppListMenuFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppListMenuFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppListMenuFieldIndex.AppModifiedById, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppListMenuFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppListMenuFieldIndex.AppCreatedByCompanyId, value); }
		}

		/// <summary>The GlobalGuid property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."GlobalGuid".<br/>Table field type characteristics (type, precision, scale, length): UniqueIdentifier, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> GlobalGuid
		{
			get { return (Nullable<System.Guid>)GetValue((int)AppListMenuFieldIndex.GlobalGuid, false); }
			set { SetValue((int)AppListMenuFieldIndex.GlobalGuid, value); }
		}

		/// <summary>The ModuleRegisterId property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."ModuleRegisterID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> ModuleRegisterId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppListMenuFieldIndex.ModuleRegisterId, false); }
			set { SetValue((int)AppListMenuFieldIndex.ModuleRegisterId, value); }
		}

		/// <summary>The DisplayModeMenuOrTab property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."DisplayModeMenuOrTab".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> DisplayModeMenuOrTab
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppListMenuFieldIndex.DisplayModeMenuOrTab, false); }
			set { SetValue((int)AppListMenuFieldIndex.DisplayModeMenuOrTab, value); }
		}

		/// <summary>The IconName2 property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."IconName2".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String IconName2
		{
			get { return (System.String)GetValue((int)AppListMenuFieldIndex.IconName2, true); }
			set { SetValue((int)AppListMenuFieldIndex.IconName2, value); }
		}

		/// <summary>The EsiteId property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."EsiteID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> EsiteId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppListMenuFieldIndex.EsiteId, false); }
			set { SetValue((int)AppListMenuFieldIndex.EsiteId, value); }
		}

		/// <summary>The EmAppMenuItemCategory property of the Entity AppListMenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppListMenu"."EmAppMenuItemCategory".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> EmAppMenuItemCategory
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppListMenuFieldIndex.EmAppMenuItemCategory, false); }
			set { SetValue((int)AppListMenuFieldIndex.EmAppMenuItemCategory, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'AppApplicationAssetsItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppApplicationAssetsItemEntity))]
		public virtual EntityCollection<AppApplicationAssetsItemEntity> AppApplicationAssetsItem { get { return GetOrCreateEntityCollection<AppApplicationAssetsItemEntity, AppApplicationAssetsItemEntityFactory>("AppListMenu", true, false, ref _appApplicationAssetsItem); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppDataSetEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppDataSetEntity))]
		public virtual EntityCollection<AppDataSetEntity> AppDataSet { get { return GetOrCreateEntityCollection<AppDataSetEntity, AppDataSetEntityFactory>("AppListMenu", true, false, ref _appDataSet); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppDesktopEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppDesktopEntity))]
		public virtual EntityCollection<AppDesktopEntity> AppDesktop { get { return GetOrCreateEntityCollection<AppDesktopEntity, AppDesktopEntityFactory>("AppListMenu", true, false, ref _appDesktop); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppEntityInfoEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppEntityInfoEntity))]
		public virtual EntityCollection<AppEntityInfoEntity> AppEntityInfo { get { return GetOrCreateEntityCollection<AppEntityInfoEntity, AppEntityInfoEntityFactory>("AppListMenu", true, false, ref _appEntityInfo); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppEsiteEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppEsiteEntity))]
		public virtual EntityCollection<AppEsiteEntity> AppEsite { get { return GetOrCreateEntityCollection<AppEsiteEntity, AppEsiteEntityFactory>("AppListMenu", true, false, ref _appEsite); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppFormEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppFormEntity))]
		public virtual EntityCollection<AppFormEntity> AppForm { get { return GetOrCreateEntityCollection<AppFormEntity, AppFormEntityFactory>("AppListMenu", true, false, ref _appForm); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppListMenuEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppListMenuEntity))]
		public virtual EntityCollection<AppListMenuEntity> AppListMenu_ { get { return GetOrCreateEntityCollection<AppListMenuEntity, AppListMenuEntityFactory>("AppListMenu", true, false, ref _appListMenu_); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppProjectOrWorkFlowEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppProjectOrWorkFlowEntity))]
		public virtual EntityCollection<AppProjectOrWorkFlowEntity> AppProjectOrWorkFlow { get { return GetOrCreateEntityCollection<AppProjectOrWorkFlowEntity, AppProjectOrWorkFlowEntityFactory>("AppListMenu", true, false, ref _appProjectOrWorkFlow); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppReportEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppReportEntity))]
		public virtual EntityCollection<AppReportEntity> AppReport { get { return GetOrCreateEntityCollection<AppReportEntity, AppReportEntityFactory>("AppListMenu", true, false, ref _appReport); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppSearchEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppSearchEntity))]
		public virtual EntityCollection<AppSearchEntity> AppSearch { get { return GetOrCreateEntityCollection<AppSearchEntity, AppSearchEntityFactory>("AppListMenu", true, false, ref _appSearch); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppSecurityRegDomainListMenuEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppSecurityRegDomainListMenuEntity))]
		public virtual EntityCollection<AppSecurityRegDomainListMenuEntity> AppSecurityRegDomainListMenu { get { return GetOrCreateEntityCollection<AppSecurityRegDomainListMenuEntity, AppSecurityRegDomainListMenuEntityFactory>("AppListMenu", true, false, ref _appSecurityRegDomainListMenu); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppSecurityUserListMenuEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppSecurityUserListMenuEntity))]
		public virtual EntityCollection<AppSecurityUserListMenuEntity> AppSecurityUserListMenu { get { return GetOrCreateEntityCollection<AppSecurityUserListMenuEntity, AppSecurityUserListMenuEntityFactory>("AppListMenu", true, false, ref _appSecurityUserListMenu); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppSysLabelLanguageEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppSysLabelLanguageEntity))]
		public virtual EntityCollection<AppSysLabelLanguageEntity> AppSysLabelLanguage { get { return GetOrCreateEntityCollection<AppSysLabelLanguageEntity, AppSysLabelLanguageEntityFactory>("AppListMenu", true, false, ref _appSysLabelLanguage); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppTransactionEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppTransactionEntity))]
		public virtual EntityCollection<AppTransactionEntity> AppTransaction { get { return GetOrCreateEntityCollection<AppTransactionEntity, AppTransactionEntityFactory>("AppListMenu", true, false, ref _appTransaction); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppVersionEditionModuleEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppVersionEditionModuleEntity))]
		public virtual EntityCollection<AppVersionEditionModuleEntity> AppVersionEditionModule { get { return GetOrCreateEntityCollection<AppVersionEditionModuleEntity, AppVersionEditionModuleEntityFactory>("AppListMenu", true, false, ref _appVersionEditionModule); } }

		/// <summary>Gets / sets related entity of type 'AppCompanyEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppCompanyEntity AppCompany
		{
			get { return _appCompany; }
			set { SetSingleRelatedEntityNavigator(value, "AppCompany"); }
		}

		/// <summary>Gets / sets related entity of type 'AppListMenuEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppListMenuEntity AppListMenu
		{
			get { return _appListMenu; }
			set { SetSingleRelatedEntityNavigator(value, "AppListMenu"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppListMenuFieldIndex
	{
		///<summary>MenuId. </summary>
		MenuId,
		///<summary>ParentId. </summary>
		ParentId,
		///<summary>Name. </summary>
		Name,
		///<summary>Description. </summary>
		Description,
		///<summary>IconName. </summary>
		IconName,
		///<summary>RouteCode. </summary>
		RouteCode,
		///<summary>Link. </summary>
		Link,
		///<summary>Sort. </summary>
		Sort,
		///<summary>LinkType. </summary>
		LinkType,
		///<summary>IsSharedbyMutipleCompany. </summary>
		IsSharedbyMutipleCompany,
		///<summary>EmDeviceMenuShowMode. </summary>
		EmDeviceMenuShowMode,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		///<summary>GlobalGuid. </summary>
		GlobalGuid,
		///<summary>ModuleRegisterId. </summary>
		ModuleRegisterId,
		///<summary>DisplayModeMenuOrTab. </summary>
		DisplayModeMenuOrTab,
		///<summary>IconName2. </summary>
		IconName2,
		///<summary>EsiteId. </summary>
		EsiteId,
		///<summary>EmAppMenuItemCategory. </summary>
		EmAppMenuItemCategory,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppListMenu. </summary>
	public partial class AppListMenuRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppApplicationAssetsItemEntity over the 1:n relation they have, using the relation between the fields: AppListMenu.MenuId - AppApplicationAssetsItem.ApplicationId</summary>
		public virtual IEntityRelation AppApplicationAssetsItemEntityUsingApplicationId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppApplicationAssetsItem", true, new[] { AppListMenuFields.MenuId, AppApplicationAssetsItemFields.ApplicationId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppDataSetEntity over the 1:n relation they have, using the relation between the fields: AppListMenu.MenuId - AppDataSet.SaasApplicationId</summary>
		public virtual IEntityRelation AppDataSetEntityUsingSaasApplicationId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppDataSet", true, new[] { AppListMenuFields.MenuId, AppDataSetFields.SaasApplicationId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppDesktopEntity over the 1:n relation they have, using the relation between the fields: AppListMenu.MenuId - AppDesktop.SaasApplicationId</summary>
		public virtual IEntityRelation AppDesktopEntityUsingSaasApplicationId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppDesktop", true, new[] { AppListMenuFields.MenuId, AppDesktopFields.SaasApplicationId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppEntityInfoEntity over the 1:n relation they have, using the relation between the fields: AppListMenu.MenuId - AppEntityInfo.SaasApplicationId</summary>
		public virtual IEntityRelation AppEntityInfoEntityUsingSaasApplicationId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppEntityInfo", true, new[] { AppListMenuFields.MenuId, AppEntityInfoFields.SaasApplicationId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppEsiteEntity over the 1:n relation they have, using the relation between the fields: AppListMenu.MenuId - AppEsite.SaasApplicationId</summary>
		public virtual IEntityRelation AppEsiteEntityUsingSaasApplicationId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppEsite", true, new[] { AppListMenuFields.MenuId, AppEsiteFields.SaasApplicationId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppFormEntity over the 1:n relation they have, using the relation between the fields: AppListMenu.MenuId - AppForm.SaasApplicationId</summary>
		public virtual IEntityRelation AppFormEntityUsingSaasApplicationId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppForm", true, new[] { AppListMenuFields.MenuId, AppFormFields.SaasApplicationId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppListMenuEntity over the 1:n relation they have, using the relation between the fields: AppListMenu.MenuId - AppListMenu.ParentId</summary>
		public virtual IEntityRelation AppListMenuEntityUsingParentId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppListMenu_", true, new[] { AppListMenuFields.MenuId, AppListMenuFields.ParentId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppProjectOrWorkFlowEntity over the 1:n relation they have, using the relation between the fields: AppListMenu.MenuId - AppProjectOrWorkFlow.SaasApplicationId</summary>
		public virtual IEntityRelation AppProjectOrWorkFlowEntityUsingSaasApplicationId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppProjectOrWorkFlow", true, new[] { AppListMenuFields.MenuId, AppProjectOrWorkFlowFields.SaasApplicationId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppReportEntity over the 1:n relation they have, using the relation between the fields: AppListMenu.MenuId - AppReport.SaasApplicationId</summary>
		public virtual IEntityRelation AppReportEntityUsingSaasApplicationId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppReport", true, new[] { AppListMenuFields.MenuId, AppReportFields.SaasApplicationId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppSearchEntity over the 1:n relation they have, using the relation between the fields: AppListMenu.MenuId - AppSearch.SaasApplicationId</summary>
		public virtual IEntityRelation AppSearchEntityUsingSaasApplicationId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppSearch", true, new[] { AppListMenuFields.MenuId, AppSearchFields.SaasApplicationId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppSecurityRegDomainListMenuEntity over the 1:n relation they have, using the relation between the fields: AppListMenu.MenuId - AppSecurityRegDomainListMenu.MenuId</summary>
		public virtual IEntityRelation AppSecurityRegDomainListMenuEntityUsingMenuId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppSecurityRegDomainListMenu", true, new[] { AppListMenuFields.MenuId, AppSecurityRegDomainListMenuFields.MenuId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppSecurityUserListMenuEntity over the 1:n relation they have, using the relation between the fields: AppListMenu.MenuId - AppSecurityUserListMenu.MenuId</summary>
		public virtual IEntityRelation AppSecurityUserListMenuEntityUsingMenuId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppSecurityUserListMenu", true, new[] { AppListMenuFields.MenuId, AppSecurityUserListMenuFields.MenuId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppSysLabelLanguageEntity over the 1:n relation they have, using the relation between the fields: AppListMenu.MenuId - AppSysLabelLanguage.MenuId</summary>
		public virtual IEntityRelation AppSysLabelLanguageEntityUsingMenuId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppSysLabelLanguage", true, new[] { AppListMenuFields.MenuId, AppSysLabelLanguageFields.MenuId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppTransactionEntity over the 1:n relation they have, using the relation between the fields: AppListMenu.MenuId - AppTransaction.SaasApplicationId</summary>
		public virtual IEntityRelation AppTransactionEntityUsingSaasApplicationId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppTransaction", true, new[] { AppListMenuFields.MenuId, AppTransactionFields.SaasApplicationId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppVersionEditionModuleEntity over the 1:n relation they have, using the relation between the fields: AppListMenu.MenuId - AppVersionEditionModule.MenuId</summary>
		public virtual IEntityRelation AppVersionEditionModuleEntityUsingMenuId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppVersionEditionModule", true, new[] { AppListMenuFields.MenuId, AppVersionEditionModuleFields.MenuId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppCompanyEntity over the m:1 relation they have, using the relation between the fields: AppListMenu.AppCreatedByCompanyId - AppCompany.AppCompanyId</summary>
		public virtual IEntityRelation AppCompanyEntityUsingAppCreatedByCompanyId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppCompany", false, new[] { AppCompanyFields.AppCompanyId, AppListMenuFields.AppCreatedByCompanyId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppListMenuEntity and AppListMenuEntity over the m:1 relation they have, using the relation between the fields: AppListMenu.ParentId - AppListMenu.MenuId</summary>
		public virtual IEntityRelation AppListMenuEntityUsingMenuIdParentId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppListMenu", false, new[] { AppListMenuFields.MenuId, AppListMenuFields.ParentId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppListMenuRelations
	{
		internal static readonly IEntityRelation AppApplicationAssetsItemEntityUsingApplicationIdStatic = new AppListMenuRelations().AppApplicationAssetsItemEntityUsingApplicationId;
		internal static readonly IEntityRelation AppDataSetEntityUsingSaasApplicationIdStatic = new AppListMenuRelations().AppDataSetEntityUsingSaasApplicationId;
		internal static readonly IEntityRelation AppDesktopEntityUsingSaasApplicationIdStatic = new AppListMenuRelations().AppDesktopEntityUsingSaasApplicationId;
		internal static readonly IEntityRelation AppEntityInfoEntityUsingSaasApplicationIdStatic = new AppListMenuRelations().AppEntityInfoEntityUsingSaasApplicationId;
		internal static readonly IEntityRelation AppEsiteEntityUsingSaasApplicationIdStatic = new AppListMenuRelations().AppEsiteEntityUsingSaasApplicationId;
		internal static readonly IEntityRelation AppFormEntityUsingSaasApplicationIdStatic = new AppListMenuRelations().AppFormEntityUsingSaasApplicationId;
		internal static readonly IEntityRelation AppListMenuEntityUsingParentIdStatic = new AppListMenuRelations().AppListMenuEntityUsingParentId;
		internal static readonly IEntityRelation AppProjectOrWorkFlowEntityUsingSaasApplicationIdStatic = new AppListMenuRelations().AppProjectOrWorkFlowEntityUsingSaasApplicationId;
		internal static readonly IEntityRelation AppReportEntityUsingSaasApplicationIdStatic = new AppListMenuRelations().AppReportEntityUsingSaasApplicationId;
		internal static readonly IEntityRelation AppSearchEntityUsingSaasApplicationIdStatic = new AppListMenuRelations().AppSearchEntityUsingSaasApplicationId;
		internal static readonly IEntityRelation AppSecurityRegDomainListMenuEntityUsingMenuIdStatic = new AppListMenuRelations().AppSecurityRegDomainListMenuEntityUsingMenuId;
		internal static readonly IEntityRelation AppSecurityUserListMenuEntityUsingMenuIdStatic = new AppListMenuRelations().AppSecurityUserListMenuEntityUsingMenuId;
		internal static readonly IEntityRelation AppSysLabelLanguageEntityUsingMenuIdStatic = new AppListMenuRelations().AppSysLabelLanguageEntityUsingMenuId;
		internal static readonly IEntityRelation AppTransactionEntityUsingSaasApplicationIdStatic = new AppListMenuRelations().AppTransactionEntityUsingSaasApplicationId;
		internal static readonly IEntityRelation AppVersionEditionModuleEntityUsingMenuIdStatic = new AppListMenuRelations().AppVersionEditionModuleEntityUsingMenuId;
		internal static readonly IEntityRelation AppCompanyEntityUsingAppCreatedByCompanyIdStatic = new AppListMenuRelations().AppCompanyEntityUsingAppCreatedByCompanyId;
		internal static readonly IEntityRelation AppListMenuEntityUsingMenuIdParentIdStatic = new AppListMenuRelations().AppListMenuEntityUsingMenuIdParentId;

		/// <summary>CTor</summary>
		static StaticAppListMenuRelations() { }
	}
}
