//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:17 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppmessageNotificationSetting'.<br/><br/></summary>
	[Serializable]
	public partial class AppmessageNotificationSettingEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<AppmessageNotificationSettingEntity> _appmessageNotificationSetting_;
		private AppmessageNotificationSettingEntity _appmessageNotificationSetting;
		private AppTransactionEntity _appTransaction;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppmessageNotificationSettingEntityStaticMetaData _staticMetaData = new AppmessageNotificationSettingEntityStaticMetaData();
		private static AppmessageNotificationSettingRelations _relationsFactory = new AppmessageNotificationSettingRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppmessageNotificationSetting</summary>
			public static readonly string AppmessageNotificationSetting = "AppmessageNotificationSetting";
			/// <summary>Member name AppTransaction</summary>
			public static readonly string AppTransaction = "AppTransaction";
			/// <summary>Member name AppmessageNotificationSetting_</summary>
			public static readonly string AppmessageNotificationSetting_ = "AppmessageNotificationSetting_";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppmessageNotificationSettingEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppmessageNotificationSettingEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppmessageNotificationSettingEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppmessageNotificationSettingEntity, typeof(AppmessageNotificationSettingEntity), typeof(AppmessageNotificationSettingEntityFactory), false);
				AddNavigatorMetaData<AppmessageNotificationSettingEntity, EntityCollection<AppmessageNotificationSettingEntity>>("AppmessageNotificationSetting_", a => a._appmessageNotificationSetting_, (a, b) => a._appmessageNotificationSetting_ = b, a => a.AppmessageNotificationSetting_, () => new AppmessageNotificationSettingRelations().AppmessageNotificationSettingEntityUsingNotificationQueryContentSettingId, typeof(AppmessageNotificationSettingEntity), (int)APP.LBL.EntityType.AppmessageNotificationSettingEntity);
				AddNavigatorMetaData<AppmessageNotificationSettingEntity, AppmessageNotificationSettingEntity>("AppmessageNotificationSetting", "AppmessageNotificationSetting_", (a, b) => a._appmessageNotificationSetting = b, a => a._appmessageNotificationSetting, (a, b) => a.AppmessageNotificationSetting = b, APP.LBL.RelationClasses.StaticAppmessageNotificationSettingRelations.AppmessageNotificationSettingEntityUsingNotificationSettingIdNotificationQueryContentSettingIdStatic, ()=>new AppmessageNotificationSettingRelations().AppmessageNotificationSettingEntityUsingNotificationSettingIdNotificationQueryContentSettingId, null, new int[] { (int)AppmessageNotificationSettingFieldIndex.NotificationQueryContentSettingId }, null, true, (int)APP.LBL.EntityType.AppmessageNotificationSettingEntity);
				AddNavigatorMetaData<AppmessageNotificationSettingEntity, AppTransactionEntity>("AppTransaction", "AppmessageNotificationSetting", (a, b) => a._appTransaction = b, a => a._appTransaction, (a, b) => a.AppTransaction = b, APP.LBL.RelationClasses.StaticAppmessageNotificationSettingRelations.AppTransactionEntityUsingTranscationIdStatic, ()=>new AppmessageNotificationSettingRelations().AppTransactionEntityUsingTranscationId, null, new int[] { (int)AppmessageNotificationSettingFieldIndex.TranscationId }, null, true, (int)APP.LBL.EntityType.AppTransactionEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppmessageNotificationSettingEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppmessageNotificationSettingEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppmessageNotificationSettingEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppmessageNotificationSettingEntity</param>
		public AppmessageNotificationSettingEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="notificationSettingId">PK value for AppmessageNotificationSetting which data should be fetched into this AppmessageNotificationSetting object</param>
		public AppmessageNotificationSettingEntity(System.Int32 notificationSettingId) : this(notificationSettingId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="notificationSettingId">PK value for AppmessageNotificationSetting which data should be fetched into this AppmessageNotificationSetting object</param>
		/// <param name="validator">The custom validator object for this AppmessageNotificationSettingEntity</param>
		public AppmessageNotificationSettingEntity(System.Int32 notificationSettingId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.NotificationSettingId = notificationSettingId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppmessageNotificationSettingEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppmessageNotificationSetting' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppmessageNotificationSetting_() { return CreateRelationInfoForNavigator("AppmessageNotificationSetting_"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppmessageNotificationSetting' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppmessageNotificationSetting() { return CreateRelationInfoForNavigator("AppmessageNotificationSetting"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppTransaction' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppTransaction() { return CreateRelationInfoForNavigator("AppTransaction"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppmessageNotificationSettingEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppmessageNotificationSettingRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppmessageNotificationSetting' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppmessageNotificationSetting_ { get { return _staticMetaData.GetPrefetchPathElement("AppmessageNotificationSetting_", CommonEntityBase.CreateEntityCollection<AppmessageNotificationSettingEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppmessageNotificationSetting' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppmessageNotificationSetting { get { return _staticMetaData.GetPrefetchPathElement("AppmessageNotificationSetting", CommonEntityBase.CreateEntityCollection<AppmessageNotificationSettingEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppTransaction' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppTransaction { get { return _staticMetaData.GetPrefetchPathElement("AppTransaction", CommonEntityBase.CreateEntityCollection<AppTransactionEntity>()); } }

		/// <summary>The NotificationSettingId property of the Entity AppmessageNotificationSetting<br/><br/></summary>
		/// <remarks>Mapped on  table field: "APPMessageNotificationSetting"."NotificationSettingID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 NotificationSettingId
		{
			get { return (System.Int32)GetValue((int)AppmessageNotificationSettingFieldIndex.NotificationSettingId, true); }
			set { SetValue((int)AppmessageNotificationSettingFieldIndex.NotificationSettingId, value); }
		}

		/// <summary>The TranscationId property of the Entity AppmessageNotificationSetting<br/><br/></summary>
		/// <remarks>Mapped on  table field: "APPMessageNotificationSetting"."TranscationID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> TranscationId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppmessageNotificationSettingFieldIndex.TranscationId, false); }
			set { SetValue((int)AppmessageNotificationSettingFieldIndex.TranscationId, value); }
		}

		/// <summary>The ProejctId property of the Entity AppmessageNotificationSetting<br/><br/></summary>
		/// <remarks>Mapped on  table field: "APPMessageNotificationSetting"."ProejctID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> ProejctId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppmessageNotificationSettingFieldIndex.ProejctId, false); }
			set { SetValue((int)AppmessageNotificationSettingFieldIndex.ProejctId, value); }
		}

		/// <summary>The SettingName property of the Entity AppmessageNotificationSetting<br/><br/></summary>
		/// <remarks>Mapped on  table field: "APPMessageNotificationSetting"."SettingName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String SettingName
		{
			get { return (System.String)GetValue((int)AppmessageNotificationSettingFieldIndex.SettingName, true); }
			set { SetValue((int)AppmessageNotificationSettingFieldIndex.SettingName, value); }
		}

		/// <summary>The NotificationQuery property of the Entity AppmessageNotificationSetting<br/><br/></summary>
		/// <remarks>Mapped on  table field: "APPMessageNotificationSetting"."NotificationQuery".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String NotificationQuery
		{
			get { return (System.String)GetValue((int)AppmessageNotificationSettingFieldIndex.NotificationQuery, true); }
			set { SetValue((int)AppmessageNotificationSettingFieldIndex.NotificationQuery, value); }
		}

		/// <summary>The MessageUsageType property of the Entity AppmessageNotificationSetting<br/><br/></summary>
		/// <remarks>Mapped on  table field: "APPMessageNotificationSetting"."MessageUsageType".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> MessageUsageType
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppmessageNotificationSettingFieldIndex.MessageUsageType, false); }
			set { SetValue((int)AppmessageNotificationSettingFieldIndex.MessageUsageType, value); }
		}

		/// <summary>The MessageTemplateId property of the Entity AppmessageNotificationSetting<br/><br/></summary>
		/// <remarks>Mapped on  table field: "APPMessageNotificationSetting"."MessageTemplateID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> MessageTemplateId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppmessageNotificationSettingFieldIndex.MessageTemplateId, false); }
			set { SetValue((int)AppmessageNotificationSettingFieldIndex.MessageTemplateId, value); }
		}

		/// <summary>The MessageTemplate property of the Entity AppmessageNotificationSetting<br/><br/></summary>
		/// <remarks>Mapped on  table field: "APPMessageNotificationSetting"."MessageTemplate".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String MessageTemplate
		{
			get { return (System.String)GetValue((int)AppmessageNotificationSettingFieldIndex.MessageTemplate, true); }
			set { SetValue((int)AppmessageNotificationSettingFieldIndex.MessageTemplate, value); }
		}

		/// <summary>The EmScanPeriod property of the Entity AppmessageNotificationSetting<br/><br/></summary>
		/// <remarks>Mapped on  table field: "APPMessageNotificationSetting"."EmScanPeriod".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> EmScanPeriod
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppmessageNotificationSettingFieldIndex.EmScanPeriod, false); }
			set { SetValue((int)AppmessageNotificationSettingFieldIndex.EmScanPeriod, value); }
		}

		/// <summary>The NotificationQueryContentSettingId property of the Entity AppmessageNotificationSetting<br/><br/></summary>
		/// <remarks>Mapped on  table field: "APPMessageNotificationSetting"."NotificationQueryContentSettingID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> NotificationQueryContentSettingId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppmessageNotificationSettingFieldIndex.NotificationQueryContentSettingId, false); }
			set { SetValue((int)AppmessageNotificationSettingFieldIndex.NotificationQueryContentSettingId, value); }
		}

		/// <summary>The AlertSpanTime property of the Entity AppmessageNotificationSetting<br/><br/></summary>
		/// <remarks>Mapped on  table field: "APPMessageNotificationSetting"."AlertSpanTime".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AlertSpanTime
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppmessageNotificationSettingFieldIndex.AlertSpanTime, false); }
			set { SetValue((int)AppmessageNotificationSettingFieldIndex.AlertSpanTime, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppmessageNotificationSetting<br/><br/></summary>
		/// <remarks>Mapped on  table field: "APPMessageNotificationSetting"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppmessageNotificationSettingFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppmessageNotificationSettingFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppmessageNotificationSetting<br/><br/></summary>
		/// <remarks>Mapped on  table field: "APPMessageNotificationSetting"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): Date, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppmessageNotificationSettingFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppmessageNotificationSettingFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppmessageNotificationSetting<br/><br/></summary>
		/// <remarks>Mapped on  table field: "APPMessageNotificationSetting"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): Date, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppmessageNotificationSettingFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppmessageNotificationSettingFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppmessageNotificationSetting<br/><br/></summary>
		/// <remarks>Mapped on  table field: "APPMessageNotificationSetting"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppmessageNotificationSettingFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppmessageNotificationSettingFieldIndex.AppModifiedById, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppmessageNotificationSetting<br/><br/></summary>
		/// <remarks>Mapped on  table field: "APPMessageNotificationSetting"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppmessageNotificationSettingFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppmessageNotificationSettingFieldIndex.AppCreatedByCompanyId, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'AppmessageNotificationSettingEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppmessageNotificationSettingEntity))]
		public virtual EntityCollection<AppmessageNotificationSettingEntity> AppmessageNotificationSetting_ { get { return GetOrCreateEntityCollection<AppmessageNotificationSettingEntity, AppmessageNotificationSettingEntityFactory>("AppmessageNotificationSetting", true, false, ref _appmessageNotificationSetting_); } }

		/// <summary>Gets / sets related entity of type 'AppmessageNotificationSettingEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppmessageNotificationSettingEntity AppmessageNotificationSetting
		{
			get { return _appmessageNotificationSetting; }
			set { SetSingleRelatedEntityNavigator(value, "AppmessageNotificationSetting"); }
		}

		/// <summary>Gets / sets related entity of type 'AppTransactionEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppTransactionEntity AppTransaction
		{
			get { return _appTransaction; }
			set { SetSingleRelatedEntityNavigator(value, "AppTransaction"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppmessageNotificationSettingFieldIndex
	{
		///<summary>NotificationSettingId. </summary>
		NotificationSettingId,
		///<summary>TranscationId. </summary>
		TranscationId,
		///<summary>ProejctId. </summary>
		ProejctId,
		///<summary>SettingName. </summary>
		SettingName,
		///<summary>NotificationQuery. </summary>
		NotificationQuery,
		///<summary>MessageUsageType. </summary>
		MessageUsageType,
		///<summary>MessageTemplateId. </summary>
		MessageTemplateId,
		///<summary>MessageTemplate. </summary>
		MessageTemplate,
		///<summary>EmScanPeriod. </summary>
		EmScanPeriod,
		///<summary>NotificationQueryContentSettingId. </summary>
		NotificationQueryContentSettingId,
		///<summary>AlertSpanTime. </summary>
		AlertSpanTime,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppmessageNotificationSetting. </summary>
	public partial class AppmessageNotificationSettingRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between AppmessageNotificationSettingEntity and AppmessageNotificationSettingEntity over the 1:n relation they have, using the relation between the fields: AppmessageNotificationSetting.NotificationSettingId - AppmessageNotificationSetting.NotificationQueryContentSettingId</summary>
		public virtual IEntityRelation AppmessageNotificationSettingEntityUsingNotificationQueryContentSettingId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppmessageNotificationSetting_", true, new[] { AppmessageNotificationSettingFields.NotificationSettingId, AppmessageNotificationSettingFields.NotificationQueryContentSettingId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppmessageNotificationSettingEntity and AppmessageNotificationSettingEntity over the m:1 relation they have, using the relation between the fields: AppmessageNotificationSetting.NotificationQueryContentSettingId - AppmessageNotificationSetting.NotificationSettingId</summary>
		public virtual IEntityRelation AppmessageNotificationSettingEntityUsingNotificationSettingIdNotificationQueryContentSettingId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppmessageNotificationSetting", false, new[] { AppmessageNotificationSettingFields.NotificationSettingId, AppmessageNotificationSettingFields.NotificationQueryContentSettingId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppmessageNotificationSettingEntity and AppTransactionEntity over the m:1 relation they have, using the relation between the fields: AppmessageNotificationSetting.TranscationId - AppTransaction.TransactionId</summary>
		public virtual IEntityRelation AppTransactionEntityUsingTranscationId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppTransaction", false, new[] { AppTransactionFields.TransactionId, AppmessageNotificationSettingFields.TranscationId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppmessageNotificationSettingRelations
	{
		internal static readonly IEntityRelation AppmessageNotificationSettingEntityUsingNotificationQueryContentSettingIdStatic = new AppmessageNotificationSettingRelations().AppmessageNotificationSettingEntityUsingNotificationQueryContentSettingId;
		internal static readonly IEntityRelation AppmessageNotificationSettingEntityUsingNotificationSettingIdNotificationQueryContentSettingIdStatic = new AppmessageNotificationSettingRelations().AppmessageNotificationSettingEntityUsingNotificationSettingIdNotificationQueryContentSettingId;
		internal static readonly IEntityRelation AppTransactionEntityUsingTranscationIdStatic = new AppmessageNotificationSettingRelations().AppTransactionEntityUsingTranscationId;

		/// <summary>CTor</summary>
		static StaticAppmessageNotificationSettingRelations() { }
	}
}
