//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:17 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppProjectTeamMemberRole'.<br/><br/></summary>
	[Serializable]
	public partial class AppProjectTeamMemberRoleEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private AppProjectRoleEntity _appProjectRole;
		private AppProjectTeamMemberEntity _appProjectTeamMember;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppProjectTeamMemberRoleEntityStaticMetaData _staticMetaData = new AppProjectTeamMemberRoleEntityStaticMetaData();
		private static AppProjectTeamMemberRoleRelations _relationsFactory = new AppProjectTeamMemberRoleRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppProjectRole</summary>
			public static readonly string AppProjectRole = "AppProjectRole";
			/// <summary>Member name AppProjectTeamMember</summary>
			public static readonly string AppProjectTeamMember = "AppProjectTeamMember";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppProjectTeamMemberRoleEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppProjectTeamMemberRoleEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppProjectTeamMemberRoleEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppProjectTeamMemberRoleEntity, typeof(AppProjectTeamMemberRoleEntity), typeof(AppProjectTeamMemberRoleEntityFactory), false);
				AddNavigatorMetaData<AppProjectTeamMemberRoleEntity, AppProjectRoleEntity>("AppProjectRole", "AppProjectTeamMemberRole", (a, b) => a._appProjectRole = b, a => a._appProjectRole, (a, b) => a.AppProjectRole = b, APP.LBL.RelationClasses.StaticAppProjectTeamMemberRoleRelations.AppProjectRoleEntityUsingProjectRoleIdStatic, ()=>new AppProjectTeamMemberRoleRelations().AppProjectRoleEntityUsingProjectRoleId, null, new int[] { (int)AppProjectTeamMemberRoleFieldIndex.ProjectRoleId }, null, true, (int)APP.LBL.EntityType.AppProjectRoleEntity);
				AddNavigatorMetaData<AppProjectTeamMemberRoleEntity, AppProjectTeamMemberEntity>("AppProjectTeamMember", "AppProjectTeamMemberRole", (a, b) => a._appProjectTeamMember = b, a => a._appProjectTeamMember, (a, b) => a.AppProjectTeamMember = b, APP.LBL.RelationClasses.StaticAppProjectTeamMemberRoleRelations.AppProjectTeamMemberEntityUsingTeamMemberIdStatic, ()=>new AppProjectTeamMemberRoleRelations().AppProjectTeamMemberEntityUsingTeamMemberId, null, new int[] { (int)AppProjectTeamMemberRoleFieldIndex.TeamMemberId }, null, true, (int)APP.LBL.EntityType.AppProjectTeamMemberEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppProjectTeamMemberRoleEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppProjectTeamMemberRoleEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppProjectTeamMemberRoleEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppProjectTeamMemberRoleEntity</param>
		public AppProjectTeamMemberRoleEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="teamMemberRoleId">PK value for AppProjectTeamMemberRole which data should be fetched into this AppProjectTeamMemberRole object</param>
		public AppProjectTeamMemberRoleEntity(System.Int32 teamMemberRoleId) : this(teamMemberRoleId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="teamMemberRoleId">PK value for AppProjectTeamMemberRole which data should be fetched into this AppProjectTeamMemberRole object</param>
		/// <param name="validator">The custom validator object for this AppProjectTeamMemberRoleEntity</param>
		public AppProjectTeamMemberRoleEntity(System.Int32 teamMemberRoleId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.TeamMemberRoleId = teamMemberRoleId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppProjectTeamMemberRoleEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppProjectRole' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppProjectRole() { return CreateRelationInfoForNavigator("AppProjectRole"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppProjectTeamMember' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppProjectTeamMember() { return CreateRelationInfoForNavigator("AppProjectTeamMember"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppProjectTeamMemberRoleEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppProjectTeamMemberRoleRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppProjectRole' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppProjectRole { get { return _staticMetaData.GetPrefetchPathElement("AppProjectRole", CommonEntityBase.CreateEntityCollection<AppProjectRoleEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppProjectTeamMember' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppProjectTeamMember { get { return _staticMetaData.GetPrefetchPathElement("AppProjectTeamMember", CommonEntityBase.CreateEntityCollection<AppProjectTeamMemberEntity>()); } }

		/// <summary>The TeamMemberRoleId property of the Entity AppProjectTeamMemberRole<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppProjectTeamMemberRole"."TeamMemberRoleID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 TeamMemberRoleId
		{
			get { return (System.Int32)GetValue((int)AppProjectTeamMemberRoleFieldIndex.TeamMemberRoleId, true); }
			set { SetValue((int)AppProjectTeamMemberRoleFieldIndex.TeamMemberRoleId, value); }
		}

		/// <summary>The TeamMemberId property of the Entity AppProjectTeamMemberRole<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppProjectTeamMemberRole"."TeamMemberID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> TeamMemberId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppProjectTeamMemberRoleFieldIndex.TeamMemberId, false); }
			set { SetValue((int)AppProjectTeamMemberRoleFieldIndex.TeamMemberId, value); }
		}

		/// <summary>The ProjectRoleId property of the Entity AppProjectTeamMemberRole<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppProjectTeamMemberRole"."ProjectRoleID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> ProjectRoleId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppProjectTeamMemberRoleFieldIndex.ProjectRoleId, false); }
			set { SetValue((int)AppProjectTeamMemberRoleFieldIndex.ProjectRoleId, value); }
		}

		/// <summary>The RoleRate property of the Entity AppProjectTeamMemberRole<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppProjectTeamMemberRole"."RoleRate".<br/>Table field type characteristics (type, precision, scale, length): Float, 38, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> RoleRate
		{
			get { return (Nullable<System.Double>)GetValue((int)AppProjectTeamMemberRoleFieldIndex.RoleRate, false); }
			set { SetValue((int)AppProjectTeamMemberRoleFieldIndex.RoleRate, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppProjectTeamMemberRole<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppProjectTeamMemberRole"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppProjectTeamMemberRoleFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppProjectTeamMemberRoleFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppProjectTeamMemberRole<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppProjectTeamMemberRole"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppProjectTeamMemberRoleFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppProjectTeamMemberRoleFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppProjectTeamMemberRole<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppProjectTeamMemberRole"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppProjectTeamMemberRoleFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppProjectTeamMemberRoleFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppProjectTeamMemberRole<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppProjectTeamMemberRole"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppProjectTeamMemberRoleFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppProjectTeamMemberRoleFieldIndex.AppModifiedById, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppProjectTeamMemberRole<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppProjectTeamMemberRole"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppProjectTeamMemberRoleFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppProjectTeamMemberRoleFieldIndex.AppCreatedByCompanyId, value); }
		}

		/// <summary>Gets / sets related entity of type 'AppProjectRoleEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppProjectRoleEntity AppProjectRole
		{
			get { return _appProjectRole; }
			set { SetSingleRelatedEntityNavigator(value, "AppProjectRole"); }
		}

		/// <summary>Gets / sets related entity of type 'AppProjectTeamMemberEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppProjectTeamMemberEntity AppProjectTeamMember
		{
			get { return _appProjectTeamMember; }
			set { SetSingleRelatedEntityNavigator(value, "AppProjectTeamMember"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppProjectTeamMemberRoleFieldIndex
	{
		///<summary>TeamMemberRoleId. </summary>
		TeamMemberRoleId,
		///<summary>TeamMemberId. </summary>
		TeamMemberId,
		///<summary>ProjectRoleId. </summary>
		ProjectRoleId,
		///<summary>RoleRate. </summary>
		RoleRate,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppProjectTeamMemberRole. </summary>
	public partial class AppProjectTeamMemberRoleRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between AppProjectTeamMemberRoleEntity and AppProjectRoleEntity over the m:1 relation they have, using the relation between the fields: AppProjectTeamMemberRole.ProjectRoleId - AppProjectRole.ProjectRoleId</summary>
		public virtual IEntityRelation AppProjectRoleEntityUsingProjectRoleId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppProjectRole", false, new[] { AppProjectRoleFields.ProjectRoleId, AppProjectTeamMemberRoleFields.ProjectRoleId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppProjectTeamMemberRoleEntity and AppProjectTeamMemberEntity over the m:1 relation they have, using the relation between the fields: AppProjectTeamMemberRole.TeamMemberId - AppProjectTeamMember.TeamMemberId</summary>
		public virtual IEntityRelation AppProjectTeamMemberEntityUsingTeamMemberId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppProjectTeamMember", false, new[] { AppProjectTeamMemberFields.TeamMemberId, AppProjectTeamMemberRoleFields.TeamMemberId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppProjectTeamMemberRoleRelations
	{
		internal static readonly IEntityRelation AppProjectRoleEntityUsingProjectRoleIdStatic = new AppProjectTeamMemberRoleRelations().AppProjectRoleEntityUsingProjectRoleId;
		internal static readonly IEntityRelation AppProjectTeamMemberEntityUsingTeamMemberIdStatic = new AppProjectTeamMemberRoleRelations().AppProjectTeamMemberEntityUsingTeamMemberId;

		/// <summary>CTor</summary>
		static StaticAppProjectTeamMemberRoleRelations() { }
	}
}
