//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:17 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppSearchSavedValue'.<br/><br/></summary>
	[Serializable]
	public partial class AppSearchSavedValueEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private AppSearchFieldEntity _appSearchField;
		private AppSearchSavedEntity _appSearchSaved;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppSearchSavedValueEntityStaticMetaData _staticMetaData = new AppSearchSavedValueEntityStaticMetaData();
		private static AppSearchSavedValueRelations _relationsFactory = new AppSearchSavedValueRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppSearchField</summary>
			public static readonly string AppSearchField = "AppSearchField";
			/// <summary>Member name AppSearchSaved</summary>
			public static readonly string AppSearchSaved = "AppSearchSaved";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppSearchSavedValueEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppSearchSavedValueEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppSearchSavedValueEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppSearchSavedValueEntity, typeof(AppSearchSavedValueEntity), typeof(AppSearchSavedValueEntityFactory), false);
				AddNavigatorMetaData<AppSearchSavedValueEntity, AppSearchFieldEntity>("AppSearchField", "AppSearchSavedValue", (a, b) => a._appSearchField = b, a => a._appSearchField, (a, b) => a.AppSearchField = b, APP.LBL.RelationClasses.StaticAppSearchSavedValueRelations.AppSearchFieldEntityUsingSearchFieldIdStatic, ()=>new AppSearchSavedValueRelations().AppSearchFieldEntityUsingSearchFieldId, null, new int[] { (int)AppSearchSavedValueFieldIndex.SearchFieldId }, null, true, (int)APP.LBL.EntityType.AppSearchFieldEntity);
				AddNavigatorMetaData<AppSearchSavedValueEntity, AppSearchSavedEntity>("AppSearchSaved", "AppSearchSavedValue", (a, b) => a._appSearchSaved = b, a => a._appSearchSaved, (a, b) => a.AppSearchSaved = b, APP.LBL.RelationClasses.StaticAppSearchSavedValueRelations.AppSearchSavedEntityUsingSearchSavedIdStatic, ()=>new AppSearchSavedValueRelations().AppSearchSavedEntityUsingSearchSavedId, null, new int[] { (int)AppSearchSavedValueFieldIndex.SearchSavedId }, null, true, (int)APP.LBL.EntityType.AppSearchSavedEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppSearchSavedValueEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppSearchSavedValueEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppSearchSavedValueEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppSearchSavedValueEntity</param>
		public AppSearchSavedValueEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="searchSavedValueId">PK value for AppSearchSavedValue which data should be fetched into this AppSearchSavedValue object</param>
		public AppSearchSavedValueEntity(System.Int32 searchSavedValueId) : this(searchSavedValueId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="searchSavedValueId">PK value for AppSearchSavedValue which data should be fetched into this AppSearchSavedValue object</param>
		/// <param name="validator">The custom validator object for this AppSearchSavedValueEntity</param>
		public AppSearchSavedValueEntity(System.Int32 searchSavedValueId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.SearchSavedValueId = searchSavedValueId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppSearchSavedValueEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppSearchField' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSearchField() { return CreateRelationInfoForNavigator("AppSearchField"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppSearchSaved' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSearchSaved() { return CreateRelationInfoForNavigator("AppSearchSaved"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppSearchSavedValueEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppSearchSavedValueRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSearchField' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSearchField { get { return _staticMetaData.GetPrefetchPathElement("AppSearchField", CommonEntityBase.CreateEntityCollection<AppSearchFieldEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSearchSaved' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSearchSaved { get { return _staticMetaData.GetPrefetchPathElement("AppSearchSaved", CommonEntityBase.CreateEntityCollection<AppSearchSavedEntity>()); } }

		/// <summary>The SearchSavedValueId property of the Entity AppSearchSavedValue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSavedValue"."SearchSavedValueID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 SearchSavedValueId
		{
			get { return (System.Int32)GetValue((int)AppSearchSavedValueFieldIndex.SearchSavedValueId, true); }
			set { SetValue((int)AppSearchSavedValueFieldIndex.SearchSavedValueId, value); }
		}

		/// <summary>The SearchSavedId property of the Entity AppSearchSavedValue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSavedValue"."SearchSavedID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 SearchSavedId
		{
			get { return (System.Int32)GetValue((int)AppSearchSavedValueFieldIndex.SearchSavedId, true); }
			set { SetValue((int)AppSearchSavedValueFieldIndex.SearchSavedId, value); }
		}

		/// <summary>The SearchFieldId property of the Entity AppSearchSavedValue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSavedValue"."SearchFieldID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 SearchFieldId
		{
			get { return (System.Int32)GetValue((int)AppSearchSavedValueFieldIndex.SearchFieldId, true); }
			set { SetValue((int)AppSearchSavedValueFieldIndex.SearchFieldId, value); }
		}

		/// <summary>The SearchValue property of the Entity AppSearchSavedValue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSavedValue"."SearchValue".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 1000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String SearchValue
		{
			get { return (System.String)GetValue((int)AppSearchSavedValueFieldIndex.SearchValue, true); }
			set { SetValue((int)AppSearchSavedValueFieldIndex.SearchValue, value); }
		}

		/// <summary>The OperationId property of the Entity AppSearchSavedValue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSavedValue"."OperationID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> OperationId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppSearchSavedValueFieldIndex.OperationId, false); }
			set { SetValue((int)AppSearchSavedValueFieldIndex.OperationId, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppSearchSavedValue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSavedValue"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppSearchSavedValueFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppSearchSavedValueFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppSearchSavedValue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSavedValue"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppSearchSavedValueFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppSearchSavedValueFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppSearchSavedValue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSavedValue"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppSearchSavedValueFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppSearchSavedValueFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppSearchSavedValue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSavedValue"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppSearchSavedValueFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppSearchSavedValueFieldIndex.AppModifiedById, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppSearchSavedValue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSavedValue"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppSearchSavedValueFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppSearchSavedValueFieldIndex.AppCreatedByCompanyId, value); }
		}

		/// <summary>Gets / sets related entity of type 'AppSearchFieldEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppSearchFieldEntity AppSearchField
		{
			get { return _appSearchField; }
			set { SetSingleRelatedEntityNavigator(value, "AppSearchField"); }
		}

		/// <summary>Gets / sets related entity of type 'AppSearchSavedEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppSearchSavedEntity AppSearchSaved
		{
			get { return _appSearchSaved; }
			set { SetSingleRelatedEntityNavigator(value, "AppSearchSaved"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppSearchSavedValueFieldIndex
	{
		///<summary>SearchSavedValueId. </summary>
		SearchSavedValueId,
		///<summary>SearchSavedId. </summary>
		SearchSavedId,
		///<summary>SearchFieldId. </summary>
		SearchFieldId,
		///<summary>SearchValue. </summary>
		SearchValue,
		///<summary>OperationId. </summary>
		OperationId,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppSearchSavedValue. </summary>
	public partial class AppSearchSavedValueRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between AppSearchSavedValueEntity and AppSearchFieldEntity over the m:1 relation they have, using the relation between the fields: AppSearchSavedValue.SearchFieldId - AppSearchField.SearchFielDid</summary>
		public virtual IEntityRelation AppSearchFieldEntityUsingSearchFieldId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppSearchField", false, new[] { AppSearchFieldFields.SearchFielDid, AppSearchSavedValueFields.SearchFieldId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppSearchSavedValueEntity and AppSearchSavedEntity over the m:1 relation they have, using the relation between the fields: AppSearchSavedValue.SearchSavedId - AppSearchSaved.SearchSavedId</summary>
		public virtual IEntityRelation AppSearchSavedEntityUsingSearchSavedId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppSearchSaved", false, new[] { AppSearchSavedFields.SearchSavedId, AppSearchSavedValueFields.SearchSavedId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppSearchSavedValueRelations
	{
		internal static readonly IEntityRelation AppSearchFieldEntityUsingSearchFieldIdStatic = new AppSearchSavedValueRelations().AppSearchFieldEntityUsingSearchFieldId;
		internal static readonly IEntityRelation AppSearchSavedEntityUsingSearchSavedIdStatic = new AppSearchSavedValueRelations().AppSearchSavedEntityUsingSearchSavedId;

		/// <summary>CTor</summary>
		static StaticAppSearchSavedValueRelations() { }
	}
}
