//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:17 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppSecurityUserSession'.<br/><br/></summary>
	[Serializable]
	public partial class AppSecurityUserSessionEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private AppSecurityUserEntity _appSecurityUser;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppSecurityUserSessionEntityStaticMetaData _staticMetaData = new AppSecurityUserSessionEntityStaticMetaData();
		private static AppSecurityUserSessionRelations _relationsFactory = new AppSecurityUserSessionRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppSecurityUser</summary>
			public static readonly string AppSecurityUser = "AppSecurityUser";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppSecurityUserSessionEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppSecurityUserSessionEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppSecurityUserSessionEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppSecurityUserSessionEntity, typeof(AppSecurityUserSessionEntity), typeof(AppSecurityUserSessionEntityFactory), false);
				AddNavigatorMetaData<AppSecurityUserSessionEntity, AppSecurityUserEntity>("AppSecurityUser", "AppSecurityUserSession", (a, b) => a._appSecurityUser = b, a => a._appSecurityUser, (a, b) => a.AppSecurityUser = b, APP.LBL.RelationClasses.StaticAppSecurityUserSessionRelations.AppSecurityUserEntityUsingUserIdStatic, ()=>new AppSecurityUserSessionRelations().AppSecurityUserEntityUsingUserId, null, new int[] { (int)AppSecurityUserSessionFieldIndex.UserId }, null, true, (int)APP.LBL.EntityType.AppSecurityUserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppSecurityUserSessionEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppSecurityUserSessionEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppSecurityUserSessionEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppSecurityUserSessionEntity</param>
		public AppSecurityUserSessionEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="userSessionId">PK value for AppSecurityUserSession which data should be fetched into this AppSecurityUserSession object</param>
		public AppSecurityUserSessionEntity(System.Int32 userSessionId) : this(userSessionId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="userSessionId">PK value for AppSecurityUserSession which data should be fetched into this AppSecurityUserSession object</param>
		/// <param name="validator">The custom validator object for this AppSecurityUserSessionEntity</param>
		public AppSecurityUserSessionEntity(System.Int32 userSessionId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.UserSessionId = userSessionId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppSecurityUserSessionEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppSecurityUser' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSecurityUser() { return CreateRelationInfoForNavigator("AppSecurityUser"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppSecurityUserSessionEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppSecurityUserSessionRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSecurityUser' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSecurityUser { get { return _staticMetaData.GetPrefetchPathElement("AppSecurityUser", CommonEntityBase.CreateEntityCollection<AppSecurityUserEntity>()); } }

		/// <summary>The UserSessionId property of the Entity AppSecurityUserSession<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityUserSession"."UserSessionID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 UserSessionId
		{
			get { return (System.Int32)GetValue((int)AppSecurityUserSessionFieldIndex.UserSessionId, true); }
			set { SetValue((int)AppSecurityUserSessionFieldIndex.UserSessionId, value); }
		}

		/// <summary>The UserId property of the Entity AppSecurityUserSession<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityUserSession"."UserID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 UserId
		{
			get { return (System.Int32)GetValue((int)AppSecurityUserSessionFieldIndex.UserId, true); }
			set { SetValue((int)AppSecurityUserSessionFieldIndex.UserId, value); }
		}

		/// <summary>The ExpirationDate property of the Entity AppSecurityUserSession<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityUserSession"."ExpirationDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime ExpirationDate
		{
			get { return (System.DateTime)GetValue((int)AppSecurityUserSessionFieldIndex.ExpirationDate, true); }
			set { SetValue((int)AppSecurityUserSessionFieldIndex.ExpirationDate, value); }
		}

		/// <summary>The SessionId property of the Entity AppSecurityUserSession<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityUserSession"."SessionID".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String SessionId
		{
			get { return (System.String)GetValue((int)AppSecurityUserSessionFieldIndex.SessionId, true); }
			set { SetValue((int)AppSecurityUserSessionFieldIndex.SessionId, value); }
		}

		/// <summary>The ApplicationType property of the Entity AppSecurityUserSession<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityUserSession"."ApplicationType".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 ApplicationType
		{
			get { return (System.Int32)GetValue((int)AppSecurityUserSessionFieldIndex.ApplicationType, true); }
			set { SetValue((int)AppSecurityUserSessionFieldIndex.ApplicationType, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppSecurityUserSession<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityUserSession"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppSecurityUserSessionFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppSecurityUserSessionFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppSecurityUserSession<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityUserSession"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppSecurityUserSessionFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppSecurityUserSessionFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppSecurityUserSession<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityUserSession"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppSecurityUserSessionFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppSecurityUserSessionFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppSecurityUserSession<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityUserSession"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppSecurityUserSessionFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppSecurityUserSessionFieldIndex.AppModifiedById, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppSecurityUserSession<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityUserSession"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppSecurityUserSessionFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppSecurityUserSessionFieldIndex.AppCreatedByCompanyId, value); }
		}

		/// <summary>The EmExternalSigninType property of the Entity AppSecurityUserSession<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityUserSession"."EmExternalSigninType".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> EmExternalSigninType
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppSecurityUserSessionFieldIndex.EmExternalSigninType, false); }
			set { SetValue((int)AppSecurityUserSessionFieldIndex.EmExternalSigninType, value); }
		}

		/// <summary>The ExternalAcessToken property of the Entity AppSecurityUserSession<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityUserSession"."ExternalAcessToken".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 4000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ExternalAcessToken
		{
			get { return (System.String)GetValue((int)AppSecurityUserSessionFieldIndex.ExternalAcessToken, true); }
			set { SetValue((int)AppSecurityUserSessionFieldIndex.ExternalAcessToken, value); }
		}

		/// <summary>Gets / sets related entity of type 'AppSecurityUserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppSecurityUserEntity AppSecurityUser
		{
			get { return _appSecurityUser; }
			set { SetSingleRelatedEntityNavigator(value, "AppSecurityUser"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppSecurityUserSessionFieldIndex
	{
		///<summary>UserSessionId. </summary>
		UserSessionId,
		///<summary>UserId. </summary>
		UserId,
		///<summary>ExpirationDate. </summary>
		ExpirationDate,
		///<summary>SessionId. </summary>
		SessionId,
		///<summary>ApplicationType. </summary>
		ApplicationType,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		///<summary>EmExternalSigninType. </summary>
		EmExternalSigninType,
		///<summary>ExternalAcessToken. </summary>
		ExternalAcessToken,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppSecurityUserSession. </summary>
	public partial class AppSecurityUserSessionRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between AppSecurityUserSessionEntity and AppSecurityUserEntity over the m:1 relation they have, using the relation between the fields: AppSecurityUserSession.UserId - AppSecurityUser.UserId</summary>
		public virtual IEntityRelation AppSecurityUserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppSecurityUser", false, new[] { AppSecurityUserFields.UserId, AppSecurityUserSessionFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppSecurityUserSessionRelations
	{
		internal static readonly IEntityRelation AppSecurityUserEntityUsingUserIdStatic = new AppSecurityUserSessionRelations().AppSecurityUserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticAppSecurityUserSessionRelations() { }
	}
}
