//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:17 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppSearchSaved'.<br/><br/></summary>
	[Serializable]
	public partial class AppSearchSavedEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<AppSearchSavedValueEntity> _appSearchSavedValue;
		private EntityCollection<AppTransactionUnitLinkedSearchEntity> _appTransactionUnitLinkedSearch;
		private AppSearchEntity _appSearch;
		private AppSearchViewEntity _appSearchView;
		private AppSecurityGroupEntity _appSecurityGroup;
		private AppSecurityUserEntity _appSecurityUser;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppSearchSavedEntityStaticMetaData _staticMetaData = new AppSearchSavedEntityStaticMetaData();
		private static AppSearchSavedRelations _relationsFactory = new AppSearchSavedRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppSearch</summary>
			public static readonly string AppSearch = "AppSearch";
			/// <summary>Member name AppSearchView</summary>
			public static readonly string AppSearchView = "AppSearchView";
			/// <summary>Member name AppSecurityGroup</summary>
			public static readonly string AppSecurityGroup = "AppSecurityGroup";
			/// <summary>Member name AppSecurityUser</summary>
			public static readonly string AppSecurityUser = "AppSecurityUser";
			/// <summary>Member name AppSearchSavedValue</summary>
			public static readonly string AppSearchSavedValue = "AppSearchSavedValue";
			/// <summary>Member name AppTransactionUnitLinkedSearch</summary>
			public static readonly string AppTransactionUnitLinkedSearch = "AppTransactionUnitLinkedSearch";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppSearchSavedEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppSearchSavedEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppSearchSavedEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppSearchSavedEntity, typeof(AppSearchSavedEntity), typeof(AppSearchSavedEntityFactory), false);
				AddNavigatorMetaData<AppSearchSavedEntity, EntityCollection<AppSearchSavedValueEntity>>("AppSearchSavedValue", a => a._appSearchSavedValue, (a, b) => a._appSearchSavedValue = b, a => a.AppSearchSavedValue, () => new AppSearchSavedRelations().AppSearchSavedValueEntityUsingSearchSavedId, typeof(AppSearchSavedValueEntity), (int)APP.LBL.EntityType.AppSearchSavedValueEntity);
				AddNavigatorMetaData<AppSearchSavedEntity, EntityCollection<AppTransactionUnitLinkedSearchEntity>>("AppTransactionUnitLinkedSearch", a => a._appTransactionUnitLinkedSearch, (a, b) => a._appTransactionUnitLinkedSearch = b, a => a.AppTransactionUnitLinkedSearch, () => new AppSearchSavedRelations().AppTransactionUnitLinkedSearchEntityUsingSearchSaveId, typeof(AppTransactionUnitLinkedSearchEntity), (int)APP.LBL.EntityType.AppTransactionUnitLinkedSearchEntity);
				AddNavigatorMetaData<AppSearchSavedEntity, AppSearchEntity>("AppSearch", "AppSearchSaved", (a, b) => a._appSearch = b, a => a._appSearch, (a, b) => a.AppSearch = b, APP.LBL.RelationClasses.StaticAppSearchSavedRelations.AppSearchEntityUsingSearchIdStatic, ()=>new AppSearchSavedRelations().AppSearchEntityUsingSearchId, null, new int[] { (int)AppSearchSavedFieldIndex.SearchId }, null, true, (int)APP.LBL.EntityType.AppSearchEntity);
				AddNavigatorMetaData<AppSearchSavedEntity, AppSearchViewEntity>("AppSearchView", "AppSearchSaved", (a, b) => a._appSearchView = b, a => a._appSearchView, (a, b) => a.AppSearchView = b, APP.LBL.RelationClasses.StaticAppSearchSavedRelations.AppSearchViewEntityUsingDefaultSearchViewIdStatic, ()=>new AppSearchSavedRelations().AppSearchViewEntityUsingDefaultSearchViewId, null, new int[] { (int)AppSearchSavedFieldIndex.DefaultSearchViewId }, null, true, (int)APP.LBL.EntityType.AppSearchViewEntity);
				AddNavigatorMetaData<AppSearchSavedEntity, AppSecurityGroupEntity>("AppSecurityGroup", "AppSearchSaved", (a, b) => a._appSecurityGroup = b, a => a._appSecurityGroup, (a, b) => a.AppSecurityGroup = b, APP.LBL.RelationClasses.StaticAppSearchSavedRelations.AppSecurityGroupEntityUsingGroupIdStatic, ()=>new AppSearchSavedRelations().AppSecurityGroupEntityUsingGroupId, null, new int[] { (int)AppSearchSavedFieldIndex.GroupId }, null, true, (int)APP.LBL.EntityType.AppSecurityGroupEntity);
				AddNavigatorMetaData<AppSearchSavedEntity, AppSecurityUserEntity>("AppSecurityUser", "AppSearchSaved", (a, b) => a._appSecurityUser = b, a => a._appSecurityUser, (a, b) => a.AppSecurityUser = b, APP.LBL.RelationClasses.StaticAppSearchSavedRelations.AppSecurityUserEntityUsingUserIdStatic, ()=>new AppSearchSavedRelations().AppSecurityUserEntityUsingUserId, null, new int[] { (int)AppSearchSavedFieldIndex.UserId }, null, true, (int)APP.LBL.EntityType.AppSecurityUserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppSearchSavedEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppSearchSavedEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppSearchSavedEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppSearchSavedEntity</param>
		public AppSearchSavedEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="searchSavedId">PK value for AppSearchSaved which data should be fetched into this AppSearchSaved object</param>
		public AppSearchSavedEntity(System.Int32 searchSavedId) : this(searchSavedId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="searchSavedId">PK value for AppSearchSaved which data should be fetched into this AppSearchSaved object</param>
		/// <param name="validator">The custom validator object for this AppSearchSavedEntity</param>
		public AppSearchSavedEntity(System.Int32 searchSavedId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.SearchSavedId = searchSavedId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppSearchSavedEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppSearchSavedValue' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSearchSavedValue() { return CreateRelationInfoForNavigator("AppSearchSavedValue"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppTransactionUnitLinkedSearch' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppTransactionUnitLinkedSearch() { return CreateRelationInfoForNavigator("AppTransactionUnitLinkedSearch"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppSearch' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSearch() { return CreateRelationInfoForNavigator("AppSearch"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppSearchView' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSearchView() { return CreateRelationInfoForNavigator("AppSearchView"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppSecurityGroup' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSecurityGroup() { return CreateRelationInfoForNavigator("AppSecurityGroup"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppSecurityUser' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSecurityUser() { return CreateRelationInfoForNavigator("AppSecurityUser"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppSearchSavedEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppSearchSavedRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSearchSavedValue' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSearchSavedValue { get { return _staticMetaData.GetPrefetchPathElement("AppSearchSavedValue", CommonEntityBase.CreateEntityCollection<AppSearchSavedValueEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppTransactionUnitLinkedSearch' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppTransactionUnitLinkedSearch { get { return _staticMetaData.GetPrefetchPathElement("AppTransactionUnitLinkedSearch", CommonEntityBase.CreateEntityCollection<AppTransactionUnitLinkedSearchEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSearch' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSearch { get { return _staticMetaData.GetPrefetchPathElement("AppSearch", CommonEntityBase.CreateEntityCollection<AppSearchEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSearchView' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSearchView { get { return _staticMetaData.GetPrefetchPathElement("AppSearchView", CommonEntityBase.CreateEntityCollection<AppSearchViewEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSecurityGroup' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSecurityGroup { get { return _staticMetaData.GetPrefetchPathElement("AppSecurityGroup", CommonEntityBase.CreateEntityCollection<AppSecurityGroupEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSecurityUser' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSecurityUser { get { return _staticMetaData.GetPrefetchPathElement("AppSecurityUser", CommonEntityBase.CreateEntityCollection<AppSecurityUserEntity>()); } }

		/// <summary>The SearchSavedId property of the Entity AppSearchSaved<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSaved"."SearchSavedID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 SearchSavedId
		{
			get { return (System.Int32)GetValue((int)AppSearchSavedFieldIndex.SearchSavedId, true); }
			set { SetValue((int)AppSearchSavedFieldIndex.SearchSavedId, value); }
		}

		/// <summary>The SearchId property of the Entity AppSearchSaved<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSaved"."SearchID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 SearchId
		{
			get { return (System.Int32)GetValue((int)AppSearchSavedFieldIndex.SearchId, true); }
			set { SetValue((int)AppSearchSavedFieldIndex.SearchId, value); }
		}

		/// <summary>The SavedSearchName property of the Entity AppSearchSaved<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSaved"."SavedSearchName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String SavedSearchName
		{
			get { return (System.String)GetValue((int)AppSearchSavedFieldIndex.SavedSearchName, true); }
			set { SetValue((int)AppSearchSavedFieldIndex.SavedSearchName, value); }
		}

		/// <summary>The UserId property of the Entity AppSearchSaved<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSaved"."UserID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 UserId
		{
			get { return (System.Int32)GetValue((int)AppSearchSavedFieldIndex.UserId, true); }
			set { SetValue((int)AppSearchSavedFieldIndex.UserId, value); }
		}

		/// <summary>The SystemTimeStamp property of the Entity AppSearchSaved<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSaved"."SystemTimeStamp".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Byte[] SystemTimeStamp
		{
			get { return (System.Byte[])GetValue((int)AppSearchSavedFieldIndex.SystemTimeStamp, true); }

		}

		/// <summary>The IsDefault property of the Entity AppSearchSaved<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSaved"."IsDefault".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IsDefault
		{
			get { return (Nullable<System.Boolean>)GetValue((int)AppSearchSavedFieldIndex.IsDefault, false); }
			set { SetValue((int)AppSearchSavedFieldIndex.IsDefault, value); }
		}

		/// <summary>The IsAutoExecute property of the Entity AppSearchSaved<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSaved"."IsAutoExecute".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IsAutoExecute
		{
			get { return (Nullable<System.Boolean>)GetValue((int)AppSearchSavedFieldIndex.IsAutoExecute, false); }
			set { SetValue((int)AppSearchSavedFieldIndex.IsAutoExecute, value); }
		}

		/// <summary>The GroupId property of the Entity AppSearchSaved<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSaved"."GroupID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> GroupId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppSearchSavedFieldIndex.GroupId, false); }
			set { SetValue((int)AppSearchSavedFieldIndex.GroupId, value); }
		}

		/// <summary>The DefaultSearchViewId property of the Entity AppSearchSaved<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSaved"."DefaultSearchViewID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> DefaultSearchViewId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppSearchSavedFieldIndex.DefaultSearchViewId, false); }
			set { SetValue((int)AppSearchSavedFieldIndex.DefaultSearchViewId, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppSearchSaved<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSaved"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppSearchSavedFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppSearchSavedFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppSearchSaved<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSaved"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppSearchSavedFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppSearchSavedFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppSearchSaved<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSaved"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppSearchSavedFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppSearchSavedFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppSearchSaved<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSaved"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppSearchSavedFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppSearchSavedFieldIndex.AppModifiedById, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppSearchSaved<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSearchSaved"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppSearchSavedFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppSearchSavedFieldIndex.AppCreatedByCompanyId, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'AppSearchSavedValueEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppSearchSavedValueEntity))]
		public virtual EntityCollection<AppSearchSavedValueEntity> AppSearchSavedValue { get { return GetOrCreateEntityCollection<AppSearchSavedValueEntity, AppSearchSavedValueEntityFactory>("AppSearchSaved", true, false, ref _appSearchSavedValue); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppTransactionUnitLinkedSearchEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppTransactionUnitLinkedSearchEntity))]
		public virtual EntityCollection<AppTransactionUnitLinkedSearchEntity> AppTransactionUnitLinkedSearch { get { return GetOrCreateEntityCollection<AppTransactionUnitLinkedSearchEntity, AppTransactionUnitLinkedSearchEntityFactory>("AppSearchSaved", true, false, ref _appTransactionUnitLinkedSearch); } }

		/// <summary>Gets / sets related entity of type 'AppSearchEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppSearchEntity AppSearch
		{
			get { return _appSearch; }
			set { SetSingleRelatedEntityNavigator(value, "AppSearch"); }
		}

		/// <summary>Gets / sets related entity of type 'AppSearchViewEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppSearchViewEntity AppSearchView
		{
			get { return _appSearchView; }
			set { SetSingleRelatedEntityNavigator(value, "AppSearchView"); }
		}

		/// <summary>Gets / sets related entity of type 'AppSecurityGroupEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppSecurityGroupEntity AppSecurityGroup
		{
			get { return _appSecurityGroup; }
			set { SetSingleRelatedEntityNavigator(value, "AppSecurityGroup"); }
		}

		/// <summary>Gets / sets related entity of type 'AppSecurityUserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppSecurityUserEntity AppSecurityUser
		{
			get { return _appSecurityUser; }
			set { SetSingleRelatedEntityNavigator(value, "AppSecurityUser"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppSearchSavedFieldIndex
	{
		///<summary>SearchSavedId. </summary>
		SearchSavedId,
		///<summary>SearchId. </summary>
		SearchId,
		///<summary>SavedSearchName. </summary>
		SavedSearchName,
		///<summary>UserId. </summary>
		UserId,
		///<summary>SystemTimeStamp. </summary>
		SystemTimeStamp,
		///<summary>IsDefault. </summary>
		IsDefault,
		///<summary>IsAutoExecute. </summary>
		IsAutoExecute,
		///<summary>GroupId. </summary>
		GroupId,
		///<summary>DefaultSearchViewId. </summary>
		DefaultSearchViewId,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppSearchSaved. </summary>
	public partial class AppSearchSavedRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between AppSearchSavedEntity and AppSearchSavedValueEntity over the 1:n relation they have, using the relation between the fields: AppSearchSaved.SearchSavedId - AppSearchSavedValue.SearchSavedId</summary>
		public virtual IEntityRelation AppSearchSavedValueEntityUsingSearchSavedId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppSearchSavedValue", true, new[] { AppSearchSavedFields.SearchSavedId, AppSearchSavedValueFields.SearchSavedId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppSearchSavedEntity and AppTransactionUnitLinkedSearchEntity over the 1:n relation they have, using the relation between the fields: AppSearchSaved.SearchSavedId - AppTransactionUnitLinkedSearch.SearchSaveId</summary>
		public virtual IEntityRelation AppTransactionUnitLinkedSearchEntityUsingSearchSaveId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppTransactionUnitLinkedSearch", true, new[] { AppSearchSavedFields.SearchSavedId, AppTransactionUnitLinkedSearchFields.SearchSaveId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppSearchSavedEntity and AppSearchEntity over the m:1 relation they have, using the relation between the fields: AppSearchSaved.SearchId - AppSearch.SearchId</summary>
		public virtual IEntityRelation AppSearchEntityUsingSearchId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppSearch", false, new[] { AppSearchFields.SearchId, AppSearchSavedFields.SearchId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppSearchSavedEntity and AppSearchViewEntity over the m:1 relation they have, using the relation between the fields: AppSearchSaved.DefaultSearchViewId - AppSearchView.SearchViewId</summary>
		public virtual IEntityRelation AppSearchViewEntityUsingDefaultSearchViewId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppSearchView", false, new[] { AppSearchViewFields.SearchViewId, AppSearchSavedFields.DefaultSearchViewId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppSearchSavedEntity and AppSecurityGroupEntity over the m:1 relation they have, using the relation between the fields: AppSearchSaved.GroupId - AppSecurityGroup.GroupId</summary>
		public virtual IEntityRelation AppSecurityGroupEntityUsingGroupId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppSecurityGroup", false, new[] { AppSecurityGroupFields.GroupId, AppSearchSavedFields.GroupId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppSearchSavedEntity and AppSecurityUserEntity over the m:1 relation they have, using the relation between the fields: AppSearchSaved.UserId - AppSecurityUser.UserId</summary>
		public virtual IEntityRelation AppSecurityUserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppSecurityUser", false, new[] { AppSecurityUserFields.UserId, AppSearchSavedFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppSearchSavedRelations
	{
		internal static readonly IEntityRelation AppSearchSavedValueEntityUsingSearchSavedIdStatic = new AppSearchSavedRelations().AppSearchSavedValueEntityUsingSearchSavedId;
		internal static readonly IEntityRelation AppTransactionUnitLinkedSearchEntityUsingSearchSaveIdStatic = new AppSearchSavedRelations().AppTransactionUnitLinkedSearchEntityUsingSearchSaveId;
		internal static readonly IEntityRelation AppSearchEntityUsingSearchIdStatic = new AppSearchSavedRelations().AppSearchEntityUsingSearchId;
		internal static readonly IEntityRelation AppSearchViewEntityUsingDefaultSearchViewIdStatic = new AppSearchSavedRelations().AppSearchViewEntityUsingDefaultSearchViewId;
		internal static readonly IEntityRelation AppSecurityGroupEntityUsingGroupIdStatic = new AppSearchSavedRelations().AppSecurityGroupEntityUsingGroupId;
		internal static readonly IEntityRelation AppSecurityUserEntityUsingUserIdStatic = new AppSearchSavedRelations().AppSecurityUserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticAppSearchSavedRelations() { }
	}
}
