//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:17 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppSecurityGroupMember'.<br/><br/></summary>
	[Serializable]
	public partial class AppSecurityGroupMemberEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private AppSecurityGroupEntity _appSecurityGroup;
		private AppSecurityUserEntity _appSecurityUser;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppSecurityGroupMemberEntityStaticMetaData _staticMetaData = new AppSecurityGroupMemberEntityStaticMetaData();
		private static AppSecurityGroupMemberRelations _relationsFactory = new AppSecurityGroupMemberRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppSecurityGroup</summary>
			public static readonly string AppSecurityGroup = "AppSecurityGroup";
			/// <summary>Member name AppSecurityUser</summary>
			public static readonly string AppSecurityUser = "AppSecurityUser";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppSecurityGroupMemberEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppSecurityGroupMemberEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppSecurityGroupMemberEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppSecurityGroupMemberEntity, typeof(AppSecurityGroupMemberEntity), typeof(AppSecurityGroupMemberEntityFactory), false);
				AddNavigatorMetaData<AppSecurityGroupMemberEntity, AppSecurityGroupEntity>("AppSecurityGroup", "AppSecurityGroupMember", (a, b) => a._appSecurityGroup = b, a => a._appSecurityGroup, (a, b) => a.AppSecurityGroup = b, APP.LBL.RelationClasses.StaticAppSecurityGroupMemberRelations.AppSecurityGroupEntityUsingGroupIdStatic, ()=>new AppSecurityGroupMemberRelations().AppSecurityGroupEntityUsingGroupId, null, new int[] { (int)AppSecurityGroupMemberFieldIndex.GroupId }, null, true, (int)APP.LBL.EntityType.AppSecurityGroupEntity);
				AddNavigatorMetaData<AppSecurityGroupMemberEntity, AppSecurityUserEntity>("AppSecurityUser", "AppSecurityGroupMember", (a, b) => a._appSecurityUser = b, a => a._appSecurityUser, (a, b) => a.AppSecurityUser = b, APP.LBL.RelationClasses.StaticAppSecurityGroupMemberRelations.AppSecurityUserEntityUsingUserIdStatic, ()=>new AppSecurityGroupMemberRelations().AppSecurityUserEntityUsingUserId, null, new int[] { (int)AppSecurityGroupMemberFieldIndex.UserId }, null, true, (int)APP.LBL.EntityType.AppSecurityUserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppSecurityGroupMemberEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppSecurityGroupMemberEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppSecurityGroupMemberEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppSecurityGroupMemberEntity</param>
		public AppSecurityGroupMemberEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="roleMemberId">PK value for AppSecurityGroupMember which data should be fetched into this AppSecurityGroupMember object</param>
		public AppSecurityGroupMemberEntity(System.Int32 roleMemberId) : this(roleMemberId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="roleMemberId">PK value for AppSecurityGroupMember which data should be fetched into this AppSecurityGroupMember object</param>
		/// <param name="validator">The custom validator object for this AppSecurityGroupMemberEntity</param>
		public AppSecurityGroupMemberEntity(System.Int32 roleMemberId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.RoleMemberId = roleMemberId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppSecurityGroupMemberEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppSecurityGroup' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSecurityGroup() { return CreateRelationInfoForNavigator("AppSecurityGroup"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppSecurityUser' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSecurityUser() { return CreateRelationInfoForNavigator("AppSecurityUser"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppSecurityGroupMemberEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppSecurityGroupMemberRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSecurityGroup' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSecurityGroup { get { return _staticMetaData.GetPrefetchPathElement("AppSecurityGroup", CommonEntityBase.CreateEntityCollection<AppSecurityGroupEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSecurityUser' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSecurityUser { get { return _staticMetaData.GetPrefetchPathElement("AppSecurityUser", CommonEntityBase.CreateEntityCollection<AppSecurityUserEntity>()); } }

		/// <summary>The RoleMemberId property of the Entity AppSecurityGroupMember<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityGroupMember"."RoleMemberID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 RoleMemberId
		{
			get { return (System.Int32)GetValue((int)AppSecurityGroupMemberFieldIndex.RoleMemberId, true); }
			set { SetValue((int)AppSecurityGroupMemberFieldIndex.RoleMemberId, value); }
		}

		/// <summary>The GroupId property of the Entity AppSecurityGroupMember<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityGroupMember"."GroupID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 GroupId
		{
			get { return (System.Int32)GetValue((int)AppSecurityGroupMemberFieldIndex.GroupId, true); }
			set { SetValue((int)AppSecurityGroupMemberFieldIndex.GroupId, value); }
		}

		/// <summary>The UserId property of the Entity AppSecurityGroupMember<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityGroupMember"."UserID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 UserId
		{
			get { return (System.Int32)GetValue((int)AppSecurityGroupMemberFieldIndex.UserId, true); }
			set { SetValue((int)AppSecurityGroupMemberFieldIndex.UserId, value); }
		}

		/// <summary>The IsDefault property of the Entity AppSecurityGroupMember<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityGroupMember"."IsDefault".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsDefault
		{
			get { return (System.Boolean)GetValue((int)AppSecurityGroupMemberFieldIndex.IsDefault, true); }
			set { SetValue((int)AppSecurityGroupMemberFieldIndex.IsDefault, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppSecurityGroupMember<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityGroupMember"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppSecurityGroupMemberFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppSecurityGroupMemberFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppSecurityGroupMember<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityGroupMember"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppSecurityGroupMemberFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppSecurityGroupMemberFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppSecurityGroupMember<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityGroupMember"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppSecurityGroupMemberFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppSecurityGroupMemberFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppSecurityGroupMember<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityGroupMember"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppSecurityGroupMemberFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppSecurityGroupMemberFieldIndex.AppModifiedById, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppSecurityGroupMember<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppSecurityGroupMember"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppSecurityGroupMemberFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppSecurityGroupMemberFieldIndex.AppCreatedByCompanyId, value); }
		}

		/// <summary>Gets / sets related entity of type 'AppSecurityGroupEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppSecurityGroupEntity AppSecurityGroup
		{
			get { return _appSecurityGroup; }
			set { SetSingleRelatedEntityNavigator(value, "AppSecurityGroup"); }
		}

		/// <summary>Gets / sets related entity of type 'AppSecurityUserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppSecurityUserEntity AppSecurityUser
		{
			get { return _appSecurityUser; }
			set { SetSingleRelatedEntityNavigator(value, "AppSecurityUser"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppSecurityGroupMemberFieldIndex
	{
		///<summary>RoleMemberId. </summary>
		RoleMemberId,
		///<summary>GroupId. </summary>
		GroupId,
		///<summary>UserId. </summary>
		UserId,
		///<summary>IsDefault. </summary>
		IsDefault,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppSecurityGroupMember. </summary>
	public partial class AppSecurityGroupMemberRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between AppSecurityGroupMemberEntity and AppSecurityGroupEntity over the m:1 relation they have, using the relation between the fields: AppSecurityGroupMember.GroupId - AppSecurityGroup.GroupId</summary>
		public virtual IEntityRelation AppSecurityGroupEntityUsingGroupId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppSecurityGroup", false, new[] { AppSecurityGroupFields.GroupId, AppSecurityGroupMemberFields.GroupId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppSecurityGroupMemberEntity and AppSecurityUserEntity over the m:1 relation they have, using the relation between the fields: AppSecurityGroupMember.UserId - AppSecurityUser.UserId</summary>
		public virtual IEntityRelation AppSecurityUserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppSecurityUser", false, new[] { AppSecurityUserFields.UserId, AppSecurityGroupMemberFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppSecurityGroupMemberRelations
	{
		internal static readonly IEntityRelation AppSecurityGroupEntityUsingGroupIdStatic = new AppSecurityGroupMemberRelations().AppSecurityGroupEntityUsingGroupId;
		internal static readonly IEntityRelation AppSecurityUserEntityUsingUserIdStatic = new AppSecurityGroupMemberRelations().AppSecurityUserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticAppSecurityGroupMemberRelations() { }
	}
}
