//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:17 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppTransAuditTrailLog'.<br/><br/></summary>
	[Serializable]
	public partial class AppTransAuditTrailLogEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppTransAuditTrailLogEntityStaticMetaData _staticMetaData = new AppTransAuditTrailLogEntityStaticMetaData();
		private static AppTransAuditTrailLogRelations _relationsFactory = new AppTransAuditTrailLogRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppTransAuditTrailLogEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppTransAuditTrailLogEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppTransAuditTrailLogEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppTransAuditTrailLogEntity, typeof(AppTransAuditTrailLogEntity), typeof(AppTransAuditTrailLogEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static AppTransAuditTrailLogEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppTransAuditTrailLogEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppTransAuditTrailLogEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppTransAuditTrailLogEntity</param>
		public AppTransAuditTrailLogEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="auditTrailLogId">PK value for AppTransAuditTrailLog which data should be fetched into this AppTransAuditTrailLog object</param>
		public AppTransAuditTrailLogEntity(System.Int32 auditTrailLogId) : this(auditTrailLogId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="auditTrailLogId">PK value for AppTransAuditTrailLog which data should be fetched into this AppTransAuditTrailLog object</param>
		/// <param name="validator">The custom validator object for this AppTransAuditTrailLogEntity</param>
		public AppTransAuditTrailLogEntity(System.Int32 auditTrailLogId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.AuditTrailLogId = auditTrailLogId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppTransAuditTrailLogEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppTransAuditTrailLogEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppTransAuditTrailLogRelations Relations { get { return _relationsFactory; } }

		/// <summary>The AuditTrailLogId property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."AuditTrailLogID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 AuditTrailLogId
		{
			get { return (System.Int32)GetValue((int)AppTransAuditTrailLogFieldIndex.AuditTrailLogId, true); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.AuditTrailLogId, value); }
		}

		/// <summary>The TransactionId property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."TransactionID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> TransactionId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransAuditTrailLogFieldIndex.TransactionId, false); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.TransactionId, value); }
		}

		/// <summary>The RootValueId property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."RootValueID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> RootValueId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransAuditTrailLogFieldIndex.RootValueId, false); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.RootValueId, value); }
		}

		/// <summary>The TransactionFieldId property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."TransactionFieldID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> TransactionFieldId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransAuditTrailLogFieldIndex.TransactionFieldId, false); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.TransactionFieldId, value); }
		}

		/// <summary>The RowIdentityName property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."RowIdentityName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String RowIdentityName
		{
			get { return (System.String)GetValue((int)AppTransAuditTrailLogFieldIndex.RowIdentityName, true); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.RowIdentityName, value); }
		}

		/// <summary>The TraiLogAction property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."TraiLogAction".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String TraiLogAction
		{
			get { return (System.String)GetValue((int)AppTransAuditTrailLogFieldIndex.TraiLogAction, true); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.TraiLogAction, value); }
		}

		/// <summary>The ModifiedValueBefor property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."ModifiedValueBefor".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 4000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ModifiedValueBefor
		{
			get { return (System.String)GetValue((int)AppTransAuditTrailLogFieldIndex.ModifiedValueBefor, true); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.ModifiedValueBefor, value); }
		}

		/// <summary>The ModifiedValueAfter property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."ModifiedValueAfter".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 4000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ModifiedValueAfter
		{
			get { return (System.String)GetValue((int)AppTransAuditTrailLogFieldIndex.ModifiedValueAfter, true); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.ModifiedValueAfter, value); }
		}

		/// <summary>The BatchNoId property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."BatchNoID".<br/>Table field type characteristics (type, precision, scale, length): BigInt, 19, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int64> BatchNoId
		{
			get { return (Nullable<System.Int64>)GetValue((int)AppTransAuditTrailLogFieldIndex.BatchNoId, false); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.BatchNoId, value); }
		}

		/// <summary>The UnitId property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."UnitID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> UnitId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransAuditTrailLogFieldIndex.UnitId, false); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.UnitId, value); }
		}

		/// <summary>The ChildUnitRowValueId property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."ChildUnitRowValueID".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ChildUnitRowValueId
		{
			get { return (System.String)GetValue((int)AppTransAuditTrailLogFieldIndex.ChildUnitRowValueId, true); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.ChildUnitRowValueId, value); }
		}

		/// <summary>The GrandChildUnitRowValueId property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."GrandChildUnitRowValueID".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String GrandChildUnitRowValueId
		{
			get { return (System.String)GetValue((int)AppTransAuditTrailLogFieldIndex.GrandChildUnitRowValueId, true); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.GrandChildUnitRowValueId, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransAuditTrailLogFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppTransAuditTrailLogFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppTransAuditTrailLogFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransAuditTrailLogFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.AppModifiedById, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppTransAuditTrailLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransAuditTrailLog"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransAuditTrailLogFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppTransAuditTrailLogFieldIndex.AppCreatedByCompanyId, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppTransAuditTrailLogFieldIndex
	{
		///<summary>AuditTrailLogId. </summary>
		AuditTrailLogId,
		///<summary>TransactionId. </summary>
		TransactionId,
		///<summary>RootValueId. </summary>
		RootValueId,
		///<summary>TransactionFieldId. </summary>
		TransactionFieldId,
		///<summary>RowIdentityName. </summary>
		RowIdentityName,
		///<summary>TraiLogAction. </summary>
		TraiLogAction,
		///<summary>ModifiedValueBefor. </summary>
		ModifiedValueBefor,
		///<summary>ModifiedValueAfter. </summary>
		ModifiedValueAfter,
		///<summary>BatchNoId. </summary>
		BatchNoId,
		///<summary>UnitId. </summary>
		UnitId,
		///<summary>ChildUnitRowValueId. </summary>
		ChildUnitRowValueId,
		///<summary>GrandChildUnitRowValueId. </summary>
		GrandChildUnitRowValueId,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppTransAuditTrailLog. </summary>
	public partial class AppTransAuditTrailLogRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppTransAuditTrailLogRelations
	{

		/// <summary>CTor</summary>
		static StaticAppTransAuditTrailLogRelations() { }
	}
}
