//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:17 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppTrascationRecycleBin'.<br/><br/></summary>
	[Serializable]
	public partial class AppTrascationRecycleBinEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private AppTransactionEntity _appTransaction;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppTrascationRecycleBinEntityStaticMetaData _staticMetaData = new AppTrascationRecycleBinEntityStaticMetaData();
		private static AppTrascationRecycleBinRelations _relationsFactory = new AppTrascationRecycleBinRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppTransaction</summary>
			public static readonly string AppTransaction = "AppTransaction";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppTrascationRecycleBinEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppTrascationRecycleBinEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppTrascationRecycleBinEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppTrascationRecycleBinEntity, typeof(AppTrascationRecycleBinEntity), typeof(AppTrascationRecycleBinEntityFactory), false);
				AddNavigatorMetaData<AppTrascationRecycleBinEntity, AppTransactionEntity>("AppTransaction", "AppTrascationRecycleBin", (a, b) => a._appTransaction = b, a => a._appTransaction, (a, b) => a.AppTransaction = b, APP.LBL.RelationClasses.StaticAppTrascationRecycleBinRelations.AppTransactionEntityUsingTranscationIdStatic, ()=>new AppTrascationRecycleBinRelations().AppTransactionEntityUsingTranscationId, null, new int[] { (int)AppTrascationRecycleBinFieldIndex.TranscationId }, null, true, (int)APP.LBL.EntityType.AppTransactionEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppTrascationRecycleBinEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppTrascationRecycleBinEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppTrascationRecycleBinEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppTrascationRecycleBinEntity</param>
		public AppTrascationRecycleBinEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="recycleBinId">PK value for AppTrascationRecycleBin which data should be fetched into this AppTrascationRecycleBin object</param>
		public AppTrascationRecycleBinEntity(System.Int32 recycleBinId) : this(recycleBinId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="recycleBinId">PK value for AppTrascationRecycleBin which data should be fetched into this AppTrascationRecycleBin object</param>
		/// <param name="validator">The custom validator object for this AppTrascationRecycleBinEntity</param>
		public AppTrascationRecycleBinEntity(System.Int32 recycleBinId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.RecycleBinId = recycleBinId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppTrascationRecycleBinEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppTransaction' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppTransaction() { return CreateRelationInfoForNavigator("AppTransaction"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppTrascationRecycleBinEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppTrascationRecycleBinRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppTransaction' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppTransaction { get { return _staticMetaData.GetPrefetchPathElement("AppTransaction", CommonEntityBase.CreateEntityCollection<AppTransactionEntity>()); } }

		/// <summary>The RecycleBinId property of the Entity AppTrascationRecycleBin<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTrascationRecycleBin"."RecycleBinID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 RecycleBinId
		{
			get { return (System.Int32)GetValue((int)AppTrascationRecycleBinFieldIndex.RecycleBinId, true); }
			set { SetValue((int)AppTrascationRecycleBinFieldIndex.RecycleBinId, value); }
		}

		/// <summary>The TranscationId property of the Entity AppTrascationRecycleBin<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTrascationRecycleBin"."TranscationID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> TranscationId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTrascationRecycleBinFieldIndex.TranscationId, false); }
			set { SetValue((int)AppTrascationRecycleBinFieldIndex.TranscationId, value); }
		}

		/// <summary>The RootKeyValueId property of the Entity AppTrascationRecycleBin<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTrascationRecycleBin"."RootKeyValueID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> RootKeyValueId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTrascationRecycleBinFieldIndex.RootKeyValueId, false); }
			set { SetValue((int)AppTrascationRecycleBinFieldIndex.RootKeyValueId, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppTrascationRecycleBin<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTrascationRecycleBin"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTrascationRecycleBinFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppTrascationRecycleBinFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppTrascationRecycleBin<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTrascationRecycleBin"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppTrascationRecycleBinFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppTrascationRecycleBinFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppTrascationRecycleBin<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTrascationRecycleBin"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppTrascationRecycleBinFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppTrascationRecycleBinFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppTrascationRecycleBin<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTrascationRecycleBin"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTrascationRecycleBinFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppTrascationRecycleBinFieldIndex.AppModifiedById, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppTrascationRecycleBin<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTrascationRecycleBin"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTrascationRecycleBinFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppTrascationRecycleBinFieldIndex.AppCreatedByCompanyId, value); }
		}

		/// <summary>Gets / sets related entity of type 'AppTransactionEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppTransactionEntity AppTransaction
		{
			get { return _appTransaction; }
			set { SetSingleRelatedEntityNavigator(value, "AppTransaction"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppTrascationRecycleBinFieldIndex
	{
		///<summary>RecycleBinId. </summary>
		RecycleBinId,
		///<summary>TranscationId. </summary>
		TranscationId,
		///<summary>RootKeyValueId. </summary>
		RootKeyValueId,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppTrascationRecycleBin. </summary>
	public partial class AppTrascationRecycleBinRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between AppTrascationRecycleBinEntity and AppTransactionEntity over the m:1 relation they have, using the relation between the fields: AppTrascationRecycleBin.TranscationId - AppTransaction.TransactionId</summary>
		public virtual IEntityRelation AppTransactionEntityUsingTranscationId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppTransaction", false, new[] { AppTransactionFields.TransactionId, AppTrascationRecycleBinFields.TranscationId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppTrascationRecycleBinRelations
	{
		internal static readonly IEntityRelation AppTransactionEntityUsingTranscationIdStatic = new AppTrascationRecycleBinRelations().AppTransactionEntityUsingTranscationId;

		/// <summary>CTor</summary>
		static StaticAppTrascationRecycleBinRelations() { }
	}
}
