//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:17 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppTransactionGroup'.<br/><br/></summary>
	[Serializable]
	public partial class AppTransactionGroupEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<AppTransactionGroupItemEntity> _appTransactionGroupItem;
		private EntityCollection<AppTransactionGroupSessionEntity> _appTransactionGroupSession;
		private AppBusienssAssormentNavigationEntity _appBusienssAssormentNavigation;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppTransactionGroupEntityStaticMetaData _staticMetaData = new AppTransactionGroupEntityStaticMetaData();
		private static AppTransactionGroupRelations _relationsFactory = new AppTransactionGroupRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppBusienssAssormentNavigation</summary>
			public static readonly string AppBusienssAssormentNavigation = "AppBusienssAssormentNavigation";
			/// <summary>Member name AppTransactionGroupItem</summary>
			public static readonly string AppTransactionGroupItem = "AppTransactionGroupItem";
			/// <summary>Member name AppTransactionGroupSession</summary>
			public static readonly string AppTransactionGroupSession = "AppTransactionGroupSession";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppTransactionGroupEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppTransactionGroupEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppTransactionGroupEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppTransactionGroupEntity, typeof(AppTransactionGroupEntity), typeof(AppTransactionGroupEntityFactory), false);
				AddNavigatorMetaData<AppTransactionGroupEntity, EntityCollection<AppTransactionGroupItemEntity>>("AppTransactionGroupItem", a => a._appTransactionGroupItem, (a, b) => a._appTransactionGroupItem = b, a => a.AppTransactionGroupItem, () => new AppTransactionGroupRelations().AppTransactionGroupItemEntityUsingTransactionGroupId, typeof(AppTransactionGroupItemEntity), (int)APP.LBL.EntityType.AppTransactionGroupItemEntity);
				AddNavigatorMetaData<AppTransactionGroupEntity, EntityCollection<AppTransactionGroupSessionEntity>>("AppTransactionGroupSession", a => a._appTransactionGroupSession, (a, b) => a._appTransactionGroupSession = b, a => a.AppTransactionGroupSession, () => new AppTransactionGroupRelations().AppTransactionGroupSessionEntityUsingTransactionGroupId, typeof(AppTransactionGroupSessionEntity), (int)APP.LBL.EntityType.AppTransactionGroupSessionEntity);
				AddNavigatorMetaData<AppTransactionGroupEntity, AppBusienssAssormentNavigationEntity>("AppBusienssAssormentNavigation", "AppTransactionGroup", (a, b) => a._appBusienssAssormentNavigation = b, a => a._appBusienssAssormentNavigation, (a, b) => a.AppBusienssAssormentNavigation = b, APP.LBL.RelationClasses.StaticAppTransactionGroupRelations.AppBusienssAssormentNavigationEntityUsingAssotmentnavigationIdStatic, ()=>new AppTransactionGroupRelations().AppBusienssAssormentNavigationEntityUsingAssotmentnavigationId, null, new int[] { (int)AppTransactionGroupFieldIndex.AssotmentnavigationId }, null, true, (int)APP.LBL.EntityType.AppBusienssAssormentNavigationEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppTransactionGroupEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppTransactionGroupEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppTransactionGroupEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppTransactionGroupEntity</param>
		public AppTransactionGroupEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="transactionGroupId">PK value for AppTransactionGroup which data should be fetched into this AppTransactionGroup object</param>
		public AppTransactionGroupEntity(System.Int32 transactionGroupId) : this(transactionGroupId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="transactionGroupId">PK value for AppTransactionGroup which data should be fetched into this AppTransactionGroup object</param>
		/// <param name="validator">The custom validator object for this AppTransactionGroupEntity</param>
		public AppTransactionGroupEntity(System.Int32 transactionGroupId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.TransactionGroupId = transactionGroupId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppTransactionGroupEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppTransactionGroupItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppTransactionGroupItem() { return CreateRelationInfoForNavigator("AppTransactionGroupItem"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AppTransactionGroupSession' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppTransactionGroupSession() { return CreateRelationInfoForNavigator("AppTransactionGroupSession"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppBusienssAssormentNavigation' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppBusienssAssormentNavigation() { return CreateRelationInfoForNavigator("AppBusienssAssormentNavigation"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppTransactionGroupEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppTransactionGroupRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppTransactionGroupItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppTransactionGroupItem { get { return _staticMetaData.GetPrefetchPathElement("AppTransactionGroupItem", CommonEntityBase.CreateEntityCollection<AppTransactionGroupItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppTransactionGroupSession' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppTransactionGroupSession { get { return _staticMetaData.GetPrefetchPathElement("AppTransactionGroupSession", CommonEntityBase.CreateEntityCollection<AppTransactionGroupSessionEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppBusienssAssormentNavigation' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppBusienssAssormentNavigation { get { return _staticMetaData.GetPrefetchPathElement("AppBusienssAssormentNavigation", CommonEntityBase.CreateEntityCollection<AppBusienssAssormentNavigationEntity>()); } }

		/// <summary>The TransactionGroupId property of the Entity AppTransactionGroup<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroup"."TransactionGroupID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 TransactionGroupId
		{
			get { return (System.Int32)GetValue((int)AppTransactionGroupFieldIndex.TransactionGroupId, true); }
			set { SetValue((int)AppTransactionGroupFieldIndex.TransactionGroupId, value); }
		}

		/// <summary>The AssotmentnavigationId property of the Entity AppTransactionGroup<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroup"."AssotmentnavigationID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AssotmentnavigationId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransactionGroupFieldIndex.AssotmentnavigationId, false); }
			set { SetValue((int)AppTransactionGroupFieldIndex.AssotmentnavigationId, value); }
		}

		/// <summary>The GroupName property of the Entity AppTransactionGroup<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroup"."GroupName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String GroupName
		{
			get { return (System.String)GetValue((int)AppTransactionGroupFieldIndex.GroupName, true); }
			set { SetValue((int)AppTransactionGroupFieldIndex.GroupName, value); }
		}

		/// <summary>The Description property of the Entity AppTransactionGroup<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroup"."Description".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)AppTransactionGroupFieldIndex.Description, true); }
			set { SetValue((int)AppTransactionGroupFieldIndex.Description, value); }
		}

		/// <summary>The IsDefaultGroup property of the Entity AppTransactionGroup<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroup"."IsDefaultGroup".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IsDefaultGroup
		{
			get { return (Nullable<System.Boolean>)GetValue((int)AppTransactionGroupFieldIndex.IsDefaultGroup, false); }
			set { SetValue((int)AppTransactionGroupFieldIndex.IsDefaultGroup, value); }
		}

		/// <summary>The GroupSortOrder property of the Entity AppTransactionGroup<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroup"."GroupSortOrder".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> GroupSortOrder
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransactionGroupFieldIndex.GroupSortOrder, false); }
			set { SetValue((int)AppTransactionGroupFieldIndex.GroupSortOrder, value); }
		}

		/// <summary>The EmBuseinssScope property of the Entity AppTransactionGroup<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroup"."EmBuseinssScope".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> EmBuseinssScope
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransactionGroupFieldIndex.EmBuseinssScope, false); }
			set { SetValue((int)AppTransactionGroupFieldIndex.EmBuseinssScope, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppTransactionGroup<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroup"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransactionGroupFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppTransactionGroupFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppTransactionGroup<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroup"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppTransactionGroupFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppTransactionGroupFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppTransactionGroup<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroup"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppTransactionGroupFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppTransactionGroupFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppTransactionGroup<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroup"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransactionGroupFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppTransactionGroupFieldIndex.AppModifiedById, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppTransactionGroup<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroup"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransactionGroupFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppTransactionGroupFieldIndex.AppCreatedByCompanyId, value); }
		}

		/// <summary>The SaasApplicationId property of the Entity AppTransactionGroup<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroup"."SaasApplicationID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> SaasApplicationId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransactionGroupFieldIndex.SaasApplicationId, false); }
			set { SetValue((int)AppTransactionGroupFieldIndex.SaasApplicationId, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'AppTransactionGroupItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppTransactionGroupItemEntity))]
		public virtual EntityCollection<AppTransactionGroupItemEntity> AppTransactionGroupItem { get { return GetOrCreateEntityCollection<AppTransactionGroupItemEntity, AppTransactionGroupItemEntityFactory>("AppTransactionGroup", true, false, ref _appTransactionGroupItem); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AppTransactionGroupSessionEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AppTransactionGroupSessionEntity))]
		public virtual EntityCollection<AppTransactionGroupSessionEntity> AppTransactionGroupSession { get { return GetOrCreateEntityCollection<AppTransactionGroupSessionEntity, AppTransactionGroupSessionEntityFactory>("AppTransactionGroup", true, false, ref _appTransactionGroupSession); } }

		/// <summary>Gets / sets related entity of type 'AppBusienssAssormentNavigationEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppBusienssAssormentNavigationEntity AppBusienssAssormentNavigation
		{
			get { return _appBusienssAssormentNavigation; }
			set { SetSingleRelatedEntityNavigator(value, "AppBusienssAssormentNavigation"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppTransactionGroupFieldIndex
	{
		///<summary>TransactionGroupId. </summary>
		TransactionGroupId,
		///<summary>AssotmentnavigationId. </summary>
		AssotmentnavigationId,
		///<summary>GroupName. </summary>
		GroupName,
		///<summary>Description. </summary>
		Description,
		///<summary>IsDefaultGroup. </summary>
		IsDefaultGroup,
		///<summary>GroupSortOrder. </summary>
		GroupSortOrder,
		///<summary>EmBuseinssScope. </summary>
		EmBuseinssScope,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		///<summary>SaasApplicationId. </summary>
		SaasApplicationId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppTransactionGroup. </summary>
	public partial class AppTransactionGroupRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between AppTransactionGroupEntity and AppTransactionGroupItemEntity over the 1:n relation they have, using the relation between the fields: AppTransactionGroup.TransactionGroupId - AppTransactionGroupItem.TransactionGroupId</summary>
		public virtual IEntityRelation AppTransactionGroupItemEntityUsingTransactionGroupId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppTransactionGroupItem", true, new[] { AppTransactionGroupFields.TransactionGroupId, AppTransactionGroupItemFields.TransactionGroupId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppTransactionGroupEntity and AppTransactionGroupSessionEntity over the 1:n relation they have, using the relation between the fields: AppTransactionGroup.TransactionGroupId - AppTransactionGroupSession.TransactionGroupId</summary>
		public virtual IEntityRelation AppTransactionGroupSessionEntityUsingTransactionGroupId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AppTransactionGroupSession", true, new[] { AppTransactionGroupFields.TransactionGroupId, AppTransactionGroupSessionFields.TransactionGroupId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppTransactionGroupEntity and AppBusienssAssormentNavigationEntity over the m:1 relation they have, using the relation between the fields: AppTransactionGroup.AssotmentnavigationId - AppBusienssAssormentNavigation.AssotmentnavigationId</summary>
		public virtual IEntityRelation AppBusienssAssormentNavigationEntityUsingAssotmentnavigationId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppBusienssAssormentNavigation", false, new[] { AppBusienssAssormentNavigationFields.AssotmentnavigationId, AppTransactionGroupFields.AssotmentnavigationId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppTransactionGroupRelations
	{
		internal static readonly IEntityRelation AppTransactionGroupItemEntityUsingTransactionGroupIdStatic = new AppTransactionGroupRelations().AppTransactionGroupItemEntityUsingTransactionGroupId;
		internal static readonly IEntityRelation AppTransactionGroupSessionEntityUsingTransactionGroupIdStatic = new AppTransactionGroupRelations().AppTransactionGroupSessionEntityUsingTransactionGroupId;
		internal static readonly IEntityRelation AppBusienssAssormentNavigationEntityUsingAssotmentnavigationIdStatic = new AppTransactionGroupRelations().AppBusienssAssormentNavigationEntityUsingAssotmentnavigationId;

		/// <summary>CTor</summary>
		static StaticAppTransactionGroupRelations() { }
	}
}
