//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:17 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppTransactionGroupItem'.<br/><br/></summary>
	[Serializable]
	public partial class AppTransactionGroupItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private AppTransactionGroupEntity _appTransactionGroup;
		private AppTransactionItemEntity _appTransactionItem;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppTransactionGroupItemEntityStaticMetaData _staticMetaData = new AppTransactionGroupItemEntityStaticMetaData();
		private static AppTransactionGroupItemRelations _relationsFactory = new AppTransactionGroupItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppTransactionGroup</summary>
			public static readonly string AppTransactionGroup = "AppTransactionGroup";
			/// <summary>Member name AppTransactionItem</summary>
			public static readonly string AppTransactionItem = "AppTransactionItem";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppTransactionGroupItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppTransactionGroupItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppTransactionGroupItemEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppTransactionGroupItemEntity, typeof(AppTransactionGroupItemEntity), typeof(AppTransactionGroupItemEntityFactory), false);
				AddNavigatorMetaData<AppTransactionGroupItemEntity, AppTransactionGroupEntity>("AppTransactionGroup", "AppTransactionGroupItem", (a, b) => a._appTransactionGroup = b, a => a._appTransactionGroup, (a, b) => a.AppTransactionGroup = b, APP.LBL.RelationClasses.StaticAppTransactionGroupItemRelations.AppTransactionGroupEntityUsingTransactionGroupIdStatic, ()=>new AppTransactionGroupItemRelations().AppTransactionGroupEntityUsingTransactionGroupId, null, new int[] { (int)AppTransactionGroupItemFieldIndex.TransactionGroupId }, null, true, (int)APP.LBL.EntityType.AppTransactionGroupEntity);
				AddNavigatorMetaData<AppTransactionGroupItemEntity, AppTransactionItemEntity>("AppTransactionItem", "AppTransactionGroupItem", (a, b) => a._appTransactionItem = b, a => a._appTransactionItem, (a, b) => a.AppTransactionItem = b, APP.LBL.RelationClasses.StaticAppTransactionGroupItemRelations.AppTransactionItemEntityUsingTransactionIdStatic, ()=>new AppTransactionGroupItemRelations().AppTransactionItemEntityUsingTransactionId, null, new int[] { (int)AppTransactionGroupItemFieldIndex.TransactionId }, null, true, (int)APP.LBL.EntityType.AppTransactionItemEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppTransactionGroupItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppTransactionGroupItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppTransactionGroupItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppTransactionGroupItemEntity</param>
		public AppTransactionGroupItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="groupItemId">PK value for AppTransactionGroupItem which data should be fetched into this AppTransactionGroupItem object</param>
		public AppTransactionGroupItemEntity(System.Int32 groupItemId) : this(groupItemId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="groupItemId">PK value for AppTransactionGroupItem which data should be fetched into this AppTransactionGroupItem object</param>
		/// <param name="validator">The custom validator object for this AppTransactionGroupItemEntity</param>
		public AppTransactionGroupItemEntity(System.Int32 groupItemId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.GroupItemId = groupItemId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppTransactionGroupItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppTransactionGroup' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppTransactionGroup() { return CreateRelationInfoForNavigator("AppTransactionGroup"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppTransactionItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppTransactionItem() { return CreateRelationInfoForNavigator("AppTransactionItem"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppTransactionGroupItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppTransactionGroupItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppTransactionGroup' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppTransactionGroup { get { return _staticMetaData.GetPrefetchPathElement("AppTransactionGroup", CommonEntityBase.CreateEntityCollection<AppTransactionGroupEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppTransactionItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppTransactionItem { get { return _staticMetaData.GetPrefetchPathElement("AppTransactionItem", CommonEntityBase.CreateEntityCollection<AppTransactionItemEntity>()); } }

		/// <summary>The GroupItemId property of the Entity AppTransactionGroupItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroupItem"."GroupItemID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 GroupItemId
		{
			get { return (System.Int32)GetValue((int)AppTransactionGroupItemFieldIndex.GroupItemId, true); }
			set { SetValue((int)AppTransactionGroupItemFieldIndex.GroupItemId, value); }
		}

		/// <summary>The TransactionGroupId property of the Entity AppTransactionGroupItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroupItem"."TransactionGroupID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> TransactionGroupId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransactionGroupItemFieldIndex.TransactionGroupId, false); }
			set { SetValue((int)AppTransactionGroupItemFieldIndex.TransactionGroupId, value); }
		}

		/// <summary>The TransactionId property of the Entity AppTransactionGroupItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroupItem"."TransactionItemID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> TransactionId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransactionGroupItemFieldIndex.TransactionId, false); }
			set { SetValue((int)AppTransactionGroupItemFieldIndex.TransactionId, value); }
		}

		/// <summary>The TransactionCaculationFlowOrder property of the Entity AppTransactionGroupItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroupItem"."TransactionCaculationFlowOrder".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> TransactionCaculationFlowOrder
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransactionGroupItemFieldIndex.TransactionCaculationFlowOrder, false); }
			set { SetValue((int)AppTransactionGroupItemFieldIndex.TransactionCaculationFlowOrder, value); }
		}

		/// <summary>The TransactionLayoutOrder property of the Entity AppTransactionGroupItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroupItem"."TransactionLayoutOrder".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> TransactionLayoutOrder
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransactionGroupItemFieldIndex.TransactionLayoutOrder, false); }
			set { SetValue((int)AppTransactionGroupItemFieldIndex.TransactionLayoutOrder, value); }
		}

		/// <summary>The IsGroupSharedHeader property of the Entity AppTransactionGroupItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroupItem"."IsCrossGroupSharedHeader".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IsGroupSharedHeader
		{
			get { return (Nullable<System.Boolean>)GetValue((int)AppTransactionGroupItemFieldIndex.IsGroupSharedHeader, false); }
			set { SetValue((int)AppTransactionGroupItemFieldIndex.IsGroupSharedHeader, value); }
		}

		/// <summary>The IsCrossGroupSharedHeader property of the Entity AppTransactionGroupItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroupItem"."IsGroupSharedHeader".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> IsCrossGroupSharedHeader
		{
			get { return (Nullable<System.Boolean>)GetValue((int)AppTransactionGroupItemFieldIndex.IsCrossGroupSharedHeader, false); }
			set { SetValue((int)AppTransactionGroupItemFieldIndex.IsCrossGroupSharedHeader, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppTransactionGroupItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroupItem"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransactionGroupItemFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppTransactionGroupItemFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppTransactionGroupItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroupItem"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppTransactionGroupItemFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppTransactionGroupItemFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppTransactionGroupItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroupItem"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppTransactionGroupItemFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppTransactionGroupItemFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppTransactionGroupItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroupItem"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransactionGroupItemFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppTransactionGroupItemFieldIndex.AppModifiedById, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppTransactionGroupItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppTransactionGroupItem"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppTransactionGroupItemFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppTransactionGroupItemFieldIndex.AppCreatedByCompanyId, value); }
		}

		/// <summary>Gets / sets related entity of type 'AppTransactionGroupEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppTransactionGroupEntity AppTransactionGroup
		{
			get { return _appTransactionGroup; }
			set { SetSingleRelatedEntityNavigator(value, "AppTransactionGroup"); }
		}

		/// <summary>Gets / sets related entity of type 'AppTransactionItemEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppTransactionItemEntity AppTransactionItem
		{
			get { return _appTransactionItem; }
			set { SetSingleRelatedEntityNavigator(value, "AppTransactionItem"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppTransactionGroupItemFieldIndex
	{
		///<summary>GroupItemId. </summary>
		GroupItemId,
		///<summary>TransactionGroupId. </summary>
		TransactionGroupId,
		///<summary>TransactionId. </summary>
		TransactionId,
		///<summary>TransactionCaculationFlowOrder. </summary>
		TransactionCaculationFlowOrder,
		///<summary>TransactionLayoutOrder. </summary>
		TransactionLayoutOrder,
		///<summary>IsGroupSharedHeader. </summary>
		IsGroupSharedHeader,
		///<summary>IsCrossGroupSharedHeader. </summary>
		IsCrossGroupSharedHeader,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppTransactionGroupItem. </summary>
	public partial class AppTransactionGroupItemRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between AppTransactionGroupItemEntity and AppTransactionGroupEntity over the m:1 relation they have, using the relation between the fields: AppTransactionGroupItem.TransactionGroupId - AppTransactionGroup.TransactionGroupId</summary>
		public virtual IEntityRelation AppTransactionGroupEntityUsingTransactionGroupId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppTransactionGroup", false, new[] { AppTransactionGroupFields.TransactionGroupId, AppTransactionGroupItemFields.TransactionGroupId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppTransactionGroupItemEntity and AppTransactionItemEntity over the m:1 relation they have, using the relation between the fields: AppTransactionGroupItem.TransactionId - AppTransactionItem.AppTransactionItemId</summary>
		public virtual IEntityRelation AppTransactionItemEntityUsingTransactionId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppTransactionItem", false, new[] { AppTransactionItemFields.AppTransactionItemId, AppTransactionGroupItemFields.TransactionId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppTransactionGroupItemRelations
	{
		internal static readonly IEntityRelation AppTransactionGroupEntityUsingTransactionGroupIdStatic = new AppTransactionGroupItemRelations().AppTransactionGroupEntityUsingTransactionGroupId;
		internal static readonly IEntityRelation AppTransactionItemEntityUsingTransactionIdStatic = new AppTransactionGroupItemRelations().AppTransactionItemEntityUsingTransactionId;

		/// <summary>CTor</summary>
		static StaticAppTransactionGroupItemRelations() { }
	}
}
