//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: Monday, June 8, 2026 6:07:17 PM
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using APP.LBL.HelperClasses;
using APP.LBL.FactoryClasses;
using APP.LBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace APP.LBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AppUserSkill'.<br/><br/></summary>
	[Serializable]
	public partial class AppUserSkillEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private AppSecurityUserEntity _appSecurityUser;
		private AppUserSkillListEntity _appUserSkillList;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AppUserSkillEntityStaticMetaData _staticMetaData = new AppUserSkillEntityStaticMetaData();
		private static AppUserSkillRelations _relationsFactory = new AppUserSkillRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AppSecurityUser</summary>
			public static readonly string AppSecurityUser = "AppSecurityUser";
			/// <summary>Member name AppUserSkillList</summary>
			public static readonly string AppUserSkillList = "AppUserSkillList";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AppUserSkillEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AppUserSkillEntityStaticMetaData()
			{
				SetEntityCoreInfo("AppUserSkillEntity", InheritanceHierarchyType.None, false, (int)APP.LBL.EntityType.AppUserSkillEntity, typeof(AppUserSkillEntity), typeof(AppUserSkillEntityFactory), false);
				AddNavigatorMetaData<AppUserSkillEntity, AppSecurityUserEntity>("AppSecurityUser", "AppUserSkill", (a, b) => a._appSecurityUser = b, a => a._appSecurityUser, (a, b) => a.AppSecurityUser = b, APP.LBL.RelationClasses.StaticAppUserSkillRelations.AppSecurityUserEntityUsingUserIdStatic, ()=>new AppUserSkillRelations().AppSecurityUserEntityUsingUserId, null, new int[] { (int)AppUserSkillFieldIndex.UserId }, null, true, (int)APP.LBL.EntityType.AppSecurityUserEntity);
				AddNavigatorMetaData<AppUserSkillEntity, AppUserSkillListEntity>("AppUserSkillList", "AppUserSkill", (a, b) => a._appUserSkillList = b, a => a._appUserSkillList, (a, b) => a.AppUserSkillList = b, APP.LBL.RelationClasses.StaticAppUserSkillRelations.AppUserSkillListEntityUsingSkillItemIdStatic, ()=>new AppUserSkillRelations().AppUserSkillListEntityUsingSkillItemId, null, new int[] { (int)AppUserSkillFieldIndex.SkillItemId }, null, true, (int)APP.LBL.EntityType.AppUserSkillListEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AppUserSkillEntity()
		{
		}

		/// <summary> CTor</summary>
		public AppUserSkillEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AppUserSkillEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AppUserSkillEntity</param>
		public AppUserSkillEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="userSkillId">PK value for AppUserSkill which data should be fetched into this AppUserSkill object</param>
		public AppUserSkillEntity(System.Int32 userSkillId) : this(userSkillId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="userSkillId">PK value for AppUserSkill which data should be fetched into this AppUserSkill object</param>
		/// <param name="validator">The custom validator object for this AppUserSkillEntity</param>
		public AppUserSkillEntity(System.Int32 userSkillId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.UserSkillId = userSkillId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AppUserSkillEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppSecurityUser' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppSecurityUser() { return CreateRelationInfoForNavigator("AppSecurityUser"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'AppUserSkillList' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAppUserSkillList() { return CreateRelationInfoForNavigator("AppUserSkillList"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AppUserSkillEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AppUserSkillRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppSecurityUser' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppSecurityUser { get { return _staticMetaData.GetPrefetchPathElement("AppSecurityUser", CommonEntityBase.CreateEntityCollection<AppSecurityUserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AppUserSkillList' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAppUserSkillList { get { return _staticMetaData.GetPrefetchPathElement("AppUserSkillList", CommonEntityBase.CreateEntityCollection<AppUserSkillListEntity>()); } }

		/// <summary>The UserSkillId property of the Entity AppUserSkill<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppUserSkill"."UserSkillID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 UserSkillId
		{
			get { return (System.Int32)GetValue((int)AppUserSkillFieldIndex.UserSkillId, true); }
			set { SetValue((int)AppUserSkillFieldIndex.UserSkillId, value); }
		}

		/// <summary>The SkillItemId property of the Entity AppUserSkill<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppUserSkill"."SkillItemID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> SkillItemId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppUserSkillFieldIndex.SkillItemId, false); }
			set { SetValue((int)AppUserSkillFieldIndex.SkillItemId, value); }
		}

		/// <summary>The UserId property of the Entity AppUserSkill<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppUserSkill"."UserID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> UserId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppUserSkillFieldIndex.UserId, false); }
			set { SetValue((int)AppUserSkillFieldIndex.UserId, value); }
		}

		/// <summary>The AppCreatedById property of the Entity AppUserSkill<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppUserSkill"."AppCreatedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppUserSkillFieldIndex.AppCreatedById, false); }
			set { SetValue((int)AppUserSkillFieldIndex.AppCreatedById, value); }
		}

		/// <summary>The AppCreatedDate property of the Entity AppUserSkill<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppUserSkill"."AppCreatedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppCreatedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppUserSkillFieldIndex.AppCreatedDate, false); }
			set { SetValue((int)AppUserSkillFieldIndex.AppCreatedDate, value); }
		}

		/// <summary>The AppModifiedDate property of the Entity AppUserSkill<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppUserSkill"."AppModifiedDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> AppModifiedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AppUserSkillFieldIndex.AppModifiedDate, false); }
			set { SetValue((int)AppUserSkillFieldIndex.AppModifiedDate, value); }
		}

		/// <summary>The AppModifiedById property of the Entity AppUserSkill<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppUserSkill"."AppModifiedByID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppModifiedById
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppUserSkillFieldIndex.AppModifiedById, false); }
			set { SetValue((int)AppUserSkillFieldIndex.AppModifiedById, value); }
		}

		/// <summary>The AppCreatedByCompanyId property of the Entity AppUserSkill<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AppUserSkill"."AppCreatedByCompanyID".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AppCreatedByCompanyId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AppUserSkillFieldIndex.AppCreatedByCompanyId, false); }
			set { SetValue((int)AppUserSkillFieldIndex.AppCreatedByCompanyId, value); }
		}

		/// <summary>Gets / sets related entity of type 'AppSecurityUserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppSecurityUserEntity AppSecurityUser
		{
			get { return _appSecurityUser; }
			set { SetSingleRelatedEntityNavigator(value, "AppSecurityUser"); }
		}

		/// <summary>Gets / sets related entity of type 'AppUserSkillListEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(true)]
		public virtual AppUserSkillListEntity AppUserSkillList
		{
			get { return _appUserSkillList; }
			set { SetSingleRelatedEntityNavigator(value, "AppUserSkillList"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace APP.LBL
{
	public enum AppUserSkillFieldIndex
	{
		///<summary>UserSkillId. </summary>
		UserSkillId,
		///<summary>SkillItemId. </summary>
		SkillItemId,
		///<summary>UserId. </summary>
		UserId,
		///<summary>AppCreatedById. </summary>
		AppCreatedById,
		///<summary>AppCreatedDate. </summary>
		AppCreatedDate,
		///<summary>AppModifiedDate. </summary>
		AppModifiedDate,
		///<summary>AppModifiedById. </summary>
		AppModifiedById,
		///<summary>AppCreatedByCompanyId. </summary>
		AppCreatedByCompanyId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace APP.LBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AppUserSkill. </summary>
	public partial class AppUserSkillRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between AppUserSkillEntity and AppSecurityUserEntity over the m:1 relation they have, using the relation between the fields: AppUserSkill.UserId - AppSecurityUser.UserId</summary>
		public virtual IEntityRelation AppSecurityUserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppSecurityUser", false, new[] { AppSecurityUserFields.UserId, AppUserSkillFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between AppUserSkillEntity and AppUserSkillListEntity over the m:1 relation they have, using the relation between the fields: AppUserSkill.SkillItemId - AppUserSkillList.SkillItemId</summary>
		public virtual IEntityRelation AppUserSkillListEntityUsingSkillItemId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "AppUserSkillList", false, new[] { AppUserSkillListFields.SkillItemId, AppUserSkillFields.SkillItemId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAppUserSkillRelations
	{
		internal static readonly IEntityRelation AppSecurityUserEntityUsingUserIdStatic = new AppUserSkillRelations().AppSecurityUserEntityUsingUserId;
		internal static readonly IEntityRelation AppUserSkillListEntityUsingSkillItemIdStatic = new AppUserSkillRelations().AppUserSkillListEntityUsingSkillItemId;

		/// <summary>CTor</summary>
		static StaticAppUserSkillRelations() { }
	}
}
