SET NOCOUNT ON;

-- Header-only SubItems (2)
;WITH h AS (
    SELECT TRY_CAST(RIGHT(CASE WHEN c.COLUMN_NAME LIKE '%_FK_%' 
        THEN LEFT(c.COLUMN_NAME, CHARINDEX('_FK_', c.COLUMN_NAME+'_FK_')-1) ELSE c.COLUMN_NAME END,
        CHARINDEX('_', REVERSE(CASE WHEN c.COLUMN_NAME LIKE '%_FK_%' 
        THEN LEFT(c.COLUMN_NAME, CHARINDEX('_FK_', c.COLUMN_NAME+'_FK_')-1) ELSE c.COLUMN_NAME END)+'_')-1) AS INT) AS SubItemId,
        c.COLUMN_NAME
    FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME='PLM_DW_Tab_Fabric_Header_4258'
    AND c.COLUMN_NAME NOT IN ('TabID','ProductReferenceID')
),
i AS (
    SELECT TRY_CAST(RIGHT(CASE WHEN c.COLUMN_NAME LIKE '%_FK_%' 
        THEN LEFT(c.COLUMN_NAME, CHARINDEX('_FK_', c.COLUMN_NAME+'_FK_')-1) ELSE c.COLUMN_NAME END,
        CHARINDEX('_', REVERSE(CASE WHEN c.COLUMN_NAME LIKE '%_FK_%' 
        THEN LEFT(c.COLUMN_NAME, CHARINDEX('_FK_', c.COLUMN_NAME+'_FK_')-1) ELSE c.COLUMN_NAME END)+'_')-1) AS INT) AS SubItemId
    FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME='PLM_DW_Tab_Fabric_Info_4212'
    AND c.COLUMN_NAME NOT IN ('TabID','ProductReferenceID')
)
SELECT h.SubItemId, h.COLUMN_NAME AS HeaderColumn
FROM h WHERE h.SubItemId IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM i WHERE i.SubItemId = h.SubItemId);

-- Info-only sample (first 20 of 72)
;WITH h AS (
    SELECT TRY_CAST(RIGHT(CASE WHEN c.COLUMN_NAME LIKE '%_FK_%' 
        THEN LEFT(c.COLUMN_NAME, CHARINDEX('_FK_', c.COLUMN_NAME+'_FK_')-1) ELSE c.COLUMN_NAME END,
        CHARINDEX('_', REVERSE(CASE WHEN c.COLUMN_NAME LIKE '%_FK_%' 
        THEN LEFT(c.COLUMN_NAME, CHARINDEX('_FK_', c.COLUMN_NAME+'_FK_')-1) ELSE c.COLUMN_NAME END)+'_')-1) AS INT) AS SubItemId
    FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME='PLM_DW_Tab_Fabric_Header_4258'
    AND c.COLUMN_NAME NOT IN ('TabID','ProductReferenceID')
),
i AS (
    SELECT TRY_CAST(RIGHT(CASE WHEN c.COLUMN_NAME LIKE '%_FK_%' 
        THEN LEFT(c.COLUMN_NAME, CHARINDEX('_FK_', c.COLUMN_NAME+'_FK_')-1) ELSE c.COLUMN_NAME END,
        CHARINDEX('_', REVERSE(CASE WHEN c.COLUMN_NAME LIKE '%_FK_%' 
        THEN LEFT(c.COLUMN_NAME, CHARINDEX('_FK_', c.COLUMN_NAME+'_FK_')-1) ELSE c.COLUMN_NAME END)+'_')-1) AS INT) AS SubItemId,
        c.COLUMN_NAME
    FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME='PLM_DW_Tab_Fabric_Info_4212'
    AND c.COLUMN_NAME NOT IN ('TabID','ProductReferenceID')
)
SELECT TOP 25 i.SubItemId, i.COLUMN_NAME AS InfoOnlyColumn
FROM i WHERE i.SubItemId IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM h WHERE h.SubItemId = i.SubItemId)
ORDER BY i.SubItemId;

-- Attributes composition block vs Header
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME='PLM_DW_Tab_Attributes_4213' 
AND (COLUMN_NAME LIKE '%7064%' OR COLUMN_NAME LIKE '%7065%' OR COLUMN_NAME LIKE '%4922%')
ORDER BY ORDINAL_POSITION;

-- Attributes shared with Header/Info
;WITH a AS (
    SELECT TRY_CAST(RIGHT(CASE WHEN c.COLUMN_NAME LIKE '%_FK_%' 
        THEN LEFT(c.COLUMN_NAME, CHARINDEX('_FK_', c.COLUMN_NAME+'_FK_')-1) ELSE c.COLUMN_NAME END,
        CHARINDEX('_', REVERSE(CASE WHEN c.COLUMN_NAME LIKE '%_FK_%' 
        THEN LEFT(c.COLUMN_NAME, CHARINDEX('_FK_', c.COLUMN_NAME+'_FK_')-1) ELSE c.COLUMN_NAME END)+'_')-1) AS INT) AS SubItemId
    FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME='PLM_DW_Tab_Attributes_4213'
    AND c.COLUMN_NAME NOT IN ('TabID','ProductReferenceID')
),
h AS (
    SELECT TRY_CAST(RIGHT(CASE WHEN c.COLUMN_NAME LIKE '%_FK_%' 
        THEN LEFT(c.COLUMN_NAME, CHARINDEX('_FK_', c.COLUMN_NAME+'_FK_')-1) ELSE c.COLUMN_NAME END,
        CHARINDEX('_', REVERSE(CASE WHEN c.COLUMN_NAME LIKE '%_FK_%' 
        THEN LEFT(c.COLUMN_NAME, CHARINDEX('_FK_', c.COLUMN_NAME+'_FK_')-1) ELSE c.COLUMN_NAME END)+'_')-1) AS INT) AS SubItemId
    FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME='PLM_DW_Tab_Fabric_Header_4258'
    AND c.COLUMN_NAME NOT IN ('TabID','ProductReferenceID')
)
SELECT 
    (SELECT COUNT(DISTINCT SubItemId) FROM a WHERE SubItemId IS NOT NULL) AS AttrSubItems,
    (SELECT COUNT(*) FROM a INNER JOIN h ON h.SubItemId = a.SubItemId) AS AttrSharedWithHeader,
    (SELECT COUNT(*) FROM a WHERE SubItemId IS NOT NULL AND NOT EXISTS (SELECT 1 FROM h WHERE h.SubItemId=a.SubItemId)) AS AttrOnly;

-- Fabric-related Grid tables
SELECT name FROM sys.tables WHERE name LIKE 'PLM_DW_Grid%' AND (name LIKE '%Color%' OR name LIKE '%Denim%' OR name LIKE '%Fabric%') ORDER BY name;
